### ISSUE TITLE
Request: Anthropic LLM support?

### ISSUE THREAD

**Issue by georgemandis** [hwchase17/langchainjs#1003]
I know there are efforts to keep parity with the Python version of Langchain. I'd love to see support for additional LLMs brought in as part of that effort.

In particular, porting over support for Anthropic would be very useful (for me):
- https://github.com/hwchase17/langchain/blob/master/langchain/llms/anthropic.py

Wondering if this is something on the roadmap and/or others would like?

**Comment by V01D-NULL** [comment]
yeah that would be nice.
Anthropic is quite powerful and could be amazing when combined with langchainjs

**Comment by georgemandis** [comment]
I realized (not long after opening this) there actually _is_ Anthropic support and I was just looking in the wrong place 🤦‍♂️ 
- https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chat_models/anthropic.ts

I did realize that the Python version offers Anthropic support both as an LLM _and_ a Chat Model. I'm... not actually sure what the difference would be—my impression is that Claude only has one modality (chat?)

I might close this out, but wanted to add that update in the meantime.

**Comment by V01D-NULL** [comment]
Aha... very cool!
Thank you @georgemandis
