### ISSUE TITLE
Error: SequentialChain is not a Constructor

### ISSUE THREAD

**Issue by omni-trix** [hwchase17/langchainjs#1039]
`import { SequentialChain, LLMChain } from "langchain/chains";`

`rest of the code`

`const overallChain = new SequentialChain({
  chains: [learningChain, questionChain],
  inputVariables: ["topic"],
  outputVariables: ["summary", "question"],
  verbose: true,
});`

`const response = await overallChain.call({
      topic: topic,
    });`

This throws an error:
Error [TypeError]: langchain_chains__WEBPACK_IMPORTED_MODULE_0__.SequentialChain is not a constructor
    at eval (webpack-internal:///(api)/./src/pages/api/learningContent.js:47:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  digest: undefined
}

**Comment by nfcampos** [comment]
Hi, which version of langchain are you running?

**Comment by omni-trix** [comment]
Hi, I'm using verison "langchain": "^0.0.62",

**Comment by omni-trix** [comment]
Okay I have updated the langchain version and the error is gone. Thank you so much for your help.
