### ISSUE TITLE
use official pinecone package

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchainjs#104]
https://www.npmjs.com/package/@pinecone-database/pinecone

**Comment by rschwabco** [comment]
Would love to assist!

**Comment by dqbd** [comment]
To add context, the reason why I haven't used the official pinecone NPM library is due to the usage of `axios`, which prevents us for deploying to non-Node environments. 

https://github.com/pinecone-io/pinecone-ts-client/issues/5

**Comment by nfcampos** [comment]
Done in #112
