### ISSUE TITLE
Unable to parse JSON response from chat agent

### ISSUE THREAD

**Issue by juanma1331** [hwchase17/langchainjs#1042]
Hi im getting an error when trying to use the example from here https://js.langchain.com/docs/modules/agents/agents/examples/chat_mrkl

Im using this template https://github.com/domeccleston/langchain-ts-starter and my node version is 18.16.

The error is this 
![image](https://user-images.githubusercontent.com/46537115/235228246-7ffb8c2c-af78-4c7b-be3e-89d7d00531b0.png)

**Comment by glitchyg** [comment]
I am running into something a little the same. Unable to get demos to work. @nfcampos

Code aside, this is the prompt that is being fed into GPT-4:

```
Answer the following questions as best you can. You have access to the following tools:

web-browser: useful for when you need to find something on or summarize a webpage. input should be a comma seperated list of "ONE valid http URL including protocol","what you want to find on the page or empty string for a summary".
search: a search engine. useful for when you need to answer questions about current events. input should be a search query.

Use the following format:

Question: the input question you must answer
Thought: you should always think about what to do
Action: the action to take, should be one of [web-browser,search]
Action Input: the input to the action
Observation: the result of the action
... (this Thought/Action/Action Input/Observation can repeat N times)
Thought: I now know the final answer
Final Answer: the final answer to the original input question

Begin!

Question: What is the wether like in Washington DC
Thought:
```

Just playing around in [Open API Playground](https://platform.openai.com/playground?mode=chat&model=gpt-4) I am getting inconsistent results. That prompt above with temp set to 0, give me just:

`I need to search for the current weather in Washington DC.`

But If i submit again, with that still in the history i get:

```Action: search
Action Input: current weather in Washington DC```

This is the part that langchain is failing on for me. It is refusing more often than not complete the "action:" and "action input". 

This all happened to stop working really suddenly. I was getting decent results, then it just stopped. I suspect perhaps the model was updated. I am using gpt-4 chat for this.

**Comment by nfcampos** [comment]
Thanks for reporting we're looking into this

**Comment by jacoblee93** [comment]
Was able to repro with GPT-4 and adding a few more words to the prompt seemed to fix it consistently.
