### ISSUE TITLE
Pinecone and NextJS vercel edge functions

### ISSUE THREAD

**Issue by haritiruna** [hwchase17/langchainjs#1055]
I'm making a chatbot in NextjS that talks to custom PDF docs and it works fine locally, but when I deploy to vercel, it no longer streams the responses.

I tried to convert my API route to an edge function and I'm getting this error when initialiasing pinecone:

```
error  [PineconeError: Failed getting project name. Error: A Node.js API is used (process.nextTick) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime] {
  name: 'PineconeError'
}
error - unhandledRejection: Error: Failed to initialize Pinecone Client
    at initPinecone (webpack-internal:///(middleware)/./utils/data/pinecone.ts:27:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (webpack-internal:///(middleware)/./utils/data/pinecone.ts:30:18) {
  digest: undefined
}
error - node_modules/next/dist/build/webpack/loaders/next-edge-function-loader.js?absolutePagePath=.... @ <unknown>
```

Anyone else encounter this? How do I fix it?

**Comment by nfcampos** [comment]
the Pinecone SDK is Node-only. If you want it to work outside of Node I suggest opening an issue on the Pinecone repo, we cannot do anything on our side sadly

**Comment by assafweinberg** [comment]
@nfcampos - In addition to posting an issue with Pinecone, we could also swap out the Pinecode client in Langchain for a custom one that just wraps their REST API. That should work in Node.

**Comment by brerdem** [comment]
Vercel Edge functions unfortunately break many things including Pinecone. I switched to Axios and it runs fine
