### ISSUE TITLE
Delete function for hnswlib

### ISSUE THREAD

**Issue by anandkumarpatel** [hwchase17/langchainjs#1107]
I needed this in my app since I create different indexes on one server. Not sure If I should update the interface since this might be a specific feature for disk / in-memory stores only. 

https://github.com/hwchase17/langchainjs/compare/main...anandkumarpatel:feature-hnswlib-delete?expand=1

I can add tests and flesh it out more if other people find this useful.

**Comment by anandkumarpatel** [comment]
Yea, this is still relevant.

**Comment by XueSeason** [comment]
There are some issues with this PR, for example, the code [await vectorStore.delete({ ids: uidsToDelete })](https://github.com/langchain-ai/langchainjs/blob/0.1.37/langchain/src/indexes/indexing.ts#L355) in the index to delete some data. It is clear that the current delete function does not support this and will cause an error.
