### ISSUE TITLE
[Feature] Integration with Google PaLM APIs

### ISSUE THREAD

**Issue by heqian** [hwchase17/langchainjs#1129]
Reference:

- https://github.com/hwchase17/langchain/pull/3575
- https://developers.generativeai.google/tutorials/chat_node_quickstart

**Comment by ap-1** [comment]
Is there a PR open for this? I may be able to help.

**Comment by afirstenberg** [comment]
@ap-1 - The VertexAI PaLM models have been fully integrated for several versions now.

I've had the "PaLM API" models on hold until they make them available without the wait list. But if you'd like to tackle it - go for it! (I'm currently backlogged on trying to get Matching Engine to work.)

**Comment by anselm94** [comment]
@ap-1 @afirstenberg I just raised a PR for Google PaLM support :). Yet to write documentation and have to make some changes to be compatible with Python implementation [here](https://github.com/hwchase17/langchain/pull/3575)
