### ISSUE TITLE
figma doc loader

### ISSUE THREAD

**Issue by ghostlpx** [hwchase17/langchainjs#1132]
I found that figma doc loader is available in the [python repo](https://github.com/hwchase17/langchain/blob/6e1b5b8f7eb3004555062ec2e2cd501eba2f5822/langchain/document_loaders/figma.py), but I am not familiar with Python code. It makes a lot of sense for figma design to code.
I would really appreciate it if someone could contribute the figma doc loader code.

thanks again!

**Comment by munkhorgil** [comment]
Here is WIP [PR](https://github.com/hwchase17/langchainjs/pull/1148)

**Comment by ghostlpx** [comment]
> Here is WIP [PR](https://github.com/hwchase17/langchainjs/pull/1148)

That's fast👍
