### ISSUE TITLE
Callback for after saveContext is called?

### ISSUE THREAD

**Issue by Emsu** [hwchase17/langchainjs#1158]
I tried to use handleChainEnd to check things in history after they're saved. However I found in the code that there's no way currently to execute a callback after context is saved.

<img width="494" alt="Screen Shot 2023-05-08 at 12 58 26 AM" src="https://user-images.githubusercontent.com/477917/236768893-f0ba774a-d356-4df3-a115-c7b69fb1c29a.png">

Would it make sense to either move the `handleChainEnd` to after context is saved?
Or add a new callback after `handleChainEnd`?
Maybe `handleSaveContext`?

I could do a PR to add a new callback if that's the way to go.

**Comment by nfcampos** [comment]
Hi @Emsu thanks for opening this issue, great feedback. I think the best solution is actually to move handleChainEnd to after context is updated, as that's part of the chain run, so end should come after, do you want to open a PR moving it?
