### ISSUE TITLE
Better Typings for PromptTemplate.fromTemplate

### ISSUE THREAD

**Issue by iway1** [hwchase17/langchainjs#1171]
Right now the type for "format" returned from `PromptTemplate.fromTemplate` is `Record<string, any>`.

Using typescript string template literals, it's possible to infer the format types so that we get typesafety when calling `.format` with no extra work from the developer. So we'd get static typechecking ensuring we pass correct parameter names to format. 

Before: 
![Screenshot 2023-05-08 at 2 19 29 PM](https://user-images.githubusercontent.com/12774588/236913298-a48d2dbb-8188-4ce3-8e38-2e2da4f80e90.png)

After:

![Screenshot 2023-05-08 at 2 23 10 PM](https://user-images.githubusercontent.com/12774588/236914035-8d0ba076-cb3c-4205-a7dd-64f6dc87ea8a.png)

![Screenshot 2023-05-08 at 2 23 22 PM](https://user-images.githubusercontent.com/12774588/236914071-39d1717b-136b-4f90-963f-b752458c1424.png)
![Screenshot 2023-05-08 at 2 32 38 PM](https://user-images.githubusercontent.com/12774588/236915995-b4c1b5f2-a824-4190-ac55-7ffc664d1a44.png)

As you can see, we get errors if we mispell an input name or if we forget a parameter. Also we get autocomplete on parameter names. 

With this simple change, we can make our code a lot safer and improve the developer experience. Instead of our code breaking at run time, we get immediate feedback. Can do this with any of the string based templating in the lib

Let me know if we want to add this and I'll create a PR. stuff like this really increases usability

**Comment by jacoblee93** [comment]
This would be really cool!

**Comment by jacoblee93** [comment]
Added this in #1528
