### ISSUE TITLE
node:fs/promises error with HNSWLib in Next.js Edge Functions

### ISSUE THREAD

**Issue by naveedjanmo** [hwchase17/langchainjs#1179]
I'm getting an error when importing HNSWLib vectorstore inside a Next.js Edge function. It works in Serverless runtime but not Edge.

`import { HNSWLib } from 'langchain/vectorstores/hnswlib'`

```
error - node:fs/promises
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
Import trace for requested module:
node:fs/promises
./node_modules/langchain/dist/vectorstores/hnswlib.js
./node_modules/langchain/vectorstores/hnswlib.js
```

This seems like the same error some people were getting before support for Edge functions was released. Tried all the proposed solutions in #378 to no avail. I also tried importing other vectorstores (Pinecone and SupabaseVectorStore) and they both worked fine. I have an exisiting project running on HNSWLib so need to stick with it if possible.

I'm running `"langchain": "^0.0.56"` and `"hnswlib-node": "^1.4.2"`.

Any help would be really appreciated :)

**Comment by nfcampos** [comment]
Unfortunately per our docs HNSWLib is only supported in Node.js, this is not a langchain limitation, it's how the HNSWLib library is designed, see the docs for alternatives https://js.langchain.com/docs/modules/indexes/vector_stores

**Comment by robinmuhia** [comment]
Hello. I am encountering the same problem. Did you manage to resolve it?

**Comment by naveedjanmo** [comment]
Nope -- it's a limitation with HNSWLib. If it's just streaming you want, try deploying on Fly io where it's supported for Serverless functions.

**Comment by robinmuhia** [comment]
Thanks G. Was using it for langchain. Will just switch to pinecone
