### ISSUE TITLE
Aborting an agent

### ISSUE THREAD

**Issue by rafalzawadzki** [hwchase17/langchainjs#1187]
I am working with the [experimental AutoGPT agent](https://js.langchain.com/docs/use_cases/autonomous_agents/auto_gpt) and wonder if there's a way to stop its execution similarly to an [LLM model](https://js.langchain.com/docs/modules/models/llms/additional_functionality)?

```js
const res = await model.call(
    "What would be a good company name a company that makes colorful socks?",
    {
      options: {
        signal: controller.signal,
      },
    }
  );
```

At this point seems to me like there is no way to stop an agent and given how pricey and time consuming they are it poses a bit of a problem. Am I missing something?

**Comment by Emsu** [comment]
@rafalzawadzki I had a similar question. @nfcampos opened a PR here: https://github.com/hwchase17/langchainjs/pull/1182/files

**Comment by rafalzawadzki** [comment]
> @rafalzawadzki I had a similar question. @nfcampos opened a PR here: https://github.com/hwchase17/langchainjs/pull/1182/files

Wow amazing luck :) 

I think for now I found a workaround which is adding abort signal to the model like this:
```js
const autogpt = AutoGPT.fromLLMAndTools(
  new ChatOpenAI(
    { temperature: 0 }, 
    { baseOptions: { signal: abortSignal }}
  ),
  tools,
  {
    memory: vectorStore.asRetriever(),
    aiName: "Tom",
    aiRole: "Assistant",
  }
);
```

It seems to be quite severe and results in the chain (or llm?) throwing an exception but at least makes the whole run stop immediately :)
