### ISSUE TITLE
Adding example for PDF document loader 

### ISSUE THREAD

**Issue by JeremyFabrikapp** [hwchase17/langchainjs#1209]
I couldn't find an example for PDF document loader while there is a wonderful document loader for it.

I will create a PR related to this issue with a basic implementation.

**Comment by shawnesquivel** [comment]
bump, would love to see this !

**Comment by JeremyFabrikapp** [comment]
I've added a couple of PR related to this issue @shawnesquivel ! Actually it's very basic but much more can be done like saving to Memory, embeddings etc. But let's keep it simple 😄

**Comment by nfcampos** [comment]
Thanks both!
