### ISSUE TITLE
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme)

### ISSUE THREAD

**Issue by dev2049** [hwchase17/langchainjs#1211]
Believe this issue is meant for here https://github.com/hwchase17/langchain/issues/4491

cc @ruai0511

**Comment by jacoblee93** [comment]
Hey @ruai0511, responded on the other issue in the Python repo as well, but am responding here for visibility.

> Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme)

We've deprecated importing from `langchain/vectorstores` and `langchain/embeddings` in favor of new entrypoints to avoid issues like this (some other vector stores are Node only and use fs).

In your case the imports would be `import { Chroma } from "langchain/vectorstores/chroma"` and `import { OpenAIEmbeddings} from "langchain/embeddings/openai"` - can you try changing to that (and perhaps updating your LangChainJS version)?
