### ISSUE TITLE
TokenTextSplitter doesn't support special tokens

### ISSUE THREAD

**Issue by darknoon** [hwchase17/langchainjs#122]
It seems that this is a [known issue](https://github.com/hwchase17/langchainjs/blame/4ecf055e760a66eeec4e15f755921e38d8372f51/langchain/text_splitter.ts#L214) but wanted to call it out explicitly since we're (Diagram) interested in helping bring the WASM tokenizer up to parity with python tiktoken for our usage. Not currently using langchain, but would be interested in adopting bits and pieces.

**Comment by hwchase17** [comment]
@dqbd any plans to add this in?

**Comment by dqbd** [comment]
Currently working on it, next version should include support for both `allowedSpecial` and `disallowedSpecial`

**Comment by dqbd** [comment]
Should be resolved with the accompanying PR #134
