### ISSUE TITLE
Google Vertex AI PaLM Support

### ISSUE THREAD

**Issue by afirstenberg** [hwchase17/langchainjs#1240]
Reference: hwchase17/langchain#4532

Although there is an open issue for the PaLM API integration (#1129), these APIs are different and should be tracked separately.

I would be willing to work on this one as well and coordinate with @Jflick58 on the Python side.

**Comment by danny-avila** [comment]
Would love to see this integrated. I’m curious how it will perform given the examples parameter which explicitly defines expected outputs to the API. I still need to test this bit myself.

I just integrated PaLM 2 into my project here: https://github.com/danny-avila/chatgpt-clone

My chief complaint is that the moderation filter is pretty high. It will false flag certain topics consistently. Also despite its ability to translate well, it will refuse to answer messages without any English.

**Comment by Jflick58** [comment]
@afirstenberg  let's do it. Want to connect on the langchain discord?

**Comment by sounishnath003** [comment]
I am also eager to work on this integration. I would love to hear more on this as soon as possible.

It certainly will be a nice feature to introduce to langchain ecosystem.

**Comment by afirstenberg** [comment]
For those interested, the first integration (text) was just merged into main with #1273. Expect Chat and Embedding support soon.

**Comment by danny-avila** [comment]
> For those interested, the first integration (text) was just merged into main with #1273. Expect Chat and Embedding support soon.

Awesome work!!!

**Comment by afirstenberg** [comment]
These are now available as of versions 0.0.80 and 0.0.82.

**Comment by sounishnath003** [comment]
Thank you so much @afirstenberg for the Google Palm support for langchainjs.
