### ISSUE TITLE
LangChain OpenAI doesn't work with Azure OpenAI GPT 3.5 Turbo deployed models

### ISSUE THREAD

**Issue by basyonic** [hwchase17/langchainjs#1247]
using LangChain not working with Azure Open AI deployed model

running below code, generates error
```
  const model = new OpenAI({ temperature: 0.1,
    azureOpenAIApiKey: "xxx",
    azureOpenAIApiInstanceName: "xxx",
    azureOpenAIApiDeploymentName: "xxx",
    azureOpenAIApiVersion: "xxx" });

  const res = await model.call("What is the capital city of France?");
```
error
```
logprobs, best_of and echo parameters are not available on gpt-35-turbo model. Please remove the parameter and try again. For more details, see https://go.microsoft.com/fwlink/?linkid=2227346.
```

**Comment by sutekyara** [comment]
same error message appeared

**Comment by windmemory** [comment]
Seems like this is a bug in langchain.js. I have a workaround to make it work, but not ideal.

Here is the config that works without throwing errors:
```ts
  const model = new OpenAI({ temperature: 0.1,
    azureOpenAIApiKey: "xxx",
    azureOpenAIApiInstanceName: "xxx",
    azureOpenAIApiDeploymentName: "text-davinci-003",
    azureOpenAIApiVersion: "xxx" });

  const res = await model.call("What is the capital city of France?");
```

And here is the config that does not work
```ts
  const model = new OpenAI({ temperature: 0.1,
    azureOpenAIApiKey: "xxx",
    azureOpenAIApiInstanceName: "xxx",
    azureOpenAIApiDeploymentName: "chatgpt-3.5",
    azureOpenAIApiVersion: "xxx" });

  const res = await model.call("What is the capital city of France?");
```

The main difference is that using a `chatgpt-3.5` model will not work correctly here, but is you use a model that is `text-davinci-003`, it will work.

So this should be a bug using wrong params or endpoints when calling azure openAI completion endpoint.

**Comment by windmemory** [comment]
I think I figured out how to fix this problem, it is pretty easy here, just change the `OpenAI` class to be `OpenAIChat`, then everything works smoothly!

From this
```ts
import { OpenAI } from 'langchain/llms/openai';

const model = new OpenAI({ temperature: 0.1,
  azureOpenAIApiKey: "xxx",
  azureOpenAIApiInstanceName: "xxx",
  azureOpenAIApiDeploymentName: "chatgpt-3.5",don't directly use this name.
  azureOpenAIApiVersion: "xxx" });

const res = await model.call("What is the capital city of France?");
```

To this
```ts
import { OpenAIChat } from 'langchain/llms/openai';

const model = new OpenAIChat({ temperature: 0.1,
  azureOpenAIApiKey: "xxx",
  azureOpenAIApiInstanceName: "xxx",
  azureOpenAIApiDeploymentName: "chatgpt-3.5",don't directly use this name.
  azureOpenAIApiVersion: "xxx" });

const res = await model.call("What is the capital city of France?");
```

CC @basyonic @sutekyara @ElodieComte

**Comment by ElodieComte** [comment]
Thanks a lot @windmemory. 
For my purpose I’m using ChatOpenAI: https://js.langchain.com/docs/modules/models/chat/integrations#azure-chatopenai
I'm pretty sure it wasn't working yesterday 🤷  
Anyway, I think the issue's closed @basyonic ?

**Comment by basyonic** [comment]
Thanks @windmemory , but I think OpenAIChat under the hood calls chat endpoint (/chat/completions) this is different than completion endpoint (/completions) and it may be returning different response

**Comment by ElodieComte** [comment]
you have to call chat completions endpoint to use gpt-3.5-turbo model
https://platform.openai.com/docs/models/model-endpoint-compatibility

**Comment by sutekyara** [comment]
@windmemory 
it works well thanks for your advise.
