### ISSUE TITLE
Async_call Regression in x.75 from x.74 

### ISSUE THREAD

**Issue by albert-carreras** [hwchase17/langchainjs#1248]
My MemoryVectorStore similaritySearch timesout with a "ReferenceError: Property 'TextEncoder' doesn't exist".

I think there were some changes in async_call.js that broke the embeddings call

**Comment by nfcampos** [comment]
Hi, can you confirm which version of Node, or other JS environment, you're running this on? TextEncoder is available in Node.js since version 11.0, The current version is 20.x

**Comment by albert-carreras** [comment]
Running it in the browser, as the MemoryVectorStore was marked as working without Node, it was working fine before!

**Comment by nfcampos** [comment]
@albert-carreras See here the compat table for TextEncoder https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder#browser_compatibility I suggest adding a polypill if you're running in an older browser
