### ISSUE TITLE
The requested module 'langchain' does not provide an export named 'VectorStoreInfo'

### ISSUE THREAD

**Issue by rajanpanchal** [hwchase17/langchainjs#1257]
I keep getting errors when using the example from  here 
https://js.langchain.com/docs/modules/agents/toolkits/vectorstore
`The requested module 'langchain' does not provide an export named 'VectorStoreInfo'`
I also had to change the const declaration as below because node kept complaining about VectoreStore

```
/* Create the agent */
 const vectorStoreInfo = {
  name: "state_of_union_address",
  description: "the most recent state of the Union address",
  vectorStore,
};
```
But still get the VectoreStore Error not provided in langchain

**Comment by nfcampos** [comment]
Hi, can you confirm you're running this with TypeScript? The export does exist, it is a TypeScript interface, see https://js.langchain.com/docs/api/agents/interfaces/VectorStoreInfo
