### ISSUE TITLE
Streaming and API Error

### ISSUE THREAD

**Issue by A-F-V** [hwchase17/langchainjs#1265]
If the LLM (in my case ChatOpenAI) has `streaming` to true and there is an **API** exception, instead of throwing an exception for that API error, it instead throws an exception saying that it failed to parse the response from server:
> Error in handler Handler, handleLLMError: Error: Expected content-type to be text/event-stream, Actual: application/json; charset=utf-8

This means that you cannot actually report if, say, the API key was invalid from a streamed request.

My proposal is that **the API error is raised instead**

**Comment by A-F-V** [comment]
Correct please still address

**Comment by jacoblee93** [comment]
Hey @A-F-V, we have a brand new stream method you can try instead that should work better!

 https://js.langchain.com/docs/guides/expression_language/interface
