### ISSUE TITLE
No loader is configured for ".wasm" files

### ISSUE THREAD

**Issue by logancyang** [hwchase17/langchainjs#1276]
Hi, I'm trying to use langchainJS in an Obsidian plugin, and the plugin system uses esbuild. Seeing this error after I added langchain to my plugin

```
> node esbuild.config.mjs

[watch] build finished, watching for changes...
✘ [ERROR] No loader is configured for ".wasm" files: node_modules/@dqbd/tiktoken/tiktoken_bg.wasm

    node_modules/@dqbd/tiktoken/tiktoken.js:1:22:
      1 │ import * as wasm from "./tiktoken_bg.wasm";
```

I'm quite new to all this, not sure what issues need to be solved in order for me to proceed. Here's what I tried: I installed https://github.com/Tschrock/esbuild-plugin-wasm but it introduced a new error where it complains about top-level awaits. This esbuild-plugin-wasm readme actually has the note that says

> This loader makes use of top-level await, which only has partial support in esbuild. For now, it is only supported with the esm output format, not the iife or cjs formats. See https://github.com/evanw/esbuild/issues/253

I checked that esbuild issue there, but it was still open from 2020, seems not going to change anytime soon. 

Can someone please kindly help me understand what needs to be done in order for me to use langchainjs in my Obsidian plugin? Switching the bundler from esbuild to something else probably isn't an option for me.

I saw this issue https://github.com/hwchase17/langchainjs/pull/1239, but not sure if this solves my problem.

**Comment by Tangjj1996** [comment]
I met the same problem, and I used `esbuild WebAssembly plugin` to solve this. Maybe you can try.
https://esbuild.github.io/plugins/#webassembly-plugin

**Comment by moltenform** [comment]
I am also building an Obsidian plugin!

As an alternative, I didn't use an esbuild plugin, but instead I added

```
loader: {
        '.wasm': 'binary',
 },
```

to the `esbuild.config.mjs` file and also set the `target: "es2020"`.

This also resolved an error where the path to the wasm file was not being found.
