### ISSUE TITLE
Incompatibility of `ChatOpenAI` with Azure OpenAI due to EventStream Handling

### ISSUE THREAD

**Issue by yuku** [hwchase17/langchainjs#1299]
### Description

Currently, the `langchain.js` library is unable to successfully resolve `ChatOpenAI` when used with Azure OpenAI streaming because of the differences in the responses from OpenAI's and Azure's APIs. 

The OpenAI's chat completions API ends with a blank line:

![response from openai](https://github.com/hwchase17/langchainjs/assets/96157/41d8db4f-0517-427d-95f3-44ab648c11d6)

In contrast, Azure's OpenAI API doesn't send a blank line at the end:

![response from azure openai](https://github.com/hwchase17/langchainjs/assets/96157/48761943-a127-4ac9-8f00-46dfd53c9a9c)

`Langchain.js` uses `src/event-source-parse.ts`, originally copied from [fetch-event-source](https://github.com/gfortaine/fetch-event-source/blob/main/src/parse.ts), to handle EventSource. This code dispatches `onMessage` when a blank line is encountered, based on the standard:

> * If the line is empty (a blank line)
>     * Dispatch the event, as defined below.
>
> *[9.2.6 Interpreting an event stream](https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation)*

https://github.com/hwchase17/langchainjs/blob/d60eae5995a0d414f7684fc9c113c91c712c7af0/langchain/src/util/event-source-parse.ts#L148-L149

The problem arises in `ChatOpenAI`, where due to the absence of a blank line in Azure's OpenAI response, the promise never resolves:

https://github.com/hwchase17/langchainjs/blob/d60eae5995a0d414f7684fc9c113c91c712c7af0/langchain/src/chat_models/openai.ts#L302-L308

### Possible Solutions

1. **Microsoft sends a blank line at the end of response**: This would make Azure's OpenAI compatible with OpenAI's API. However, convincing Microsoft to alter their API behavior may be difficult, especially since their current implementation is valid according to the standard.

2. **Patch `src/event-source-parse.ts`**: Modifying this module to allow handling of Azure's OpenAI response without requiring a blank line could solve the issue.

In order to maintain broad compatibility with different APIs, I recommend exploring the second solution. We need to ensure that our library can handle responses from different APIs that follow the standard, even if they interpret it slightly differently.

**Comment by yuku** [comment]
If the solution 2 makes sense, I'd like to open a pull request. Please let me know.

**Comment by jacoblee93** [comment]
Option 2 definitely sounds better - maybe add some config or options to let it ignore that just for Azure OpenAI?

**Comment by yuku** [comment]
The crux of the problem is that the `onMessage` callback doesn't get triggered with the last `message`. An interesting approach might be to introduce a `flush` option. If set to `true`, the callback would be invoked with any unhandled `message` once the readstream reaches its end.

Alternatively, we could adjust `src/event-source-parse.ts` to always dispatch any lingering message upon reaching the end of the stream. This seems reasonable given that there likely wouldn't be any practical cases where we'd intentionally ignore the last message. This adjustment could ensure we handle responses thoroughly without needing to specifically configure the `flush` option.
