### ISSUE TITLE
Error on Chroma.fromTexts() when creating a collection

### ISSUE THREAD

**Issue by kradyy** [hwchase17/langchainjs#1311]
I encountered an error while using the Chroma.fromTexts() function in the Langchain library. The error occurs when attempting to create a collection using the fromTexts() method. The function throws an error with the message throw new Error(newCollection.error).

**Use the following [example code snippet](https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/chroma):**
```
// Import necessary libraries and modules
import { Chroma, OpenAIEmbeddings } from 'langchain';

// Define the texts and metadata
const texts = [
  `Tortoise: Labyrinth? Labyrinth? Could it Are we in the notorious Little
  Harmonic Labyrinth of the dreaded Majotaur?`,
  "Achilles: Yiikes! What is that?",
  `Tortoise: They say-although I person never believed it myself-that an I
  Majotaur has created a tiny labyrinth sits in a pit in the middle of
  it, waiting innocent victims to get lost in its fears complexity.
  Then, when they wander and dazed into the center, he laughs and
  laughs at them-so hard, that he laughs them to death!`,
  "Achilles: Oh, no!",
  "Tortoise: But it's only a myth. Courage, Achilles.",
];

const metadatas = [{ id: 2 }, { id: 1 }, { id: 3 }];

// Create OpenAIEmbeddings instance
const embeddings = new OpenAIEmbeddings();

// Create Chroma vector store
const vectorStore = await Chroma.fromTexts(texts, metadatas, embeddings, {
  collectionName: "godel-escher-bach",
});
```

**Expected Behavior:**

The Chroma.fromTexts() function should create a new Chroma vector store and perform a similarity search without errors.

**Actual Behavior:**

An error is thrown during the creation of the collection in Chroma's index.js file. The error message received is newCollection.error. The server is running - i checked docker and i get an endpoint request with a 422 error.

`chroma-server-1      | 2023-05-18 09:36:46 INFO     uvicorn.access  192.168.48.1:61414 - "POST /api/v1/collections HTTP/1.1" 422`

It seems to be due to getOrCreateCollection in production **langchain/dist/chroma.js** only passing a name but it excepts an object:
```
  async ensureCollection() {
        if (!this.collection) {
            if (!this.index) {
                const { ChromaClient } = await Chroma.imports();
                this.index = new ChromaClient(this.url);
            }
            this.collection = await this.index.getOrCreateCollection(this.collectionName);
        }
        return this.collection;
    }
```

And in **/chromadb/dist/main/index.js**
```
    async getOrCreateCollection({ name, metadata, embeddingFunction }) {
        const newCollection = await this.api
            .createCollection({
            name,
            metadata,
            'get_or_create': true
        })
            .then(handleSuccess)
            .catch(handleError);
        if (newCollection.error) {
            throw new Error(newCollection.error);
        }
        return new Collection(name, newCollection.id, this.api, newCollection.metadata, embeddingFunction);
    }
```

**Additional Details:**

Langchainjs version: 0.0.76
Chromadb version: 1.4.2

**Error Stack Trace:**
```
newCollection.error
    at getOrCreateCollection (index.js:37)
    at Chroma.addDocuments (chroma.js:82)
    at Chroma.fromTexts (chroma.js:138)
```

**Comment by thisisommore** [comment]
+1, there seems to be signature miss match between functions
for example,
Langchain usage - https://github.com/hwchase17/langchainjs/blob/2943cc382724381d38da4635d92f7525f6656127/langchain/src/vectorstores/chroma.ts#L57
Original definition - https://github.com/chroma-core/chroma/blob/main/clients/js/src/index.ts#L864

**Comment by jacoblee93** [comment]
Can you try updating your package to > 1.4.2? #1348 should have fixed this.

**Comment by rodrigo398** [comment]
> Can you try updating your Chroma package to > 1.4.2 and bumping your LangChainJS version? #1348 should have fixed this.

Yes, I've just done this and it definitely fix this issue. Thanks @jacoblee93

**Comment by jacoblee93** [comment]
Excellent, thank you!

**Comment by satpalsr** [comment]
I was trying this [example ](https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/chroma#usage-index-and-query-documents)
```
 const chromaInst = await Chroma.fromDocuments(docs, new OpenAIEmbeddings(), {
        collectionName: "a-test-collection",
      });;
      ```
      
  I get error
  ```
  Error: Chroma getOrCreateCollection error: Error: TypeError: fetch failed
  ```
  
"langchain": "^0.0.96",
"chromadb": "^1.5.3",

**Comment by sudhamjayanthi** [comment]
> I was trying this [example ](https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/chroma#usage-index-and-query-documents)
> 
> ```
>  const chromaInst = await Chroma.fromDocuments(docs, new OpenAIEmbeddings(), {
>         collectionName: "a-test-collection",
>       });;
> ```
> 
> I get error
> 
> ` Error: Chroma getOrCreateCollection error: Error: TypeError: fetch failed`
> 
> "langchain": "^0.0.96", "chromadb": "^1.5.3",

i still get the same error! have you been able to solve it?

**Comment by jwhenry28** [comment]
@satpalsr @sudhamjayanthi Did either of you discover a solution?
