### ISSUE TITLE
`Error: input values have 2 keys` when using abort signal mid streaming for ConversationChain

### ISSUE THREAD

**Issue by logancyang** [hwchase17/langchainjs#1327]
Hi, I saw this example in the doc https://js.langchain.com/docs/modules/chains/llm_chain#cancelling-a-running-llmchain so I tried this code:

```js
import { ConversationChain } from "langchain/chains";
import { ChatOpenAI } from 'langchain/chat_models/openai';
import { BufferWindowMemory } from "langchain/memory";
import {
  ChatPromptTemplate,
  HumanMessagePromptTemplate,
  MessagesPlaceholder,
  SystemMessagePromptTemplate,
} from "langchain/prompts";

const chatOpenAI = new ChatOpenAI({
  openAIApiKey: 'MY_API_KEY',
  modelName: 'gpt-3.5-turbo',
  temperature: 0.7,
  streaming: true,
  callbacks: [{
    handleLLMNewToken: (token) => {
      console.log(token);
    }
  }]
});

const memory = new BufferWindowMemory({
  k: 2,
  memoryKey: 'history',
  returnMessages: true,
});

const chatPrompt = ChatPromptTemplate.fromPromptMessages([
  SystemMessagePromptTemplate.fromTemplate('you are a helpful assistant'),
  new MessagesPlaceholder("history"),
  HumanMessagePromptTemplate.fromTemplate("{input}"),
]);

const chain = new ConversationChain({
  llm: chatOpenAI,
  memory: memory,
  prompt: chatPrompt,
});
const controller = new AbortController();

// Call `controller.abort()` somewhere to cancel the request.
setTimeout(() => {
  controller.abort();
}, 3000);

try {
  // Call the chain with the inputs and a callback for the streamed tokens
  const res = chain.call(
    { input: "hello who are you?", signal: controller.signal },
    [
      {
        handleLLMNewToken(token) {
          console.log(token);
        },
      },
    ]
  );
} catch (e) {
  console.log(e);
}
```

The abort signal **did** work, the stream was stopped successfully. However, this error below still showed up. In my application I have other logic after `chain.call`, and this error is messing it up. Am I doing it wrong or is there something to be fixed?

```
Error: input values have 2 keys, you must specify an input key or pass only 1 key as input
    at getInputValue
    at BufferWindowMemory.saveContext
    at ConversationChain.call
...
```

Can someone kindly take a look? Thanks in advance!

**Comment by CrankGentleman** [comment]
I also encountered the same problem and am waiting for the official repair

**Comment by logancyang** [comment]
@CrankGentleman I've tried to use `try... catch... finally` and put my logic after `chain.call` into `finally`, and ignore this error. However, the thing is that `chain.call` still fails with this error, so it won't properly update my conversation memory with the new message. Do you happen to know some temporary hack that works?

Some input from the LangchainJS maintainers would be appreciated.

**Comment by CrankGentleman** [comment]
@logancyang I also encountered the same problem during the process of using cancellation requests. My business logic is to cancel requests, and as for the historical records, I have not yet covered them, catch It cannot solve the actual problem.

**Comment by logancyang** [comment]
@nfcampos Hi sorry to tag you, I saw this PR https://github.com/hwchase17/langchainjs/pull/1182 and thought you might have some insights around this issue, could you help us understand it better, and how to fix?

**Comment by CrankGentleman** [comment]
@nfcampos Unable to cancel request. chain.call add option signal error message **input values have 2 keys**

**Comment by clemenspeters** [comment]
Adding `inputKey: "question",` to `BufferMemory` solved it for me:
```JS
const memory = new BufferMemory({
  inputKey: "question",
  chatHistory: new DynamoDBChatMessageHistory({
    tableName: "langchain",
    partitionKey: "id",
    sessionId: new Date().toISOString(), // Or some other unique identifier for the conversation
    config: {
      region: "us-east-2",
      credentials: {
        accessKeyId: "<your AWS access key id>",
        secretAccessKey: "<your AWS secret access key>",
      },
    },
  }),
});
```

**Comment by logancyang** [comment]
> Adding `inputKey: "question",` to `BufferMemory` solved it for me:
> 
> ```js
> const memory = new BufferMemory({
>   inputKey: "question",
>   chatHistory: new DynamoDBChatMessageHistory({
>     tableName: "langchain",
>     partitionKey: "id",
>     sessionId: new Date().toISOString(), // Or some other unique identifier for the conversation
>     config: {
>       region: "us-east-2",
>       credentials: {
>         accessKeyId: "<your AWS access key id>",
>         secretAccessKey: "<your AWS secret access key>",
>       },
>     },
>   }),
> });
> ```

Thanks! I added `inputKey: "input"` and it works now. Closing.

**Comment by masa8x** [comment]
Looks tricky though, It works! This was a big help. Awesome! Thanks!

**Comment by masa8** [comment]
Looks tricky though, it works! This was a big help. Awesome! Thanks!

**Comment by Chibionos** [comment]
This works but why is adding inputKey work? We looked into the code and it doesn't make sense. Can we get a proper fix here. @logancyang

**Comment by logancyang** [comment]
@Chibionos probably best to ask the maintainers. Feel free to open a new issue with your specific problem and tag them. I do find it a bit confusing a convoluted. At least the documentation should point it out explicitly, cuz I followed the documentation directly.

**Comment by jacoblee93** [comment]
Yes we 100% want to fix this - will reopen and work towards a more intuitive solution!

**Comment by jondwillis** [comment]
@nfcampos This is still happening for me on version 0.0.96 with an AgentExecutor.
```stack: 'Error: input values have 2 keys, you must specify an input key or pass only 1 key as input\n' +
@acme/nextjs:dev:     '    at getInputValue (/langchain/dist/memory/base.js:16:11)\n' +
@acme/nextjs:dev:     '    at ConversationSummaryMemory.saveContext (/langchain/dist/memory/chat_memory.js:38:49)\n' +
@acme/nextjs:dev:     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n' +
@acme/nextjs:dev:     '    at async ConversationSummaryMemory.saveContext (/langchain/dist/memory/summary.js:82:9)\n' +
@acme/nextjs:dev:     '    at async AgentExecutor.call (/langchain/dist/chains/base.js:91:13)\n' +```

initiating call:
``` executor = await initializeAgentExecutorWithOptions(tools, llm, {
      agentType: "chat-conversational-react-description",
      streaming: true,
      returnIntermediateSteps: true,
      memory,
      ...creationProps,
    });```
    
 Strangely, I also see several successful llm starts, chain starts, ends, which should have called `saveContext` on memory if I am not mistaken, before it crashes on a further attempt.
