### ISSUE TITLE
vector stores Milvus need to update

### ISSUE THREAD

**Issue by jbeetle** [hwchase17/langchainjs#1333]
collectionManager are no longer necessary, you can call methods directly on the client object.                                                                                                          
indexManager are no longer necessary, you can call methods directly on the client object.                                                                                                               
dataManager are no longer necessary, you can call methods directly on the client object.                                                                                                                
error [Error: Error inserting data: {"succ_index":[],"err_index":[0,1,2,3,4],"status":{"error_code":"UnexpectedError","reason":"**string is not supported now**","code":0},"IDs":null,"acknowledged":false,"
insert_cnt":"0","delete_cnt":"0","upsert_cnt":"0","timestamp":"0"}]                                                                                                                                     
file:///home/workdir/chatpdfjs/scripts/ingest-data.js:104                                                                                                                                               
        throw new Error("Failed to ingest your data");

**Comment by jacoblee93** [comment]
Should be fixed by #1024

**Comment by jacoblee93** [comment]
You should also make sure the version of Milvus you're running is in sync with the client you installed as a peer dependency - now that I've looked a bit deeper I think the `you can call methods directly on the client object.` warnings shouldn't have been stopping anything.
