### ISSUE TITLE
[ERROR] : Invalid _type: undefined

### ISSUE THREAD

**Issue by apollo0102** [hwchase17/langchainjs#1355]
const docChain = loadQAChain(new OpenAIChat({}), { prompt: IMPROVED_QA_PROMPT });

It works well on old version. I faced the error after upgrading the langchain version to the latest.
What's the reason?

**Comment by apollo0102** [comment]
"langchain": "^0.0.77",

**Comment by jacoblee93** [comment]
We suggest using the `ChatOpenAI` class rather than `OpenAIChat` in general.

Happy to take a look at the issue - can you paste your code here?
