### ISSUE TITLE
Update chroma integration to support `1.5.0`

### ISSUE THREAD

**Issue by jeffchuber** [hwchase17/langchainjs#1362]
`1.5.0` has a breaking change that swaps to named inputs from positional. 

Can you assign this issue to me?

**Comment by jacoblee93** [comment]
Hey @jeffchuber, this PR should be merged and released with a fix tomorrow: https://github.com/hwchase17/langchainjs/pull/1348

**Comment by jeffchuber** [comment]
@jacoblee93 incredible! 🚀
