### ISSUE TITLE
/document_loaders/fs/unstructured.ts file, missing a package?

### ISSUE THREAD

**Issue by iamwill123** [hwchase17/langchainjs#1364]
https://github.com/hwchase17/langchainjs/blob/4ca0b5f400ae961a46b4c07d738eff2b48eeee57/langchain/src/document_loaders/fs/unstructured.ts#L87

Since this is running in a Node env, I think we need the `FormData` npm package right?

I'm currently getting this error, I'm not sure if it's just me doing something wrong 🤷🏼‍♂️ 
<img width="1539" alt="Screenshot 2023-05-22 at 9 31 20 PM" src="https://github.com/hwchase17/langchainjs/assets/15272175/49d3145b-a788-4c1f-95f2-0279fe61b071">

**Comment by jacoblee93** [comment]
It should be there in Node 18:
https://developer.mozilla.org/en-US/docs/Web/API/FormData#browser_compatibility

What version of Node are you running?
