### ISSUE TITLE
Agent with `StructuredTool` is not finishing the chain, and stuck with infinite loop.

### ISSUE THREAD

**Issue by leric7** [hwchase17/langchainjs#1366]
I have created an agent with some structured tools.

```typescript
const tools = [
    new BingNewsSearchTool(import.meta.env.VITE_BING_API_KEY),
];

const chatModel = new ChatOpenAI({
  temperature: 0,
  openAIApiKey: import.meta.env.VITE_OPENAI_API_KEY,
});

const agent = await initializeAgentExecutorWithOptions(tools, chatModel, {
    agentType: "structured-chat-zero-shot-react-description",
    returnIntermediateSteps: true,
    verbose: true,
});
```

Here is the implementation for `BingNewsSearchTool`.
```typescript
import { StructuredTool } from "langchain/tools";
import { summarizeOrGeneratePrompt } from "./helper";
import { z } from "zod";

class BingNewsSearchTool extends StructuredTool {
  name = "bing-news-search";
  description = `Useful to search for recent news about any topic. Input should be the keywords for the news search.`;
  schema = z.object({
    query: z.string(),
  });

  apiKey: string;

  constructor(apiKey: string) {
    super();

    this.apiKey = apiKey;
  }

  async _call({ query }: { query: string }) {
    const topic = query.toLowerCase().replace(/\s/g, "-");

    let text;

    try {
      if (window.textCache[topic]) {
        text = window.textCache[topic];
      } else {
        const headers = { "Ocp-Apim-Subscription-Key": this.apiKey };
        const params = {
          q: query,
          textDecorations: "true",
          textFormat: "HTML",
        };
        const searchUrl = new URL(
          "https://api.bing.microsoft.com/v7.0/news/search"
        );
        Object.entries(params).forEach(([key, value]) => {
          searchUrl.searchParams.append(key, value);
        });
        const response = await fetch(searchUrl, { headers });
        if (!response.ok) {
          throw new Error(`HTTP error ${response.status}`);
        }
        const res = await response.json();
        const results = res.value;
        if (results.length === 0) {
          return "No good results found.";
        }
        text = results
          .map((result: { description: string }) => result.description)
          .join("\n");

        window.textCache[topic] = text;
      }
    } catch (e) {
      if (e) {
        return e.toString();
      }
      return "There was a problem connecting to the site";
    }

    return await summarizeOrGeneratePrompt(topic, text);
  }
}

export { BingNewsSearchTool };
```
`summarizeOrGeneratePrompt` function above does similarity search using `VectorStore`, and returns the whole bunch of the documents concatenated by `\n`.

If I run the agent, it does not finish the chain. I confirmed the tool output is correct - couple sentences with similar topic what user gave as input. However, there seems to be something wrong with prompt which is generated by agent. Agent keeps deciding to use the tool, but does not find the answer from the tool output.

**Comment by jacoblee93** [comment]
Will take a look and try to repro, thanks for bringing this up

**Comment by emilsedgh** [comment]
I can frequently this happening as well. It's not doing a great job realizing that the answer it has got from the tools is good enough. Looking at the prompts, it appears that we are not being very explicit when it should consider using a "Final Answer" and get out of the chain.

**Comment by shawnesquivel** [comment]
I'm finding the same issue too.

**Comment by j1philli** [comment]
I mentioned I am seeing similar in #1290

**Comment by miguelmoya97** [comment]
Same issue here

**Comment by jacoblee93** [comment]
Are you able to try with the new functions agent? That also supports StructuredTools

**Comment by miguelmoya97** [comment]
@jacoblee93 
Might be going out of topic, but for my use case the Functions Agent doesn't seem to support the Zapier integration. I get the error message

`[ERROR] InvalidRequestError: 'Gmail: Send Email' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'functions.1.name'`

Thus I try other agents (which seems to be working fine), it just ends up in this endless loop of sending emails
