### ISSUE TITLE
Failing to load S3 file using s3Loader.

### ISSUE THREAD

**Issue by shubhamrejolut** [hwchase17/langchainjs#1390]
Facing this error while downloading file through S3Loader.
![image](https://github.com/hwchase17/langchainjs/assets/107535300/8fb349f8-cfa7-4b8d-9cc5-77901928ebbc)
Below is my code.
>  const loader = new S3Loader({
        bucket: process.env.AWS_S3_BUCKET,
        key: 'shubham/test_training_data.txt',
        s3Config: {
          region: process.env.REGION,
          accessKeyId: process.env.AWS_S3_ACCESS_KEY,
          secretAccessKey: process.env.AWS_S3_KEY_SECRET,
        },
        unstructuredAPIURL: 'http://127.0.0.1:8000/general/v0/general',
      });
      // const loader = new PDFLoader('/home/shubham/Downloads/policy.pdf', {
      //   splitPages: true,
      // });
      console.log(loader);
      const docs = await loader.load();

**Comment by shubhamrejolut** [comment]
Solved it, needed to do aws configure. 
I am still figuring it out why would it fetch env variables from default location instead of those provided in the s3config.

**Comment by shubhamrejolut** [comment]
Solved

**Comment by QasimRRizvi** [comment]
Because s3Loader interface is changed, issue solved in this PR:
https://github.com/hwchase17/langchainjs/pull/1557
