### ISSUE TITLE
Feature request: Upstash Redis-based cache

### ISSUE THREAD

**Issue by ap-1** [hwchase17/langchainjs#1428]
LangChain already offers [Upstash Redis-Backed Chat Memory](https://js.langchain.com/docs/modules/memory/examples/upstash_redis), under `langchain/stores/message/upstash_redis`, in addition to [Redis-Backed Chat Memory](https://js.langchain.com/docs/modules/memory/examples/redis) under `langchain/stores/message/redis`. 

Would it be possible to create an Upstash Redis-based cache (presumably under `langchain/cache/upstash_redis`) to supplement the existing [Redis-based cache](https://js.langchain.com/docs/modules/models/llms/additional_functionality#caching-with-redis) under `langchain/cache/redis`?

**Comment by jacoblee93** [comment]
This would be awesome!
