### ISSUE TITLE
queryEmbeddings and queryTexts cannot both be undefined on Chromadb 1.5.1

### ISSUE THREAD

**Issue by ladrians** [hwchase17/langchainjs#1481]
Updated to version `0.87` and got the Chromadb `1.5.1` update from `1.5.0`.
[This commit](https://github.com/chroma-core/chroma/commit/565f2e4fb84cf92f5cf57df001edd90e3389ded8) changing to use `camelCase` broke compatibility. When using the query I get the error

```
queryEmbeddings and queryTexts cannot both be undefined
```

**Comment by ravi-dhiwise** [comment]
I'm also facing this issue.

**Comment by e-roy** [comment]
I can confirm.

I'm using next js with langchain v0.0.89 and chromadb v1.5.0 with no error

here is the code

`// api/test-chroma-response.ts

import { NextApiRequest, NextApiResponse } from "next";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";
import { Chroma } from "langchain/vectorstores/chroma";
import { RetrievalQAChain } from "langchain/chains";
import { OpenAI } from "langchain/llms/openai";

export const config = {
  runtime: "nodejs",
};

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const vectorStore = await Chroma.fromExistingCollection(
    new OpenAIEmbeddings(),
    { collectionName: "a-test-collection" }
  );
  const model = new OpenAI({
    modelName: "gpt-3.5-turbo",
    temperature: 0.2,
  });

  const chain = RetrievalQAChain.fromLLM(model, vectorStore.asRetriever());
  const response = await chain.call({
    query: "What did the president say about Justice Breyer?",
  });
  console.log({ response });

  try {
  } catch (e) {
    console.log(e);
  }

  res.status(200).json({ response });
}
`

when I update to chroma v1.5.1, I get this error
`- error Error: queryEmbeddings and queryTexts cannot both be undefined
    at Collection.query (...\chatbot-pinecone-test\node_modules\chromadb\dist\main\Collection.js:320:19)`

is this a chromadb issue??

**Comment by Russell-Pollari** [comment]
This was a breaking change that was meant to ship with 1.5.0
PR: https://github.com/chroma-core/chroma/pull/587

Due to a publishing issue, it did not ship until 1.5.1 (see https://github.com/chroma-core/chroma/issues/635

**Comment by Russell-Pollari** [comment]
Will try and push a fix for chroma ^1.5.1

**Comment by jacoblee93** [comment]
Thank you!

**Comment by zsh2401** [comment]
> Will try and push a fix for chroma ^1.5.1

Wonderful!

**Comment by jacoblee93** [comment]
Fix is live in 0.0.90!
