### ISSUE TITLE
Azure & embeddings : The embeddings operation does not work with the specified model

### ISSUE THREAD

**Issue by givebest** [hwchase17/langchainjs#1510]
I use Azure OpenAI API like this in my project:

```js
import { OpenAIEmbeddings } from "langchain/embeddings/openai";

const embeddings = new OpenAIEmbeddings({
   azureOpenAIApiKey: "YOUR-API-KEY", // In Node.js defaults to process.env.AZURE_OPENAI_API_KEY
   azureOpenAIApiInstanceName: "YOUR-INSTANCE-NAME", // In Node.js defaults to process.env.AZURE_OPENAI_API_INSTANCE_NAME
   azureOpenAIApiDeploymentName: "YOUR-DEPLOYMENT-NAME", // In Node.js defaults to process.env.AZURE_OPENAI_API_DEPLOYMENT_NAME
   azureOpenAIApiVersion: "YOUR-API-VERSION", // In Node.js defaults to process.env.AZURE_OPENAI_API_VERSION
});
```

This error will appear: `The embeddings operation does not work with the specified model, gpt-35-turbo. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go .microsoft.com/fwlink/?linkid=2197993`.

**Comment by jacoblee93** [comment]
Can you global search for `gpt-35-turbo` in your code? There should be a dot between `3.5` and I don't see it anywhere in the OSS package.

**Comment by givebest** [comment]
Thank you for your reply, it should be because of the model set up by the Azure API.
