### ISSUE TITLE
Custom openai basePath properties are not supported

### ISSUE THREAD

**Issue by jokingzhang** [hwchase17/langchainjs#1511]
I want to customize the openai basePath property, but the current SDK does not provide the entrance, please support it, thank you

![image](https://github.com/hwchase17/langchainjs/assets/10766546/ca39cfea-57c8-432a-87d3-61c3c5d2bdd3)

![image](https://github.com/hwchase17/langchainjs/assets/10766546/c804a244-f6c5-48e6-9974-ae66315d0276)

![image](https://github.com/hwchase17/langchainjs/assets/10766546/901bdf58-a371-49e3-833f-4c75571c81c3)

**Comment by jacoblee93** [comment]
You should be able to pass it in as a third parameter (`configuration` in your above screenshot):

```js
const model = new OpenAI({}, {
  basePath: "your-base-path"
});
```
