### ISSUE TITLE
How to retain memory while chatting over documents?

### ISSUE THREAD

**Issue by unseen1980** [hwchase17/langchainjs#1513]
Hello,

Would you please let me know if there is a way to have memory while using documents in the chat?
In my code I am using the ```loadQAStuffChain``` with the ```input_documents``` property when calling the chain. Works great, no issues, however, I can't seem to find a way to have memory.  When using ```ConversationChain``` instead of ```loadQAStuffChain``` I can have memory eg BufferMemory, but I can't pass documents. Is there a way to have both?

Regards

**Comment by jacoblee93** [comment]
The `ConversationalRetrievalQAChain` may be helpful - please reopen if not:

https://js.langchain.com/docs/modules/chains/index_related_chains/conversational_retrieval
