### ISSUE TITLE
Support for Vertex AI Matching Engine as a Vector Store

### ISSUE THREAD

**Issue by afirstenberg** [hwchase17/langchainjs#1532]
See also (from the Python version):
- hwchase17/langchain#2892
- hwchase17/langchain#2971
- hwchase17/langchain#3104

Documentation:
- https://cloud.google.com/vertex-ai/docs/matching-engine/overview

I'll be working on this.

**Comment by nfcampos** [comment]
Thank you

**Comment by afirstenberg** [comment]
Only a little - was going to do more this weekend, but if you'd like to get started, feel free.
(Particularly if you understand the Matching Engine. I've been trying to wrap my head around it, and I feel like I have only the barest grasp of it.)
Would love if you shared your branch so I can follow along or work with you.

My main thoughts:
- Use the Docstore to store the document (so I needed to get that in the codebase first)
- Assume streaming updates
- Use the metadata to generate "restricts" values?

Your thoughts?

**Comment by afirstenberg** [comment]
@jaythegeek 
Only a little - was going to do more this weekend, but if you'd like to get started, feel free.
(Particularly if you understand the Matching Engine. I've been trying to wrap my head around it, and I feel like I have only the barest grasp of it.)
Would love if you shared your branch so I can follow along or work with you.

My main thoughts:

- Use the Docstore to store the document (so I needed to get that in the codebase first, which it now is)
- Assume streaming updates
- Use the metadata to generate "restricts" values?

Your thoughts?

**Comment by afirstenberg** [comment]
@jaythegeek - Have you done anything on this? It's rising closer to the top of my list and want to help out if you have things in progress.

**Comment by davidoort** [comment]
What's the status of this @afirstenberg ?

**Comment by afirstenberg** [comment]
I have the basics working - add a vector and query for a nearby vector.
But the documentation for the REST interface is... non-existent. And matching with a filter doesn't work at all.

I'm in email exchanges with Google DevRel, but haven't gotten clear answers yet.

So I can add what I have (which doesn't support restrictions or matching filters) which will change once I get clear documentation about the filtering.

Thoughts?

**Comment by afirstenberg** [comment]
@davidoort 

I have the basics working - add a vector and query for a nearby vector.
But the documentation for the REST interface is... non-existent. And matching with a filter doesn't work at all.

I'm in email exchanges with Google DevRel, but haven't gotten clear answers yet.

So I can add what I have (which doesn't support restrictions or matching filters) which will change once I get clear documentation about the filtering.

Thoughts?

**Comment by davidoort** [comment]
Sounds good, I personally have not dug into this so I can't help out at the moment unfortunately. That said, are these features working in the Python version of Langchain? It should be hitting the same API right?

Thanks again 🙏

**Comment by afirstenberg** [comment]
They *are* working in the Python version. Or at least so I've been told.

And the Python library may be hitting the same REST API... but nobody seems to be able to say what that API is.
And, unsurprisingly, the answer to just about everything has been "well, we have a Python library. Here is an example Colab notebook".

But I'm getting closer!

**Comment by afirstenberg** [comment]
Ok, let's see how this goes. @davidoort - See PR #2340 
If you have questions about how I've done this or the prerequisites, let me know.

**Comment by davidoort** [comment]
Awesome work @afirstenberg !! What's required to get this merged? And what's the easiest way I can test this?

**Comment by afirstenberg** [comment]
Thank you, @davidoort!
I'm sure @jacoblee93 will get to it as he does reviews and will raise any issues with me.

The big first question - do you already have a Matching Engine instance running? That's probably more difficult than anything else right now.
If so, then you should be able to clone my clone of the repository and build my googlevertexai-matchingengine branch. The documentation should be available as part of my pull request if you want to read that and comment on it.

**Comment by afirstenberg** [comment]
This has *finally* been released - thank you @jacoblee93 for your help with this!

@davidoort - Please reach out to me on Twitter/X or LinkedIn to discuss Matching Engine further. I'd like to take your thoughts back to the team, and I hope that we see some improvements in Cloud Next. (Or I'll be working on a companion package.)

**Comment by davidoort** [comment]
Sent you a message here: https://www.linkedin.com/in/allen-s-firstenberg-950130/ 
With Cloud Next in a few days this is going to be an exciting space, let's see what they announce and go from there! I'd definitely would be interested in a package that makes it easy to manage indexes + doc stores, etc. I'm currently setting up some simple scripts to get started
