### ISSUE TITLE
Remove interface dependency for milvus-sdk-node

### ISSUE THREAD

**Issue by shanghaikid** [hwchase17/langchainjs#1551]
We should remove the dependency from @zilliz/milvus2-sdk-node/dist/milvus/const/Milvus.js.  
In newer version, it would be removed. 

You can just import these from the package

From: 
```javascript
import {
  MilvusClient,
  DataType,
  DataTypeMap,
} from "@zilliz/milvus2-sdk-node/dist/milvus/const/Milvus.js";
```

To:
```javascript
import {
  MilvusClient,
  DataType,
  DataTypeMap,
} from "@zilliz/milvus2-sdk-node";
```

**Comment by karamqubsi** [comment]
I was testing milvus with langchain js ( with nextjs ) yesterday, I noticed that this is causing Error [ERR_MODULE_NOT_FOUND]. 

thanks for pointing this out.

**Comment by shanghaikid** [comment]
> I was testing milvus with langchain js ( with nextjs ) yesterday, I noticed that this is causing Error [ERR_MODULE_NOT_FOUND].
> 
> thanks for pointing this out.

If you are using nextjs. If you meet this issue,  you may need to copy protofiles, the solution is in the issue. 

https://github.com/milvus-io/milvus-sdk-node/issues/170
