### ISSUE TITLE
SRTLoader does not properly import srt-parse-2 library

### ISSUE THREAD

**Issue by talk2MeGooseman** [hwchase17/langchainjs#1554]
When attempting to load an SRT file, I receive `TypeError: SRTParser2 is not a constructor`.

Node: v18.15.0

Example code:
```js
  const loader = new SRTLoader(
    __dirname + '/../../../document_loaders/VS-Code-Profiles.srt'
  )

  const docs = await loader.load()
```

Expect to load the file and not receive error.

Actual error:
```bash
api | TypeError: SRTParser2 is not a constructor
api |     at SRTLoader.parse (<omitted>/node_modules/langchain/dist/document_loaders/fs/srt.cjs:12:24)
api |     at async SRTLoader.load (/Users/erikguzman/code/chatgpt-playground/node_modules/langchain/dist/document_loaders/fs/text.cjs:32:24)
api |     at handler (<omitted>/api/src/functions/langChainCaptions/langChainCaptions.ts:35:16)
api |     at async requestHandler (<omitted>/node_modules/@redwoodjs/api-server/dist/requestHandlers/awsLambdaFastify.js:72:30)
```

The culprit appears to be the `default.default` to import the package.

https://github.com/hwchase17/langchainjs/blob/e9c9ae9702f06b1b186d8f1244f5e1b04bd79909/langchain/src/document_loaders/fs/srt.ts#L26

**Comment by talk2MeGooseman** [comment]
Recent updates appear to have fixed the issue

**Comment by Jakisundays** [comment]
i have the same problem.

**Comment by anirudhmaddy** [comment]
I have the same problem, how did you solve it?

**Comment by artell0** [comment]
Hi,

I have the same issue. The subtitles loader seems to be the problem. Is there a way to fix this? I don't think the issue is elsewhere in my chain. I have a subtitles file loader, with a token text splitter. The subtitles go into in-memory vector store, which is attached to OpenAI embedding. vector store leads to conversational retrieval QA chain, connected to ChatOpenAI.

**Comment by sarfudheen** [comment]
I'm also facing the same issue, 
```
api | TypeError: SRTParser2 is not a constructor
api |     at SRTLoader.parse (<omitted>/node_modules/langchain/dist/document_loaders/fs/srt.cjs:12:24)
```
