### ISSUE TITLE
Azure OpenAI Service Embedding model save multi documents error

### ISSUE THREAD

**Issue by guangzhengli** [hwchase17/langchainjs#1571]
Example Code: 
```ts   
const azureOpenAIEmbeddings = new OpenAIEmbeddings({
    azureOpenAIApiKey: AZURE_OPENAI_API_KEY,
    azureOpenAIApiInstanceName: AZURE_OPENAI_API_INSTANCE_NAME,
    azureOpenAIApiDeploymentName: AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME,
    azureOpenAIApiVersion: AZURE_OPENAI_API_VERSION,
});

export const getEmbeddings = async () => {
        return azureOpenAIEmbeddings;
}

 const supabaseVectorStore = new SupabaseVectorStore(await getEmbeddings(),
        {client, tableName: "documents", queryName: "match_documents"});
    await supabaseVectorStore.addDocuments(documents);
```

When I put one document in supabaseVectorStore.addDocuments(documents), embedding is successful. 

However, when the documents array is greater than one, Azure OpenAI service will return a 400 error with the error message.
Response Message:
```
Too many inputs. The max number of inputs is 1. We hope to increase the number of inputs per request soon.
```

This error seems to be caused by Azure OpenAI service not supporting multiple inputs. Is there any way to avoid this error? Or is there a plan to fix it?

**Comment by afirstenberg** [comment]
Same issue as #1506?

**Comment by duyhnguyen216** [comment]
my current work around is adding the document one by one. So something like
```
let vectorStore = await MemoryVectorStore.fromTexts([output[0].pageContent], output[0].metadata, embeddings);
                    for (let i = 1; i < output.length; i++) {
                        vectorStore.addDocuments([output[i]]);
                    }
```

**Comment by guangzhengli** [comment]
@afirstenberg @duyhnguyen216 
The same issue was caused by Azure OpenAI Service, I think adding documents one by one is a solution, but should we do this at the framework level?

**Comment by duyhnguyen216** [comment]
> @afirstenberg @duyhnguyen216 The same issue was caused by Azure OpenAI Service, I think adding documents one by one is a solution, but should we do this at the framework level?

We can do it. But I'm not sure if anyone should open a PR to do such thing because it feels like a bandaid fix to me. Also, what happen when Azure decide to support multiple document? We then need someone to continuously track this and make a change?

**Comment by guangzhengli** [comment]
I am not sure if it is necessary to open this PR, as it is due to Azure OpenAI Service rather than Langchain. However, most developers using Azure OpenAI Service will encounter this issue.

**Comment by duyhnguyen216** [comment]
> I am not sure if it is necessary to open this PR, as it is due to Azure OpenAI Service rather than Langchain. However, most developers using Azure OpenAI Service will encounter this issue.

Yeah. I have already contacted MS regarding this. Maybe if enough people complain about it, they will support this feature soon. Also depends on the size of our company as well.

**Comment by afirstenberg** [comment]
There are certainly other cases where the platform has a limit and LangChain will work around that limit (see, for example, #1590)
