### ISSUE TITLE
Redis Sentinel Support

### ISSUE THREAD

**Issue by chasemcdo** [hwchase17/langchainjs#1710]
The current implementation of LangChainJS' [RedisChatMessageHistory](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/stores/message/redis.ts) uses the base [Redis createClient](https://github.com/redis/node-redis) which does not have native Redis Sentinel support as far as I can tell.

There is also the [ioredis package](https://github.com/redis/ioredis) which supports both Sentinel and none-Sentinel deployments. Is there a particular reason we opted for the the base client rather than ioredis or is this a change we are open to making?

**Comment by jacoblee93** [comment]
Apologies for the delay - I'd be open to it if you're willing to tackle it! We could also make a separate RedisSentinel cache too with an optional peer dep.

**Comment by chasemcdo** [comment]
I can take this on. Does we have a preference on whether or not it is a separate cache or replaces the existing?
I could see the argument for a separate one being compatibility, but this then introduces a bit of redundancy with supporting multiple Redis libraries.

I've got most of the implementation done just curious what we'd like to be prioritizing: compatibility or reduced redundancy

**Comment by chasemcdo** [comment]
Sounds good and thanks for the quick reply! As for naming was thinking of going with something like `IORedis` since it still supports more than Sentinel.
I've imported it as a new cache which can be imported almost exactly the same as the existing for future compatibility if the current is deprecated.
ie imported through: `import { RedisChatMessageHistory } from "langchain/stores/message/ioredis";`

PR is up in #1920
