### ISSUE TITLE
ZeroShotAgentOutputParser crashes when "Action Input:" is absent on output string.

### ISSUE THREAD

**Issue by gabrielmontagne** [hwchase17/langchainjs#1738]
I'm not familiar enough with the library to know if this is a valid case or just a symptom of some other problem (I'm also struggling with #1290 when this happens), but the library does crash when the "Action Input:" is missing from the string.  Please take a look at the screenshots provided.

* ![image](https://github.com/hwchase17/langchainjs/assets/95913/71b0e6c7-6db2-400e-af96-9bf21906d2a6)
* ![image](https://github.com/hwchase17/langchainjs/assets/95913/90809bde-d38b-46c6-9a1a-0aa3e89e8b8a)

Perhaps irrelevant context: 
I'm following the [getting started (the agents part)](https://js.langchain.com/docs/getting-started/guide-llm#agents-dynamically-run-chains-based-on-user-input), but I switched to `GoogleCustomSearch` because SerpAPI [doesn't like that I'm doing my tests from a browser client directly](https://forum.serpapi.com/feature-requests/p/add-http-cors-headers).

**Comment by m-yasir** [comment]
Duplicate of #1673

I believe it's been fixed recently with #1674

**Comment by gabrielmontagne** [comment]
Thanks. It is, yes, a duplicate.  I'll close this one.
