### ISSUE TITLE
Question: Vercel AI library streaming not closing due to callbacks

### ISSUE THREAD

**Issue by aranlucas** [hwchase17/langchainjs#1740]
context: https://github.com/vercel-labs/ai/issues/97#issuecomment-1602987221

Currently Vercel's AI library is not closing the stream due to different chains being used with the library. For example, `ConversationalRetrievalQAChain` does not call `handleChainEnd` (Tried with the example code posted in issue.)

My proposed fix was to add `handleLLMEnd` to list of handlers return https://github.com/vercel-labs/ai/pull/201.

If there is a `handleLLMEnd`  and a `handleChainEnd`, could there be a problem with the chain ending earlier than it should? Additionally, could this problem also exist with `handleAgentEnd` in the future?
I tried looking through code and docs, but could not find the answer. 

Thanks in advance

**Comment by aranlucas** [comment]
This could also be a bug report where `ConversationalRetrievalQAChain` is not calling `handleChainEnd`, but I'm not sure if that's expected behavior.

**Comment by aranlucas** [comment]
Another follow up: https://js.langchain.com/docs/production/callbacks/#multiple-handlers

What would it make sense for a library to vend out these handlers? How many unique handlers do you think they should to handle the agent, chain, llm use cases?

**Comment by max-sym** [comment]
It still happens for us too, but with `initializeAgentExecutorWithOptions`:

```ts
const { stream, handlers } = LangChainStream()

const model = new ChatOpenAI({
    openAIApiKey: process.env.OPENAI_API_KEY,
    streaming: true,
    callbacks: [
      {
        handleChainEnd: async (output) => {
          console.log("CLOSED!") // 👈👈👈👈 never gets called
        }
      },
      handlers
    ],
    modelName,
    temperature: 0
  })


  const executor = await initializeAgentExecutorWithOptions(tools, model, {
    agentType: "openai-functions",
    verbose: process.env.NODE_ENV === "development",
    agentArgs: { prefix: prompt },
    memory
  })

  executor.stream({ input: lastMessageContent })
```

**Comment by max-sym** [comment]
Ok, after looking into it closely I've found the solution.
Instead of passing the callbacks to the LLM constructor, pass them to the agent like so:
```ts
const { stream, handlers } = LangChainStream()

const model = new ChatOpenAI({
    openAIApiKey: process.env.OPENAI_API_KEY,
    streaming: true,
    // callbacks: ...    // 👈👈👈👈 REMOVE IT FROM HERE
    modelName,
    temperature: 0
  })


  const executor = await initializeAgentExecutorWithOptions(tools, model, {
    agentType: "openai-functions",
    verbose: process.env.NODE_ENV === "development",
    agentArgs: { prefix: prompt },
    callbacks: [  // 👈👈👈👈 PUT IT HERE INSTEAD
      {
        handleChainEnd: async (output) => {
          console.log("CLOSED!") // 👈👈👈👈 NOW IT GETS CALLED!
        }
      },
      handlers
    ],
    memory
  })

  executor.stream({ input: lastMessageContent })
```
