### ISSUE TITLE
issue when import { ConversationChain } from "langchain/chains"

### ISSUE THREAD

**Issue by phattarin-kitbumrung** [hwchase17/langchainjs#1769]
node_modules/langchain/dist/sql_db.d.ts:1:67 - error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

1 import type { DataSource as DataSourceT, DataSourceOptions } from "typeorm";
                                                                    ~~~~~~~~~

node_modules/langchain/dist/util/sql_utils.d.ts:1:52 - error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

1 import type { DataSource, DataSourceOptions } from "typeorm";
                                                     ~~~~~~~~~

Found 2 errors in 2 files.

Errors  Files
     1  node_modules/langchain/dist/sql_db.d.ts:1
     1  node_modules/langchain/dist/util/sql_utils.d.ts:1

**Comment by jacoblee93** [comment]
This should be fixed in 0.0.102 - thank you for flagging!
