### ISSUE TITLE
SitemapLoader hangs on too many redirects, but SitemapLoader can handle it

### ISSUE THREAD

**Issue by Morriz** [hwchase17/langchainjs#1782]
I think the `SitemapLoader` should be as robust with default options as the `UnstructuredURLLoader`, which has an option `continue_on_failure` set to true.

**Comment by devstein** [comment]
@Morriz Did you mean to post this in https://github.com/hwchase17/langchain/issues ?

**Comment by Morriz** [comment]
Indeed! Tnx.
