### ISSUE TITLE
SupabaseFilterRPCCall does not work, Error: PGRST202 Could not find the function public.match_documents(query_embedding)

### ISSUE THREAD

**Issue by JimmyLv** [hwchase17/langchainjs#1795]
Related doc: https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/supabase

## Correct

```ts

const vectorStore = await SupabaseVectorStore.fromExistingIndex(new OpenAIEmbeddings(), {
    client: supabaseClient,
    // https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/supabase
    filter: { source: videoUrl },
  })
```

## Incorrect

After migrating to use SupabaseFilterRPCCall, failed:

```ts
const funcFilterByCollection: SupabaseFilterRPCCall = (rpc) =>
    // rpc.filter('metadata->>source', 'in', `(${contentUrls.join(',')})`)
    rpc.filter('metadata->>source', 'eq', videoUrl)

  const embeddings = new OpenAIEmbeddings()
  const vectorStore = new SupabaseVectorStore(embeddings, {
    client: supabaseClient,
    tableName: 'documents',
    filter: funcFilterByCollection
  })

```

## Error message

```shell
- error node_modules/langchain/dist/vectorstores/supabase.js (79:18) @ SupabaseVectorStore.similaritySearchVectorWithScore
- error Error searching for documents: PGRST202 Could not find the function public.match_documents(query_embedding) in the schema cache Searched for the function public.match_documents with parameter query_embedding or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache.
```

Error searching for documents: PGRST202 Could not find the function public.match_documents(query_embedding) in the schema cache Searched for the function public.match_documents with parameter query_embedding or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache.

**Comment by JimmyLv** [comment]
I've tried adding `queryName` but it still doesn't work

```ts
const embeddings = new OpenAIEmbeddings()
const vectorStore = new SupabaseVectorStore(embeddings, {
  client: supabaseClient,
  tableName: 'documents',
  queryName: 'match_documents', // Add this line
  filter: funcFilterByCollection
})
```

**Comment by siddarthvader** [comment]
@JimmyLv I think we have to modify the DDL when you are using filter, i have the exact same problem when using self query retriever with conversational QA chain.

I think what we need to do it add a supabase function just for metadata filtering, being said that, did you find the solution?

**Comment by JimmyLv** [comment]
I haven't found a solution yet, 😔

Maybe we could create a new `filter_match_documents` function and write the filter criteria directly into it? 
Of course, another option is to filter the documents by Supabase firstly, and then give them to LangChain.

```ts
const { data: searches, error } = await this.client.rpc(
      this.similarityQueryName,
      matchDocumentsParams
    );

    if (error) {
      throw new Error(
        `Error searching for documents: ${error.code} ${error.message} ${error.details}`
      );
    }

  const docs = (searches as SearchResponseRow[]).map((resp) => [
      new Document({
        metadata: resp.metadata,
        pageContent: resp.content,
      }),
      resp.similarity,
      resp.id,
    ]);

const res = await chain.call({
    input_documents: docs,
  });
```

No magic, ┓( ´∀` )┏ 
https://github.com/hwchase17/langchainjs/blob/d43ce8032a0c83c94422b2190b88c53b744433ca/langchain/src/retrievers/supabase.ts#L115

**Comment by siddarthvader** [comment]
@JimmyLv it worked for me, but I'm using JS/TS langchain module. But it wasn't working initially. Try to change your version. It should work.

**Comment by siddarthvader** [comment]
@JimmyLv with same match_document function, as provided in the documentation.

**Comment by JimmyLv** [comment]
Do you mean using the latest version of LangchainJS? `"langchain": "^0.0.101"` Let me try.

**Comment by JimmyLv** [comment]
It still doesn't work, I'm pretty sure I definitely have this match_documents function and I'm able to get it to work through the REST API.

![Supabase-Google Chrome](https://github.com/hwchase17/langchainjs/assets/4997466/04591aac-75bc-4928-887f-7a843af94b98)

![Postman-Postman](https://github.com/hwchase17/langchainjs/assets/4997466/14a1a9a0-f64f-4fa3-ad58-4c0f1ccac7fa)

**Comment by JimmyLv** [comment]
@hwchase17 @supabase any idea? 😁

**Comment by Lionardo** [comment]
I also encountered this issue. Did you find a solution?

**Comment by JimmyLv** [comment]
waiting for @jacoblee93 :D

**Comment by jacoblee93** [comment]
Sorry! Let me dig in a bit more today.

**Comment by jacoblee93** [comment]
The Postgres function changed a bit to support this, so if you were using it before you may have to update it.

You could try making a new function from scratch with the current version in the docs (e.g. `match_documents_new`) and initializing your vector store to hit it:

```typescript
const vectorStore = new SupabaseVectorStore(embeddings, {
  client: supabaseClient,
  tableName: 'documents',
  queryName: 'match_documents_new', // Add this line
  filter: funcFilterByCollection
})
```

**Comment by tinaroh** [comment]
Thank you, I had a similar problem and fixed it by dropping and recreating the function per the [latest docs](https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/supabase/)

```
-- Drop old function
drop function if exists match_documents (vector(1536), int);

-- Create a function to search for documents
create function match_documents (
  query_embedding vector(1536),
  match_count int DEFAULT null,
  filter jsonb DEFAULT '{}'
) returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
#variable_conflict use_column
begin
  return query
  select
    id,
    content,
    metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$$;
```

**Comment by linxz-coder** [comment]
> 

Thank you, finally found the answer, that works!

**Comment by jacoblee93** [comment]
Closing for now, can reopen if something like the above doesn't work.

**Comment by joaojbs199** [comment]
A solução do @tinaroh  funcionou pra mim!
