### ISSUE TITLE
Keep the chat history context

### ISSUE THREAD

**Issue by joaopcm** [hwchase17/langchainjs#1800]
Hey everyone, I made a really cool change to our chain! I'll present the problem and then explain how I was able to fix it.

With the standard Langchain chain connected to a vector store (for context access) and with memory storage, we can have a super powerful chatbot. The problem is that, with the standard Langchain chain, the chat is only able to reason from the results of the vector store similarity search. This introduces us to the following problem:

If I send a message to the AI introducing my friend Bob and say he is 28 years old, the bot will reason from the input message, maybe consider some vector store context (if there is any) and give us a response.

Then, if I ask the bot how old Bob is, it will be unable to answer "28 years old," because the bot will try to search for Bob in the vector store, but Bob was only mentioned in the message history.

In the current memory implementation, we use only to reformulate the user's final questions into a clearer question. Nothing else. That's why, no matter how we introduce Bob to the AI in a message, it will be unable to give any information about Bob in the next one, even though we have the memory implementation.

To fix this, I overwrote the standard prompt template of one of the Langchain chain steps not only to rewrite the user's final question in a clearer way, but also to include any messages from the history that have some similarity to the question, if any.

Here are some tests I did to identify and explain the problem and also the tests I did after overwriting the standard prompt template of this Langchain chain step.

### UI
![image](https://github.com/hwchase17/langchainjs/assets/58827242/bc0c7766-b746-464f-af1e-8ec2e9890f88)

### Underlying prompt built by Langchain
![image](https://github.com/hwchase17/langchainjs/assets/58827242/e2f7ca29-00df-4a83-865a-f701546ce4bc)

As you can see, LangChain is recreating the question, turning it into a standalone one.

### Example: Without prior relevant chat history context
![image](https://github.com/hwchase17/langchainjs/assets/58827242/11a1a12d-1f0b-46dc-9e15-44417aaba38f)

#### UI
![image](https://github.com/hwchase17/langchainjs/assets/58827242/b9c031d6-ec47-412c-8182-21d58f7941c9)

#### Underlying prompt build by Langchain
![image](https://github.com/hwchase17/langchainjs/assets/58827242/22828f5a-3ca3-4d87-b855-216f96f7abd6)

## Final result
![CleanShot 2023-06-28 at 19 08 23](https://github.com/hwchase17/langchainjs/assets/58827242/2ad9f863-75b0-4a24-899f-31debbacef25)

**Comment by jklein33** [comment]
@jacoblee93 This is extremely helpful and solves 90% of the problem for my system. Upon opening a new chat (99% of the time it is only the first prompt of the conversation), it seems that this creates an opportunity for hallucinations. I have found that if my prompt is poorly articulated or very short, it will reiterate the question back to me, respond in a foreign language or spit out non-sense. In large part, this is mitigated by opening the conversation with a very descriptive prompt and then everything runs smoothly, although the occasional hallucination still persists. Obviously, I want this to be fool-proof so simply instructing users not to prompt it poorly is not enough. Have you run into a similar issue? Do you have any idea how I can fix this or what might be causing it?

**Comment by deepak-hl** [comment]
@joaopcm Do I need to change above context in CONDENSE_QUESTION_PROMPT template ?

**Comment by joaopcm** [comment]
> @joaopcm Do I need to change above context in CONDENSE_QUESTION_PROMPT template ?

Hey, @deepak-hl! What do you mean by `CONDENSE_QUESTION_PROMPT`?
