### ISSUE TITLE
Can the OpenAI model’s max token length error be resolved?

### ISSUE THREAD

**Issue by odb23** [hwchase17/langchainjs#1813]
I’m currently working on an AI project, but I’m relatively new to the field and need some guidance. My goal is to utilize AI models, specifically OpenAI models, to generate HTML templates based on some data I have.

I explored using Langchain and a vector database. I inserted my data into the vector database as separate documents. Then, to generate templates based on a specific query, I performed a similarity search in the vector database. The retrieved documents were used as context for an OpenAI model to generate templates accordingly. However, I encountered a max token error when passing lengthy code as context to the AI model.

The context passed to the AI model contains extensive code, and I’m unsure how to handle this error. Is there a way to increase the token length or overcome this limitation?

**Comment by magick93** [comment]
Try using `gpt-3.5-turbo-16k` model

**Comment by Eventidus** [comment]
Either adjust the ChunkSize size, or use reduce or map-reduce type, or alternatively, use gpt-3.5-turbo-16k.

**Comment by odb23** [comment]
Thanks, Using `gpt-3.5-turbo-16k` worked for me.
