### ISSUE TITLE
TypeError: t.replaceAll is not a function using PineconeStore.fromDocuments

### ISSUE THREAD

**Issue by RyanThomasMusser** [hwchase17/langchainjs#1819]
This issue has been referenced in a few [other issue threads](https://github.com/hwchase17/langchainjs/issues/471) which have been closed, but I don't think it's fixed.

The issue is with using replaceAll [here](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/embeddings/openai.ts#L124) and [here](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/embeddings/openai.ts#L147) is not compatible with older versions of node (replaceALl was introduced in node 15). 

There are some popular javascript frameworks (I'm using Meteor) that still use <node 15 version, which causes PineconeStore.fromDocuments to break with the error **TypeError: t.replaceAll is not a function**. I'm going to submit a pull request for this later today. There's no tangible benefit from using replaceAll vs. using replace, and this would unblock a lot of the people who are using slightly older javascript app frameworks.

**Comment by RyanThomasMusser** [comment]
I made a pull request to fix this method, but there are probably more places where unsupported methods are called. 

For those who may find this later and if my fixes haven't gotten merged, I ended up working around this by passing `stripNewLines: false` into `OpenAIEmbeddings` like so:

`const embeddingModel = new OpenAIEmbeddings({ openAIApiKey: openAIApiKey, maxConcurrency: 5, stripNewLines: false });`

This changes the logic route such that `replaceAll` is never called.

**Comment by deemeetree** [comment]
Thank you, @RyanThomasMusser — just ran into this error and also didn't really understand the need to use a method that would be unnecessary.

**Comment by jacoblee93** [comment]
Should be fixed by #1821.

This is a one-off and we don't have plans to extend official support to lower versions of Node, but it was a simple enough fix.
