### ISSUE TITLE
Unresolved dependency 'typeorm' when importing "import { Tool } from "langchain/tools"

### ISSUE THREAD

**Issue by HaiderRazvi** [hwchase17/langchainjs#1828]
Steps to reproduce:
   1. import { Tool } from "langchain/tools";
  2. <compile project>

Error:
../../node_modules/langchain/dist/sql_db.d.ts:1:67 - error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

1 import type { DataSource as DataSourceT, DataSourceOptions } from "typeorm";
                                                                    ~~~~~~~~~

../../node_modules/langchain/dist/util/sql_utils.d.ts:1:52 - error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

1 import type { DataSource, DataSourceOptions } from "typeorm";

Found 2 errors in 2 files.

Errors  Files
     1  ../../node_modules/langchain/dist/sql_db.d.ts:1
     1  ../../node_modules/langchain/dist/util/sql_utils.d.ts:1

**Comment by HaiderRazvi** [comment]
Seems related to this issue [https://github.com/hwchase17/langchainjs/issues/1769]

**Comment by jacoblee93** [comment]
Oh dear, thanks for flagging. Will have a look as soon as I can.

**Comment by jacoblee93** [comment]
This should be good in 0.0.102 - thank you for flagging!

**Comment by HaiderRazvi** [comment]
Awesome, appreciate the quick fix!
