### ISSUE TITLE
Can I use LangChain to index my data and perform searches on the indexed data without relying on OpenAI/ChatGPT? 

### ISSUE THREAD

**Issue by anhhtca** [hwchase17/langchainjs#1844]
Can I use LangChain to index my data and perform searches on the indexed data without relying on OpenAI/ChatGPT ? 

For example, if I'm building a Knowledge Base website where employees within the company can search for internal information, similar to an internal Google search engine.

Thanks in advanced !

**Comment by afirstenberg** [comment]
Your question is pretty vague, but in general - yes.
Most examples are using OpenAI with a model that works with embeddings, but you can use any of the embedding models that are available.

**Comment by jacoblee93** [comment]
There's TensorFlow and HuggingFace embeddings you can run locally:

https://js.langchain.com/docs/modules/models/embeddings/integrations#tensorflowembeddings

And you could try something like setting up your own Azure or SageMaker instance for the LLM (though nothing directly supported for local LLMs yet, waiting on GPT4All support!
