### ISSUE TITLE
Desperate for Azure OpenAI Support 

### ISSUE THREAD

**Issue by transmoga** [hwchase17/langchainjs#1855]
Hi, 

https://github.com/hwchase17/langchainjs/pull/1792 appears to fix the ongoing issues with OpenAI in Azure that many people are experiencing here.

Is there a timeline for this being merged to the main project?

Thank you,

**Comment by clemenspeters** [comment]
Thanks for supporting this feature @transmoga 👍 
Considering the comment in the PR: https://github.com/hwchase17/langchainjs/pull/1792#issuecomment-1617088722 and the frequency of releases recently: https://github.com/hwchase17/langchainjs/releases I assume it will be merged any day now 🤞 😃

**Comment by jacoblee93** [comment]
Yes, will plan to cut a release tomorrow night at the latest!

**Comment by transmoga** [comment]
Thank you both, for your feedback.  It is much appreciated.

**Comment by jacoblee93** [comment]
Live in 0.0.103!
