### ISSUE TITLE
vue2.6 Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).

### ISSUE THREAD

**Issue by kill136** [hwchase17/langchainjs#1863]
environment：   vue.js project ，version ：vue 2.6

 ERROR  Failed to compile with 2 errors                                                                                    13:07:04

 error  in node:fs/promises

Syntax Error: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

 error  in node:path

Syntax Error: Reading from "node:path" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.

ERROR in node:fs/promises                                                                                                          
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at D:\AI\my-project\node_modules\webpack\lib\NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (D:\AI\my-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Object.processResource (D:\AI\my-project\node_modules\webpack\lib\NormalModule.js:835:8)
    at processResource (D:\AI\my-project\node_modules\loader-runner\lib\LoaderRunner.js:220:11)
    at iteratePitchingLoaders (D:\AI\my-project\node_modules\loader-runner\lib\LoaderRunner.js:171:10)
    at runLoaders (D:\AI\my-project\node_modules\loader-runner\lib\LoaderRunner.js:398:2)
    at NormalModule._doBuild (D:\AI\my-project\node_modules\webpack\lib\NormalModule.js:825:3)
    at NormalModule.build (D:\AI\my-project\node_modules\webpack\lib\NormalModule.js:969:15)
    at D:\AI\my-project\node_modules\webpack\lib\Compilation.js:1377:12
    at NormalModule.needBuild (D:\AI\my-project\node_modules\webpack\lib\NormalModule.js:1257:32)
    at Compilation._buildModule (D:\AI\my-project\node_modules\webpack\lib\Compilation.js:1358:10)
    at D:\AI\my-project\node_modules\webpack\lib\util\AsyncQueue.js:305:10
    at Hook.eval [as callAsync] (eval at create (D:\AI\my-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncQueue._startProcessing (D:\AI\my-project\node_modules\webpack\lib\util\AsyncQueue.js:295:26)
    at AsyncQueue._ensureProcessing (D:\AI\my-project\node_modules\webpack\lib\util\AsyncQueue.js:282:12)
    at process.processImmediate (node:internal/timers:476:21)
 @ ./node_modules/langchain/dist/document_loaders/fs/unstructured.js 99:16-42
 @ ./node_modules/langchain/document_loaders/fs/unstructured.js 1:0-63 1:0-63
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/App.vue?vue&type=script&lang=js& 2:0-80 14:23-41
 @ ./src/App.vue?vue&type=script&lang=js& 1:0-191 1:207-210 1:212-400 1:212-400
 @ ./src/App.vue 2:0-55 3:0-50 3:0-50 10:2-8
 @ ./src/main.js 2:0-28 5:17-20

ERROR in node:path
Module build failed: UnhandledSchemeError: Reading from "node:path" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
    at D:\AI\my-project\node_modules\webpack\lib\NormalModule.js:838:25
    at Hook.eval [as callAsync] (eval at create (D:\AI\my-project\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\AI\my-project\node_modules\tapable\lib\Hook.js:18:14)
    at Object.processResource (D:\AI\my-project\node_modules\webpack\lib\NormalModule.js:835:8)
 @ ./node_modules/langchain/dist/document_loaders/fs/unstructured.js 102:16-35
 @ ./node_modules/langchain/document_loaders/fs/unstructured.js 1:0-63 1:0-63
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40.use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/App.vue?vue&type=script&lang=js& 2:0-80 14:23-41
 @ ./src/App.vue?vue&type=script&lang=js& 1:0-191 1:207-210 1:212-400 1:212-400
 @ ./src/App.vue 2:0-55 3:0-50 3:0-50 10:2-8
 @ ./src/main.js 2:0-28 5:17-20

**Comment by jacoblee93** [comment]
How are you trying to import LangChain?

**Comment by kill136** [comment]
> How are you trying to import LangChain?

like this ：import { DocxLoader } from "langchain/document_loaders/fs/docx";

**Comment by brerdem** [comment]
I recently coma across this issue and found that the reason was Edge functions of Vercel. You may want to check this first. Another reason could be the Node version. Upgrading it over 16 could fix the error

**Comment by kill136** [comment]
> 
thanks for help ，but i  am not Vercel just using  vue.js .

**Comment by andrewrynhard** [comment]
> I recently coma across this issue and found that the reason was Edge functions of Vercel. You may want to check this first. Another reason could be the Node version. Upgrading it over 16 could fix the error

Did you ever figure out how to get this working with Vercel edge functions? I am running into this myself.

**Comment by jacoblee93** [comment]
Ah. All of the file loaders are unfortunately Node only since they use the `fs` API:

https://js.langchain.com/docs/modules/data_connection/document_loaders/integrations/file_loaders/

**Comment by zkSoju** [comment]
> > I recently coma across this issue and found that the reason was Edge functions of Vercel. You may want to check this first. Another reason could be the Node version. Upgrading it over 16 could fix the error
> 
> Did you ever figure out how to get this working with Vercel edge functions? I am running into this myself.
> 
> ```
> - error node:fs/promises
> Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
> Webpack supports "data:" and "file:" URIs by default.
> You may need an additional plugin to handle "node:" URIs.
> Import trace for requested module:
> node:fs/promises
> ./node_modules/langchain/dist/document_loaders/fs/directory.js
> ./node_modules/langchain/dist/document_loaders/fs/notion.js
> ./node_modules/langchain/document_loaders/fs/notion.js
> ```

Were you able to find another way of handling this?

**Comment by panayao** [comment]
@zkSoju +1. Also trying to use Langchain document loader within a Next.js edge function.

**Comment by try-agaaain** [comment]
I had the same problem.

**Comment by jacoblee93** [comment]
We could try going back to using a conditional import but IIRC it's still a bit unreliable with bundlers
