### ISSUE TITLE
Getting that 'langchain/schema' does not provide an export named for neither  'SystemMessage' nor 'HumanMessage'

### ISSUE THREAD

**Issue by juliomac** [hwchase17/langchainjs#1867]
Using langchain npm @lastest version: langchain@0.0.102

The import statements is:
```import { HumanMessage, SystemMessage } from "langchain/schema";```

Yet, I've got the following error message:
```SyntaxError: The requested module 'langchain/schema' does not provide an export named 'HumanMessage'```

If taken out HumanMessage of the import statement above, got the same for SystemMessage.

```SyntaxError: The requested module 'langchain/schema' does not provide an export named 'SystemMessage'```

Copying from examples in this GitHub... is it a bug?

**Comment by jacoblee93** [comment]
Yes, I believe it should be `HumanChatMessage` and `SystemChatMessage` now. Where are you seeing this?

**Comment by jacoblee93** [comment]
Ah, I'm mistaken. This changed a few days ago in https://github.com/hwchase17/langchainjs/pull/1780.

`HumanChatMessage` and `SystemChatMessage` will still work, but are deprecated. If you update your SDK to the latest version, this should go away.
