### ISSUE TITLE
[FEATURE]: Tools should allow for non-string inputs -- Zod?

### ISSUE THREAD

**Issue by Marviel** [hwchase17/langchainjs#187]
I believe it would be highly possible to use a tool such as [Zod](https://github.com/colinhacks/zod) to specify the expected inputs of a tool. Because, unlike typescript types, Zod schemas are available at runtime -- the agent could also be given the stringified version of the zod schema, which would allow it to know which arguments it should produce. Zod is also a parser, so there could be a neat little iteration loop where the model could try a few times to input a configuration that would pass the schema parser.

I'd be happy to give this a crack if it sounds interesting.

Example: In my recent PR: #186  

[I wanted to be able to specify more than just the prompt for the image.](https://github.com/hwchase17/langchainjs/pull/186/files#diff-8a1aca2365b39be0e68f66ff03c52555aefd64bd9ae645219dba75e9d6f3b486R33)

However, I defaulted to the easier mode because parsing out from a possibly quite wildly structured string could be an issue.

**Comment by idosal** [comment]
Sounds great

**Comment by nfcampos** [comment]
We've started using Zod for the StructuredOutputParser we introduced yesterday, thanks for the suggestion! https://hwchase17.github.io/langchainjs/docs/modules/prompts/output_parsers#structured-output-parser-with-zod-schema 
It sounds like an interesting idea to use these output parsers for the agent tools, thoughts @hwchase17 ?
