### ISSUE TITLE
createOpenAPIChain: Consistently incorrect payloads, incorrect values, some params can't be empty when provided

### ISSUE THREAD

**Issue by danny-avila** [hwchase17/langchainjs#1870]
First off, very thankful for this addition. I've tried many other methods with the JS library and they pale in comparison to python solutions, and this does indeed bring some parity.

While the examples for this new chain all work for me, I wanted to use it with an openAPI spec I personally find useful.

The spec I'm using can be found here: https://scholar-ai.net/openapi.yaml

There are a couple of issues with this payload, and I've highlighted them in comments
```js

  "function": {
    "name": "searchAbstracts",
    "arguments": {
      "params": {
        "keywords": { // "keywords" is the only required param
          "text": "AI VR" 
        },
        "sort": {
          "by": "relevance", // Valid values are cited_by_count or publication_date.
          "reverse": false
        },
        "query": {}, // isn't required, even when spec says otherwise. can be passed an empty value, so no issue
        "peer_reviewed_only": true,
        "start_year": {}, // can't be passed an empty value: must be a 4-digit year
        "end_year": {}, // can't be passed an empty value: must be a 4-digit year
        "offset": {} // can't be passed an empty value: Must be an integer
      }
    }
  }
```
I would like to contribute to this and here are some things I noticed. 

Since some parameters need to be specific and not empty when provided, perhaps it's best to filter them completely if they are empty? 

I made a change to SimpleRequestChain to do exactly this and now some of the API calls it generates are working, will need to test with other specs if this creates issues.

However, there are some issues with the schema not being correct. In  https://github.com/hwchase17/langchainjs/issues/1849#issuecomment-1618810667, @jacoblee93 mentioned that we could add an output checking step that retries if the schema doesn't match, which I believe may help. I will add that it should filter any params if they are invalid, when other params are valid.

#1860 will be helpful if it's an improvement over the OutputFunctionsParser as I understand

Thank you for reading, this is an awesome addition to langchain

---

my test code 
```js
  const chain = await createOpenAPIChain(spec, { verbose: true });
  const result = await chain.run('Can you find and explain some articles about the intersection of AI and VR?');
  console.log('api chain run result', result);
  return result;
  ```

**Comment by jacoblee93** [comment]
Thank you - going to try to address this and other raised issues today!

**Comment by jacoblee93** [comment]
Thought about it a bit more and I think it's best to wait for #1852 to land first as it solidifies our strategy for validating that an object conforms to a given JSON Schema - otherwise we won't know when to retry. Both that PR and this are high priority so hopefully shouldn't be too long.

**Comment by danny-avila** [comment]
> Thought about it a bit more and I think it's best to wait for #1852 to land first as it solidifies our strategy for validating that an object conforms to a given JSON Schema - otherwise we won't know when to retry. Both that PR and this are high priority so hopefully shouldn't be too long.

Sounds good, glad they are priority items! OpenAI Functions really unleashed so many possibilities and can't wait to get more reliable results from their use in this chain and elsewhere.

I put in a small PR to filter out empty params. Feel free to close if there is an issue with doing so, or with my exact method. It's bad practice for an API to require parameters that are not used, so I can't imagine this creating issues. 

As highlighted here, it's more likely an API may try to consume a provided query if it's empty, and will throw a Bad Request response if the parameter is not an expected value
