### ISSUE TITLE
Why does this BaseLLMOutputParser method throw an error?

### ISSUE THREAD

**Issue by Ehzuiq** [hwchase17/langchainjs#1876]
I am getting an error while using the BaseLLMOutputParser method. Here is the usage and error message.

`
const outputParser = new BaseLLMOutputParser(schema());
  const memory = new BufferWindowMemory({ k: 3 });
  const chain = new ConversationChain({
      llm: model,
      memory: memory,
      outputParser: outputParser,
 });
   
   
 const output = await chain.call({
      input: "text",
 });
 console.log("output", output);
`

`this.parseResult is not a function`

**Comment by jacoblee93** [comment]
It's an abstract class: 
https://github.com/hwchase17/langchainjs/blob/f04352eb45ec21cfe283cecd669062a9c39be829/langchain/src/schema/output_parser.ts#L11

You should use a subclass like StructuredOutputParser
