### ISSUE TITLE
createStructuredOutputChainFromZod is not exported from "langchain/chains/openai_functions"

### ISSUE THREAD

**Issue by kartikrao** [hwchase17/langchainjs#1882]
With reference to this example in the documentation: https://js.langchain.com/docs/modules/chains/openai_functions/structured_output

The following import fails in the latest version of langchain - 0.0.103
`import { createStructuredOutputChainFromZod } from "langchain/chains/openai_functions";`

**Comment by jacoblee93** [comment]
I'm heading home to cut a release right now 😅 will be out shortly.

**Comment by jacoblee93** [comment]
0.0.104 is live :)

**Comment by kartikrao** [comment]
@jacoblee93 - Thank you for sorting this out so quickly, much appreciated.
