### ISSUE TITLE
Cannot read properties of undefined (reading 'metadata')?

### ISSUE THREAD

**Issue by Ehzuiq** [hwchase17/langchainjs#1906]
Cannot read properties of undefined (reading 'metadata')?
https://github.com/hwchase17/langchainjs/blob/53b6cb4fd9365e26b21c5e40ed2ddd8077562fdb/langchain/src/document.ts#L20C17-L20C17

```javascript
   const vectors = await embedding.embedQuery("Hi! I'm Jim.");
   const pageContent = "Hi! I'm Jim.";
   const metadata = {
       role: "User",
       window_id: "01234567890"
     };
   const documents = [new Document({pageContent, metadata})];
   const addRes = await vectorStore.addVectors(
      vectors,
      documents,
      {
         ids: ["72601234567890"],
      }
   );
```

**Comment by jacoblee93** [comment]
Thanks for the report - which vector store are you using?

**Comment by jacoblee93** [comment]
Ah I see. It appears `embedQuery()` returns an array representing a vector, and `addVectors` takes an array of those arrays.

Can you let me know if this fixes it?

```
   const vectors = await embedding.embedQuery("Hi! I'm Jim.");
   const pageContent = "Hi! I'm Jim.";
   const metadata = {
       role: "User",
       window_id: "01234567890"
     };
   const documents = [new Document({pageContent, metadata})];
   const addRes = await vectorStore.addVectors(
      [vectors],
      documents,
      {
         ids: ["72601234567890"],
      }
   );
```

**Comment by Ehzuiq** [comment]
Thank you very much for your response, and the error has been fixed.

**Comment by Ehzuiq** [comment]
> 啊，我明白了。看起来`embedQuery()`返回一个表示向量的数组，`addVectors`接受这些数组的数组。
> 
> 你能告诉我这是否能解决它吗？
> 
> ```
>    const vectors = await embedding.embedQuery("Hi! I'm Jim.");
>    const pageContent = "Hi! I'm Jim.";
>    const metadata = {
>        role: "User",
>        window_id: "01234567890"
>      };
>    const documents = [new Document({pageContent, metadata})];
>    const addRes = await vectorStore.addVectors(
>       [vectors],
>       documents,
>       {
>          ids: ["72601234567890"],
>       }
>    );
> ```

According to your suggestions, the problem has been resolved. Thank you very much.
