### ISSUE TITLE
use similaritySearch by supabase is error

### ISSUE THREAD

**Issue by coloz** [hwchase17/langchainjs#1909]
error info:
```
file:///D:/git/aily-project/vector/node_modules/langchain/dist/vectorstores/supabase.js:79
            throw new Error(`Error searching for documents: ${error.code} ${error.message} ${error.details}`);
                  ^

Error: Error searching for documents: 42883 operator does not exist: extensions.vector <=> extensions.vector null
```

**Comment by devstein** [comment]
@coloz Is the `pg_vector` extension installed on your Supabase instances?

```sql
-- Enable the pgvector extension to work with embedding vectors
create extension vector;
```

**Comment by coloz** [comment]
> @coloz Is the `pg_vector` extension installed on your Supabase instances?
> 
> ```sql
> -- Enable the pgvector extension to work with embedding vectors
> create extension vector;
> ```

It could be due to a lower version of my `pgvector`. I am using Supabase's cloud service, and it is working fine.
