### ISSUE TITLE
AzureChatOpenAI Streaming causes IndexError

### ISSUE THREAD

**Issue by m-hamaro** [hwchase17/langchainjs#1914]
If you set the openai_api_version of the azure openai service to `2023-06-01-preview`, the response is changing its shape due to the addition of the contents filter.

There is a similar issue in the python version of langchain, but I am facing the same error in the js version
https://github.com/hwchase17/langchain/issues/6462

Sorry, I am still new to langchain.ts and do not know how to fix this.
Please help me.

**Comment by jacoblee93** [comment]
Does this occur for you when setting version to `2023-05-15`?

Looked into this and it seems there's a change in events in the preview version - given that it's `preview`, it might be best to avoid making an unnecessary change here until the mainline version comes out:

https://github.com/Azure/azure-sdk-for-go/issues/21086

**Comment by m-hamaro** [comment]
I just tried and this problem did not occur on `2023-05-15` 
As you indicated, this event seems to occur in the PREVIEW version.

I've included the responses for each version for your reference.

`2023-03-15-preview`

```
{
    "id": "chatcmpl-7av32xg4UQqLWqSYXRYYHI0zyUSLx",
    "object": "chat.completion",
    "created": 1689033456,
    "model": "gpt-35-turbo",
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "Hello! How can I assist you today?"
            }
        }
    ],
    "usage": {
        "completion_tokens": 9,
        "prompt_tokens": 10,
        "total_tokens": 19
    }
}
```

`2023-05-15`

```
{
    "id": "chatcmpl-7av3Y0V5pjJ8te5SeizWXomOi12G9",
    "object": "chat.completion",
    "created": 1689033488,
    "model": "gpt-35-turbo",
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "Hello there! How can I assist you today?"
            }
        }
    ],
    "usage": {
        "completion_tokens": 10,
        "prompt_tokens": 10,
        "total_tokens": 20
    }
}
```

`2023-06-01-preview`

```
{
    "id": "chatcmpl-7av4UrAmKWNfc0y5ZQcdzpc8x2qd0",
    "object": "chat.completion",
    "created": 1689033546,
    "model": "gpt-35-turbo",
    "prompt_annotations": [
        {
            "prompt_index": 0,
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": false,
                    "severity": "safe"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            }
        }
    ],
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "Hello there! How may I assist you today?"
            },
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": false,
                    "severity": "safe"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            }
        }
    ],
    "usage": {
        "completion_tokens": 10,
        "prompt_tokens": 10,
        "total_tokens": 20
    }
}
```

As you can see from the response here, the format of the response changed significantly on `2023-06-01-preview`.
A similar problem occurs with `stream=true`
I am not sure how long Azure will let us use past models, but I believe this issue will have to be addressed at some point.

**Comment by jacoblee93** [comment]
Yes, let's wait until they get out of preview for the latest model though as it seems it's under discussion on their end. I'll close this for now, thanks again for the report!

**Comment by jacoblee93** [comment]
Looks like it might be here to stay: https://github.com/Azure/azure-sdk-for-go/issues/21086

**Comment by jacoblee93** [comment]
I'm going to plan on fixing this along with integrating the new OpenAI v4 SDK - should hopefully be in the next week or so.

**Comment by hcl242** [comment]
Temporary modification can be made to the 334th line of openai.js as follows: add 'if(!data.id) return;' It should look like this:`
               333             const data = JSON.parse(event.data);
               334             if(!data.id) return;
               335             if (data?.error) {
`

**Comment by jacoblee93** [comment]
> Temporary modification can be made to the 334th line of openai.js as follows: add 'if(!data.id) return;' It should look like this:
> 
> ```
> 333             const data = JSON.parse(event.data);
> 334             if(!data.id) return;
> 335             if (data?.error) {
> ```
> 
> langchainjs version 0.0.115.

Going to go with this!
