### ISSUE TITLE
Langchain JS PromptLayerChatOpenAI doesnt recognize message with type == "function"

### ISSUE THREAD

**Issue by digitpdigit** [hwchase17/langchainjs#1939]
I'm using "langchain": "^0.0.100",
I got unknown type error when calling function using PromptLayerChatOpenAI gpt-3.5-turbo-0613 model

this is easily solved by adding several lines to openai.cjs as shown in the image below
but that solution would be very unpractical to be done on deployment

![image](https://github.com/hwchase17/langchainjs/assets/67557217/4e407e5a-0f9e-4fa7-9d2f-17cb1356f30d)

might be a minor bug due to recent function calling implementation on the langchain side?

**Comment by jacoblee93** [comment]
Could you open a PR for this?

**Comment by digitpdigit** [comment]
Yes, will do

Thanks for the response

**Comment by jacoblee93** [comment]
Fixed in #1948, will be out with the next release!
