### ISSUE TITLE
Azure OpenAI is streaming sentences

### ISSUE THREAD

**Issue by transmoga** [hwchase17/langchainjs#1940]
I have integrated my NextJS app with the Azure Open AI models.  It works, with the latest release of langchainjs

Unfortunately, the streaming behaviour of Azure Open AI appears to have diverged from that of OpenAI.

Azure's streaming model now seems to be outputting complete sentences, rather than the previous chunk-based approach.

Has anyone encountered and solved this issue? The user interface with these sentence chunks comes off as somewhat strange.

**Comment by jacoblee93** [comment]
We unfortunately can't do anything about this, but you could solve this at the application layer by e.g. making another streaming layer that buffers the streaming output from the model and returns a character every x milliseconds.
