### ISSUE TITLE
langchain in commonjs  come up a error

### ISSUE THREAD

**Issue by kill136** [hwchase17/langchainjs#1943]
in commonjs environment，call  langchain  like below：
 const {
	OpenAI,
	OpenAIChat
} = require("langchain/llms/openai");

#################################
 Unexpected token export\n/var/user/node_modules/langchain/llms/openai.js:1\n(function (exports, require, module, __filename, __dirname) { export * from '../dist/llms/openai.js'\n                                                              ^^^^^^\n\nSyntaxError: Unexpected token export\n    at createScript (vm.js:80:10)\n    at Object.runInThisContext (vm.js:139:10)\n    at Module._compile (module.js:607:28)\n    at Object.Module._extensions..js (module.js:654:10)\n    at Module.load (module.js:556:32)\n    at tryModuleLoad (module.js:499:12)\n    at Function.Module._load (module.js:491:3)\n    at Module.require (module.js:587:17)\n    at require (internal/module.js:11:18)\n

**Comment by jacoblee93** [comment]
Happy to try to help? Which version of LangChain are you running?

Just tried with a starter Nest.js project (running CommonJS) with the latest version (0.0.107) and it seemed to work ok:

https://github.com/jacoblee93/langchain-nest-test

**Comment by jacoblee93** [comment]
https://github.com/jacoblee93/langchain-nest-test/blob/master/src/app.controller.ts#L3
