### ISSUE TITLE
Call custom api with same structure as Azure OpenAI

### ISSUE THREAD

**Issue by vicdotdevelop** [hwchase17/langchainjs#1944]
Dear Community ⭐️,

**Use Case:** 
We are building an API, which sits in front of multiple azure open AI instances.
The idea is to easy enable developers adapting the service without ordering their own subscription and setting up azure open ai service, while we can log which API key has used how many tokens.

We would like to have a custom connector, where we can route the request to our own URL having the same body and headers instead of direct attaching Azure OpenAI or OpenAI Service as API.

I haven't jumped too deep into the rabbit hole on how langchain connects to these services but I assume somewhere, its doing any kind of HTTP calls.
Does langchain already have that or is this even possible with human efforts?

Looking forward for your suggestions <3

**Comment by jacoblee93** [comment]
@vicdotdevelop the above @dosu-beta comment may be helpful?

**Comment by jacoblee93** [comment]
Will close for now!

**Comment by vicdotdevelop** [comment]
> @vicdotdevelop the above @dosu-beta comment may be helpful?

Hey @jacoblee93 sorry for the late reply. Need to check if it's working. Thank you ! 👍🏽
