### ISSUE TITLE
Streaming Anthropic chat model broken with `TypeError: sdk_1.Anthropic is not a constructor`

### ISSUE THREAD

**Issue by palmm** [hwchase17/langchainjs#1958]
Calling an anthropic streaming chat model results in:
```
node_modules/.pnpm/langchain@0.0.108_boejqnsdfltldqkbpa6we5iqvu/node_modules/langchain/dist/chat_models/anthropic.cjs:215
                this.streamingClient = new sdk_1.Anthropic({
                                       ^
TypeError: sdk_1.Anthropic is not a constructor
    at ChatAnthropic.completionWithRetry (node_modules/.pnpm/langchain@0.0.108_boejqnsdfltldqkbpa6we5iqvu/node_modules/langchain/dist/chat_models/anthropic.cjs:215:40)
    at ChatAnthropic._generate (node_modules/.pnpm/langchain@0.0.108_boejqnsdfltldqkbpa6we5iqvu/node_modules/langchain/dist/chat_models/anthropic.cjs:191:37)
    at node_modules/.pnpm/langchain@0.0.108_boejqnsdfltldqkbpa6we5iqvu/node_modules/langchain/dist/chat_models/base.cjs:48:88
    at Array.map (<anonymous>)
    at ChatAnthropic.generate (node_modules/.pnpm/langchain@0.0.108_boejqnsdfltldqkbpa6we5iqvu/node_modules/langchain/dist/chat_models/base.cjs:48:59)
    at ChatAnthropic.call (node_modules/.pnpm/langchain@0.0.108_boejqnsdfltldqkbpa6we5iqvu/node_modules/langchain/dist/chat_models/base.cjs:98:24)
```

Afaict, https://github.com/hwchase17/langchainjs/pull/1932 appears to have broken streaming anthropic chat models.

Probable repro (untested):
```
import { ChatAnthropic } from 'langchain/chat_models/anthropic';

const model = new ChatAnthropic({
  anthropicApiKey: process.env.ANTHROPIC_API_KEY,
  modelName: "claude-instant-1",
  streaming: true,
});
const response = model.call(
  [
    new HumanMessage(
      "Please, write me a list of 10 good name options for a company that makes colorful socks."
    ),
  ],
  {},
  [
    {
      handleLLMNewToken: (token) => {
        console.log({ token });
      },
    },
  ]
);

```

**Comment by jacoblee93** [comment]
The above @dosu-beta comment is actually more or less what I would look at. Can you tell me what environment you're running in? `new sdk_1.Anthropic` sounds like there's some bundling going on.

Also, I can't imagine this wouldn't be the case, but can you double check that the version of Anthropic's SDK is `0.5.3`?

**Comment by palmm** [comment]
I'm running in a nodejs env with the bundling done via webpack. I think this is some esoteric issue related to requirements. I can see that the node runtime is picking up the CommonJS output version of langchain and I can repro this on a clean nodejs repo with this code in a javascript file and running in node (no bundling required):
```
const { ChatAnthropic } = require('langchain/chat_models/anthropic');
const { HumanMessage } = require('langchain/schema');

const model = new ChatAnthropic({
  anthropicApiKey: "KEY_HERE",
  modelName: 'claude-instant-1',
  streaming: true,
});
const response = model.call(
  [
    new HumanMessage(
      'Please, write me a list of 10 good name options for a company that makes colorful socks.'
    ),
  ],
  {},
  [
    {
      handleLLMNewToken: (token) => {
        console.log({ token });
      },
    },
  ]
);
```

I think the issue is that, if the cjs version of langchain is used, the anthropic import in the cjs code is:
```
const sdk_1 = require("@anthropic-ai/sdk");
```

which then is used like this:
```
                this.streamingClient = new sdk_1.Anthropic({
                    ...options,
                    apiKey: this.anthropicApiKey,
                });
```

the issue arises from the fact that there is a collision on `Anthropic` from the anthropic sdk. It starts as an export of the client API:
`export class Anthropic extends Core.APIClient {`
but then below it is re-exported:
`export namespace Anthropic {`
and then default exported:
`export default Anthropic;`

So I think when node runs the langchain cjs code, `sdk_1.Anthropic` doesn't resolve to the desired class. Instead it resolves to the namespace (i'm assuming).

**Comment by palmm** [comment]
does not repro if I used the `mjs` EcmaScript module version of langchain, e.g.
```
import { ChatAnthropic } from 'langchain/chat_models/anthropic';
import { HumanMessage } from 'langchain/schema';

const model = new ChatAnthropic({
  anthropicApiKey: "KEY_HERE",
  modelName: 'claude-instant-1',
  streaming: true,
});
const response = model.call(
  [
    new HumanMessage(
      'Please, write me a list of 10 good name options for a company that makes colorful socks.'
    ),
  ],
  {},
  [
    {
      handleLLMNewToken: (token) => {
        console.log({ token });
      },
    },
  ]
);
```

**Comment by palmm** [comment]
Raised a fix here: https://github.com/hwchase17/langchainjs/pull/1969
Explicitly using the default export in langchain emits the correct cjs code, solving this issue.
