### ISSUE TITLE
RedisChatMessageHistory retrieval of session only works with BufferMemory? Failed with ConversationSummary

### ISSUE THREAD

**Issue by enigmablue** [hwchase17/langchainjs#1959]
Hi i've been doing some experimenting, and could not figure out why my API wasn't getting the history correctly from Redis. It works with Buffer but not with ConversationSummary.

For example, when using  ConversationSummaryMemory (my preferred), this is my triggered dialogue 

based on this code:
`   const res1 = await chain.call({ input: 'My name is Jim and i work as a teacher' });
const res2 = await chain.call({ input: promptAfterFormat }); //just a prompt template that i'm not sharing because its big.
const res3 = await chain.call({ input: 'what is my name and job again?' });
`

Result:
{
  **res1**: {
    response: " Hi Jim! It's nice to meet you. It seems like you work in an important field. Do you like teaching?"
  },
  memory: {
    history: "The human introduces themselves as Jim, a teacher. The AI acknowledges Jim's profession and asks if he enjoys teaching."
  }
}
{
  **res2**: {
    response: " [Reply] Hi there, my name is Mary. I know from our conversations that your name is Jim and you're a teacher. Do you enjoy teaching?"
  },
  memory: {
    history: "The human introduces themselves as Jim, a teacher. The AI acknowledges Jim's profession and asks if he enjoys teaching. The AI, named Mary, responds to a player in a learning metaverse, stating that Jim's name is Jim and he is a teacher. Mary then asks Jim if he enjoys teaching."
  }
}
{
  **res3**: {
    response: ' Your name is Jim and you are a teacher. Do you enjoy teaching?'
  },
  memory: {
    history: "The human introduces themselves as Jim, a teacher. The AI acknowledges Jim's profession and asks if he enjoys teaching. The AI, named Mary, responds to a player in a learning metaverse, stating that Jim's name is Jim and he is a teacher. Mary then asks Jim if he enjoys teaching. The AI confirms that Jim's name is Jim and he is a teacher, and asks if he enjoys teaching."
  }

ISSUE: However when i reload the API (and associated Redis session) it does not remember.

`const res3 = await chain.call({ input: 'what is my name and job again?' });`
This is the result:
{
  res3: {
    response: ' Your name is John Smith and your job is an accountant. Is there anything else I can help you with?'
  },
  memory: {
    history: 'The human asks the AI for their name and job. The AI responds that their name is John Smith and their job is an accountant.'
  }
}

However, this works fine when i load BufferMemory.

With buffer memory:
 res3: {
    response: '  Your name is Jim and your job is a teacher. Is there anything else I can help you with related to your job?'
  },

Expected?

**Comment by jacoblee93** [comment]
This memory doesn't actually store messages, just a summary of the messages.

We could make this cleaner/more intuitive but for now you can call `await memory.loadMemoryVariables({})` and store it somewhere yourself.

**Comment by enigmablue** [comment]
i'm not expecting langchain to store it but its the part on redis not being picked up for ConversationSummary

const memory = new BufferWindowMemory({
    chatHistory: new RedisChatMessageHistory({
          sessionId, // Or some other unique identifier for the conversation
          sessionTTL: 300, // 5 minutes, omit this parameter to make sessions never expire
          config: {
            url: process.env.REDIS_URI, // Default value, override with your own instance's URL
          },
        }),
        k: 5,
  });
