### ISSUE TITLE
missing search kwargs for asRetriever() method for vectorstores. 

### ISSUE THREAD

**Issue by OmriNach** [hwchase17/langchainjs#1971]
Would like to pass in metadata filters which in python langchain is done as follows:
vectorstore.as_retriever(search_kwargs={"filter":{'field_name':filter_value})

**Comment by jacoblee93** [comment]
Ah @OmriNach the above is actually the correct way to do it:

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/base.ts#L128

It's not documented though - we're in the middle of a bit of a refactor and I will make sure I add it!
