### ISSUE TITLE
Building a chrome extension with LangChain

### ISSUE THREAD

**Issue by ManishAradwad** [hwchase17/langchainjs#1986]
Hi, 

I'm trying to build a chrome extension which uses LLM from Langchain. I have installed the langchain package from npm but while trying to import LLMChain with `import { LLMChain } from "langchain/chains";` I'm getting an error saying:

`Uncaught TypeError: Failed to resolve module specifier "langchain/chains". Relative references must start with either "/", "./", or "../".`

I checked the node_modules folder in my project directory, langchain is installed. Also node_modules/langchain/chains.js file does exist.

This might be a very simple problem to solve but I'm a beginner so any help is appreciated.

**Comment by jacoblee93** [comment]
Sounds like the bot helped!
