### ISSUE TITLE
Configuration using OpenAI API hosted on Azure 

### ISSUE THREAD

**Issue by gclem** [hwchase17/langchainjs#2013]
Hi, 

There are 2 cases of handling API URL on Azure : 
 
First one is generated from the instance name in .env file 
`AZURE_OPENAI_API_INSTANCE_NAME=''`

Documented here 
`    /**
     * Azure OpenAI API deployment name to use for completions when making requests to Azure OpenAI.
     * This is the name of the deployment you created in the Azure portal.
     * e.g. "my-openai-deployment"
     * this will be used in the endpoint URL: https://{InstanceName}.openai.azure.com/openai/deployments/my-openai-deployment/
     */
    azureOpenAIApiDeploymentName?: string;`

Second one, is static. 
From what I can see with my account, there are differents typologies of clusters, depending the location of deployement (Azure region) 
My second cluster has a generic url path : 
`AZURE_OPENAI_BASE_PATH=https://westeurope.api.cognitive.microsoft.com/`

I have an issue, during  the creation of the vector store (seems the class OpenAIEmbedding), not using the overwriten BASEPATH in the config file. 

`creating vector store...
error Error: getaddrinfo ENOTFOUND [instanceName].openai.azure.com
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at __node_internal_ (node:internal/errors:715:10)
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26) {
  errno: -3008,
  code: 'ENOTFOUND',`

In ingest-data.ts 
`const embeddings = new OpenAIEmbeddings();`

Any example on making Embedding works without updating the code with Azure on your side folks?

**Comment by jacoblee93** [comment]
Hey @gclem, the URL to Azure is parsed like this: 

`${azureOpenAIBasePath}/${azureOpenAIApiDeploymentName}`. It could definitely be better documented though. 

Can you try that?

**Comment by gclem** [comment]
Thanks, it works for static API url overwritting.
