### ISSUE TITLE
Documents are not saved in Opensearch when using textsplitters

### ISSUE THREAD

**Issue by nirajmchauhan** [hwchase17/langchainjs#2036]
I am using `CheerioWebBaseLoader` to load the documents and save them in the AWS Opensearch. What I realised is that the documents are not getting saved and there is no error as well. But when I remove the `TextSplitter` then the document is getting saved. Here is my code:

```ts
const loader = new CheerioWebBaseLoader(link);

const rawDocs = (await loader.load()).map((d) => {
  return new Document({
    metadata: { originalSource: link },
    pageContent: d.pageContent,
  });
});

const textSplitter = new RecursiveCharacterTextSplitter({
  chunkSize: 100,
  chunkOverlap: 10,
});

const docs = await textSplitter.splitDocuments(rawDocs);

await OpenSearchVectorStore.fromDocuments(
  docs,
  new OpenAIEmbeddings(),
  {
    client,
    indexName: "documents",
  }
);
```

I cannot go ahead without using `TextSplitter` as if the document is huge, then OpenAI gives 400 errors. Is there a solution to this?

**Comment by nirajmchauhan** [comment]
Hey 🤖
I changed the chunk & overlap size as you suggested, still the documents are not getting saved.
```ts
const textSplitter = new RecursiveCharacterTextSplitter({
  chunkSize: 1000,
  chunkOverlap: 200,
});
```

**Comment by jacoblee93** [comment]
The issue seems to be that OpenSearch can't handle certain types of metadata? 

I think the bot's response sounds reasonable here - adding a filter step to the vector store itself would be nice too if you feel up for opening a PR?

**Comment by nirajmchauhan** [comment]
I ended up fixing this by adding indexing for `{metadata:{loc:{lines:{start: Int, end: Int}}}}`

**Comment by kiraraty** [comment]
> I ended up fixing this by adding indexing for `{metadata:{loc:{lines:{start: Int, end: Int}}}}`

What's Int? please

**Comment by nirajmchauhan** [comment]
> 

Its Integer

**Comment by zhjch05** [comment]
@nirajmchauhan Would you mind share how did you add indexing? Appreciate the help! Facing same issue. Is there a way to add a general dynamic mapping for metadata that automatically handles this?

**Comment by rushikeshRL** [comment]
@zhjch05 
You can update the mapping from Opensearch dashboard:
![image](https://github.com/langchain-ai/langchainjs/assets/115528161/6291233d-83d0-4f10-98ce-176d7b60b4c1)

**Comment by zhjch05** [comment]
> @zhjch05 You can update the mapping from Opensearch dashboard: ![image](https://private-user-images.githubusercontent.com/115528161/281575922-6291233d-83d0-4f10-98ce-176d7b60b4c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMTA5OTgsIm5iZiI6MTcwNzIxMDY5OCwicGF0aCI6Ii8xMTU1MjgxNjEvMjgxNTc1OTIyLTYyOTEyMzNkLTgzZDAtNGYxMC05OGNlLTE3NmQ3YjYwYjRjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNlQwOTExMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODUxN2YzZGI4M2RmMDM0Y2Q2NDg5YzFhZmZiNGM4YmM4MjdlODhmM2IwN2Y3NjY4YjY4NmZmNjhkN2FmMzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g3VkYoDl3AmIVKFjAL_yeg2GPcbKfXoDU2iWyAQ041E)

Thank you!
