### ISSUE TITLE
GithubRepoLoader not working

### ISSUE THREAD

**Issue by SriPrarabdha** [hwchase17/langchainjs#2056]
<img width="545" alt="image" src="https://github.com/hwchase17/langchainjs/assets/89463301/2e419b6f-0eb5-4672-acbf-3014f86e48f3">

I have been trying to run this code taken from documentation but it keeps giving the error that 'Fetch' is not defined

<img width="437" alt="image" src="https://github.com/hwchase17/langchainjs/assets/89463301/d7cdb7a8-bcc7-4ad8-b3cf-c6f6d5d2a713">

It can be a bug where node-fetch library is causing some issues or it's a silly mistake at my end
Would love some help on it

**Comment by SriPrarabdha** [comment]
interestingly using just the fetch function and the code from github.ts file on my machine I am able to extract the data

**Comment by SriPrarabdha** [comment]
I actually tried all the methods that were available on the internet to resolve this issue . I added node-fetch and node-fetch@v2 package  and imported them in my code but it didn't resolved the issue.

Also I somewhat tweaked the package.json to make it compatible but it didn't work

**Comment by jacoblee93** [comment]
Are you on Node 16? LangChain only officially supports Node 18 and up.

You can try these instructions if so:
https://js.langchain.com/docs/get_started/installation#unsupported-nodejs-16
