### ISSUE TITLE
Help: InsufficientQuotaError after following the quickstart guide

### ISSUE THREAD

**Issue by kelvinsekx** [hwchase17/langchainjs#2083]
This is my code which I think is exactly what's in the quickstart guide

```js
import { OpenAI } from "langchain/llms/openai";

const llm = new OpenAI({
  modelName: "gpt-3.5-turbo",
  temperature: 0.1,
});

const predict = async () => {
  const result = await llm.predict(
    "What would be a good company name for a company that makes colorful socks?"
  );
  console.log(result);
};

predict();

```

But I keep getting the error in the screenshot
![Screenshot (71)](https://github.com/hwchase17/langchainjs/assets/51183064/13da9adc-4636-43d2-9d12-c1c316585cc8)

**Comment by kelvinsekx** [comment]
I did exactly like the AI example and it never worked. I intentionally skipped the openAIApiKey props in my snippet above.

**Comment by devstein** [comment]
@kelvinsekx Have you looked at your [OpenAI account usage](https://platform.openai.com/account/usage)? This will give you more information about your current usage and API limits/quota.

**Comment by kelvinsekx** [comment]
> @kelvinsekx Have you looked at your [OpenAI account usage](https://platform.openai.com/account/usage)? This will give you more information about your current usage and API limits/quota.

I recently just got to realize I need to subscribe to pay as you go plan of the API and OpenAI no longer have a free version.
