### ISSUE TITLE
ConversationalRetrievalQAChain Chat history coming as response

### ISSUE THREAD

**Issue by nirajattravelopia** [hwchase17/langchainjs#2098]
I am using `ConversationalRetrievalQAChain` with `stream`. When I pass chat history along with the question, in the streaming response, the entire chat history comes first and then the actual answer, why is this happening? I only want a response for the new question and not the chat history.

```ts
const llm = new OpenAIChat({
  temperature: 0,
  modelName: 'gpt-3.5-turbo',
  maxRetries: 3,
  streaming: true,
  callbacks: [
    {
      handleLLMNewToken(token: string) {
        if (token !== '') {
          observer.next(`data: ${token}\n\n`);
        }
      },
      handleLLMError(error: Error) {
        logger.error(error);
        observer.error(error);
      },
    },
  ],
});

const retrievalChain = ConversationalRetrievalQAChain.fromLLM(llm, vectorStore.asRetriever(), {
  returnSourceDocuments: true,
});

retrievalChain
.call({
  question,,
  chat_history: `${firstQuestion}\n${firstAnswer}`,
})
```

**Comment by benedictbihl** [comment]
You need to use two separate models along with the questionGeneratorChainOptions settings to only output the final answer as stream 

https://js.langchain.com/docs/modules/chains/popular/chat_vector_db#streaming
