### ISSUE TITLE
Update chroma integration to note that it has node support

### ISSUE THREAD

**Issue by jeffchuber** [hwchase17/langchainjs#2100]
Chroma's client is isomorphic, but the current sidebar implies it does not work in Node. Suggestions for how to fix this? @nfcampos Thanks! 

<img width="693" alt="Screenshot 2023-07-26 at 10 36 44 PM" src="https://github.com/hwchase17/langchainjs/assets/891664/10d29873-ed7a-4a01-b51d-e38c27500fec">

**Comment by neebdev** [comment]
The sidebar label "Node.js" implies that it only works in Node.js. So the vector stores without the label are isomorphic.

**Comment by jeffchuber** [comment]
@jacoblee93 ah i see - i think `node-only` would be more clear. Currently it looks like Chroma does not work in Node - which I think confuses users because it does! You could also have `B` and `N` chips and then put them on each client.

**Comment by jacoblee93** [comment]
B and N?

**Comment by jeffchuber** [comment]
`Browser` and `Node`

**Comment by jacoblee93** [comment]
Gotcha - `Browser` doesn't quite encapsulate it since there's Cloudflare Workers/Edge functions/Deno as well. I'll make it say `Node-only`

**Comment by jeffchuber** [comment]
@jacoblee93 very good point
