### ISSUE TITLE
Atlas vector store retriever breaking on getRelevantDocuments

### ISSUE THREAD

**Issue by sdellama** [hwchase17/langchainjs#2108]
After https://github.com/hwchase17/langchainjs/pull/1990 the `getRelevantDocuments` started to break due to misaligned signature implementation of the similaritySearchVectorWithScore method and the unneeded override of the similaritySearch method. See` langchain/src/vectorstores/mongodb_atlas.ts`

**Comment by sdellama** [comment]
please assign this to me

**Comment by jacoblee93** [comment]
Thanks for the heads up! Assigned it to you.

**Comment by sdellama** [comment]
Opened PR [2120](https://github.com/hwchase17/langchainjs/pull/2120)

**Comment by jacoblee93** [comment]
Fixed by #2120 in 0.0.120
