### ISSUE TITLE
Allow ChromaClient to be initialized outside Chroma Vector Store

### ISSUE THREAD

**Issue by shripadk** [hwchase17/langchainjs#211]
While trying out Chroma integration I stumbled upon the following error:

```bash
Error: Please install chromadb as a dependency with, e.g. `npm install -S chromadb`
```

Even though I had already installed `chromadb`.

When I dug into the source, I was surprised to see that `ChromaClient` is being required and initialized directly here: https://github.com/hwchase17/langchainjs/blob/main/langchain/src/vectorstores/chroma.ts#L10-L15

This doesn't work well with cli tools like [tsx](https://www.npmjs.com/package/tsx).

Any reason why this is the case? Why can't we just pass our own initialized `ChromaClient` to `fromDocuments`? Also, this would cause an issue when ChromaDB has a different `basePath` and is hosted on a remote machine as currently there is no way to configure parameters that are passed to `ChromaClient`.

This is already being done with `PineconeStore` where we pass in the `index` initialized outside the `PineconeStore` itself.

Keeping the API consistent with `PineconeStore`, my suggestion would be to have this function signature for `fromDocuments` (and `fromTexts` too):

```ts
static fromDocuments(
  client: ChromaClient,
  docs: Document[],
  embeddings: Embeddings,
  collectionName?: string,
  url?: string
): Promise<Chroma>;
```

And of course remove the need to initialize `ChromaClient` directly and let us pass the initialized client instead.

**Comment by shripadk** [comment]
I am currently doing it this way though I prefer using `Chroma.fromDocuments` instead:

```tsx
const client = new ChromaClient();

const chroma = new Chroma(
  {
    collectionName,
    numDimensions,
  },
  embeddings,
  client
);

await chroma.addDocuments(docs);
```

**Comment by nfcampos** [comment]
hi @shripadk thanks, this was something we missed when converting the library to ESM, thanks for pointing it out, fixing it here #220

**Comment by shripadk** [comment]
@nfcampos Thank you!
