### ISSUE TITLE
cosineSimilarity(), maximalMarginalRelevance(), and any util can't be imported

### ISSUE THREAD

**Issue by afirstenberg** [hwchase17/langchainjs#2113]
The `cosineSimilarity()` and `maximalMarginalRelevance()` functions were added with the `math_utils.ts` file in #1973.

However, this function can't be imported outside of langchain since it isn't included in the package.json "exports". In fact, nothing from the `util` directory is available since they are only in the `dist` directory.

I'm not familiar enough with how "exports" or any of this is built, but it seems like `math_utils` as a minimum should be included in this process, and there is a good case that all of `util` should be.

**Comment by jacoblee93** [comment]
Yeah, I wouldn't have a problem with adding it as an entrypoint - what would your use-case be?

**Comment by afirstenberg** [comment]
In this case, I'm using it to demonstrate how similar sets of embeddings are to each other to demonstrate or evaluate how effective the embedding library is. In theory, this could be done by using a vector database, but this also guarantees to give us a numeric evaluation of how similar the vectors are.
