### ISSUE TITLE
I hope to add concurrency settings in OpenAIEmbedding

### ISSUE THREAD

**Issue by milerL** [hwchase17/langchainjs#2140]
引用 #250 

The following is the official source code

```
 async embedDocuments(texts: string[]): Promise<number[][]> {
    const subPrompts = chunkArray(
      this.stripNewLines ? texts.map((t) => t.replace(/\n/g, " ")) : texts,
      this.batchSize
    );

    const embeddings: number[][] = [];

    for (let i = 0; i < subPrompts.length; i += 1) {
      const input = subPrompts[i];
      const { data } = await this.embeddingWithRetry({
        model: this.modelName,
        input,
      });
      for (let j = 0; j < input.length; j += 1) {
        embeddings.push(data.data[j].embedding);
      }
    }

    return embeddings;
  }
```

You can see that this is executed sequentially, although adding batchSize

But embedding is often used in conjunction with splitters, with splitter chunkSize: 1000

Is the default value of batchSize 512?

So I hope to add concurrency, although I know there is an openai frequency limit, I still hope to have concurrency parameters to control concurrency.

I am using gitbook loader -->splitter -->embedding -->qdrant

This made me wait for 30 minutes, it's too slow, I can't accept it

**Comment by jacoblee93** [comment]
This would be great! Would love a PR.
