### ISSUE TITLE
ConversationalRetrievalQAChain: qaChainOptions only work with type parameter set

### ISSUE THREAD

**Issue by benedictbihl** [hwchase17/langchainjs#2158]
When customizing the qaChain prompt, one needs to explicitly set the type like this:

<img width="778" alt="image" src="https://github.com/hwchase17/langchainjs/assets/20840784/9a4fea62-7316-496f-a899-8f5c839bd320">

Omitting the type param will lead to an error. This is not clear from the docs and at least mentioned there, or fixed in general.

**Comment by jacoblee93** [comment]
We could have this as a default I suppose but it's working as intended - there's a few different options for which QA chain runs on the chain:

https://js.langchain.com/docs/modules/chains/document/
