### ISSUE TITLE
import problems with Deno on Supabase edge functions.

### ISSUE THREAD

**Issue by KamaniBhavin** [hwchase17/langchainjs#2169]
Title: Error with langchain on Supabase in Deno environment

Issue Description:
I recently ran into an issue while working with langchain on Supabase within the Deno environment. It resulted in an error message: 

```
Uncaught SyntaxError: The requested module '/npm/openai@3.3.0/+esm' does not provide an export named 'Configuration' at https://cdn.jsdelivr.net/npm/langchain@0.0.122/+esm:7:427
```

Steps to Reproduce:
1. Use the Deno environment.
2. Attempt to use langchain on Supabase.
3. Observe the "Uncaught SyntaxError" with the mentioned module and export error.

Expected Behavior:
There should be no SyntaxError, and the 'Configuration' export should be available from the specified module.

Environment:
- Deno version: [insert Deno version]
- langchain version: 0.0.122
- Supabase version: [insert Supabase version]

Additional Information:
The error seems to be related to the 'openai' module at version 3.3.0, which is utilized within langchain. Any insights into resolving this issue would be greatly appreciated.

**Comment by sandeepone** [comment]
Did you try esm? `https://esm.sh/langchain@0.0.122`

**Comment by KamaniBhavin** [comment]
> Did you try esm? `https://esm.sh/langchain@0.0.122`

yes, I figured it out.
