### ISSUE TITLE
Supabase hybrid search retriever metadata is not getting passed to the funciton

### ISSUE THREAD

**Issue by Nedi11** [hwchase17/langchainjs#2182]
https://github.com/hwchase17/langchainjs/blob/a25677702bac226665cea861b138b7070b6658b7/langchain/src/retrievers/supabase.ts#L59

Here metadata should be passed to the filter argument of match_documents function

**Comment by jacoblee93** [comment]
Thanks for spotting! Up for opening a PR?

**Comment by Nedi11** [comment]
> Thanks for spotting! Up for opening a PR?

Opened PR #2194

**Comment by cdgmx** [comment]
Still `filter: this.metadata || {},` was not added on matchDocumentsParams on release 0.0.127
