### ISSUE TITLE
OpenAI Embeddings: Embed documents should be parallelized

### ISSUE THREAD

**Issue by yroc92** [hwchase17/langchainjs#2197]
The [embedDocuments](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/embeddings/openai.ts#L129C9-L129C23) method in `embeddings/openai.ts` loops through the `texts` array and awaits the response for each. At Postman, we've seen massive performance gains by simply creating a list of promises and using `Promise.all` (~100 seconds down to ~3 for a midsized code repo). I can submit a PR with the change.

See also the GithubRepoLoader: https://github.com/hwchase17/langchainjs/issues/2196

**Comment by jacoblee93** [comment]
Yes, they should be! Thanks for flagging. If you're up for a PR we'd love that.

**Comment by jacoblee93** [comment]
I think making them runnables might be a nice thing to do:

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/schema/runnable.ts

We'd get `batch` for free.
