### ISSUE TITLE
Chaining and making complex Supabase filters

### ISSUE THREAD

**Issue by EmilioJD** [hwchase17/langchainjs#2225]
When doing metadata query building filters. I'm having a hard time combining filters. For example,

` const mockFilter: SupabaseFilterRPCCall = (rpc) =>
    rpc.filter("metadata->b::int", "gt", 0).`

which filters "b" in the metadata field to make sure it's greater than 0. what if I want to filter my table such that "b" is greater than zero OR if b doesn't exist within the table. Having a difficult time figuring this out and was wondering if anyone can help. The docs don't seem to provide much context on the syntax of these filters.

**Comment by jacoblee93** [comment]
Hey @EmilioJD! Try some of the filters from the Supabase docs here:

https://supabase.com/docs/reference/javascript/or

Feel free to reopen if they don't seem to work properly in LangChain.
