### ISSUE TITLE
ConversationalRetrievalQAChain with FirestoreChatMessageHistory: problem with chat_history

### ISSUE THREAD

**Issue by Zained** [hwchase17/langchainjs#2227]
Hello,

I would like to call ConversationalRetrievalQAChain :
- vectorstore : Pinecone (working fine so far)
- Firestore history: working fine with `ConversationChain` but not here

Did someone manage to get firestore history working with ConversationalRetrievalQAChain ?

Here a snippet of my code : 

```
    const fileContent = fs.readFileSync("serviceAccountKey.json", 'utf8');
    const serviceAccount = JSON.parse(fileContent);

    admin_fs.initializeApp({
      credential: admin_fs.credential.cert(serviceAccount)
    });

    const vectorStore = await init_vectorStore();

    const chatHistory = new FirestoreChatMessageHistory({
        collectionName: "DEMO_LANGCHAIN",
        sessionId: "lc-example_8",
        userId: "test@test.com",
        config: {
            admin_fs
        },
    })

    const memory = new BufferMemory({
        chatHistory,
        memoryKey: "chat_history",
        inputKey: "question",
    });
    
    const model = new ChatOpenAI({
        openAIApiKey: '<API KEY>'
    });

    const chain = ConversationalRetrievalQAChain.fromLLM(
        model,
        vectorStore.asRetriever(),
        {
            memory: memory
        }
    );

    const res1 = await chain.call({ question: "Hello, my name is John", chat_history: chatHistory });

    console.log({ res1 });
    // { 
    //     res1: { 
    //         text: 'Hello John! How can I assist you today?' 
    //      } 
    // }

    const res2 = await chain.call({ question: "What's my name?", chat_history: chatHistory });

    console.log({ res2 });
    // {
    //     res2: {
    //         text: "I'm sorry, but I do not have access to personal information."
    //     }
    // }

```

**Comment by jacoblee93** [comment]
I think the bot comment is actually directionally correct (with a hallucinated class haha) - I can't be sure without seeing the error but the conversational qa chain has two outputs, so you need to specify an output key to tell the memory which one to use. Try:

```typescript
    const memory = new BufferMemory({
        chatHistory,
        memoryKey: "chat_history",
        inputKey: "question",
        outputKey: "text",
    });
```

Docs: https://js.langchain.com/docs/modules/chains/popular/chat_vector_db#built-in-memory

**Comment by Zained** [comment]
@jacoblee93 Even with your suggestion, the entry in firestore is written, but not read in the follow-up question. Basically it's not reading properly in database. It's working great with `ConversationalChain` so I guess there is something wrong here, but I don't know where to dig. I will be patient and hope for an update! Thanks anyway
