### ISSUE TITLE
Metadata is always empty when creating embeddings with Chroma

### ISSUE THREAD

**Issue by Dawsoncodes** [hwchase17/langchainjs#2256]
### Description
When retrieving data using the `similaritySearch()` method using Chroma, the metadata will not be retrieved which were provided when creating the embeddings using `fromTexts()`

### System settings
OS: Windows 10
Node: 18.16.0
langchain: ^0.0.127
chromadb: ^1.5.6

### Steps to reproduce the error

- Create embeddings using the `Chroma.fromTexts()` method
- Provide metadata
- Create another chroma instance using `Chroma.fromExistingCollection()` method
- Run the `similaritySearch()` method
- The returned results do not contain the metadata as provided in step two (it's empty)

### Code examples
Generate the embeddings:
```ts
const generateEmbeddings = async () => {
  await Chroma.fromTexts(
    ["First text", "Second text", "Third text"],
    [{ id: 1 }, { id: 2 }, { id: 3 }],
    new OpenAIEmbeddings(),
    { collectionName: "texts" }
  )

  console.log(`Embeddings generated`)
}
```

Run a query:
```ts
const query = async (query: string) => {
  const vectorstore = await Chroma.fromExistingCollection(
    new OpenAIEmbeddings(),
    { collectionName: "texts" }
  )

  const results = await vectorstore.similaritySearch(query)

  console.log(`Results for query "${query}":`)

  console.log(results)
}
```

Running a query:
```ts
query("First")
```

Result:
```js
[
  Document { pageContent: 'First text', metadata: {} },
  Document { pageContent: 'Second text', metadata: {} },
  Document { pageContent: 'Third text', metadata: {} }
]
```

### Expected behavior

```js
[
  Document { pageContent: 'First text', metadata: { id: 1 } },
  Document { pageContent: 'Second text', metadata: { id: 2 } },
  Document { pageContent: 'Third text', metadata: { id: 3 } }
]
```

**Comment by Dawsoncodes** [comment]
I found out the issue was introduced at release 0.0.125.

These [lines of code](https://github.com/hwchase17/langchainjs/compare/0.0.124...0.0.125#diff-309b567023ad2f2a276b9ff067fdbbe7083d40145b4219b8de25ed51083f2804R112-R131) might have caused the issue

**Comment by jacoblee93** [comment]
#2273 should fix this - thanks for raising the issue!
