### ISSUE TITLE
DynamicStructuredTool returning undefined

### ISSUE THREAD

**Issue by xyanglu** [hwchase17/langchainjs#2257]
`[tool/start] [1:chain:AgentExecutor > 3:tool:DynamicStructuredTool] Entering Tool run with input: "{}"
[tool/end] [1:chain:AgentExecutor > 3:tool:DynamicStructuredTool] [87ms] Exiting Tool run with output: "undefined"`

**Comment by jacoblee93** [comment]
Going to need a bit more information, but sounds like the bot response was helpful!
