### ISSUE TITLE
How to periodically update a vectorStore by appending new data without erasing the existing content?

### ISSUE THREAD

**Issue by Uno-count** [hwchase17/langchainjs#2285]
Training with large amounts of data consumes numerous tokens. But what if your data is dynamic? As data accumulates daily, there's a need to avoid retraining with both old and new data simultaneously.
 
How can we prevent retraining on both the existing and new data?

**Comment by jacoblee93** [comment]
See: https://js.langchain.com/docs/modules/data_connection/caching_embeddings
