### ISSUE TITLE
How can I query from existing collection in a PGVector?

### ISSUE THREAD

**Issue by eRuaro** [hwchase17/langchainjs#2307]
In the Python library, you can use something like this:
```
store = PGVector(
    collection_name=COLLECTION_NAME,
    connection_string=CONNECTION_STRING,
    embedding_function=embeddings,
)
```

And in the JS chroma integration, you can use this:
```
const vectorStore = await Chroma.fromExistingCollection(
  new OpenAIEmbeddings(),
  { collectionName: "godel-escher-bach" }
);
```

What's the equivalent code for PGVectors in JS? There don't seem to be any relevant / equivalent functions to Chroma's `fromExistingCollection` nor can I specify in the constructor the `collection_name`.

**Comment by jacoblee93** [comment]
Your best bet is the TypeORM vector store. 

Going to close this but if you have trouble, feel free to open another issue:

https://js.langchain.com/docs/modules/data_connection/vectorstores/integrations/typeorm

**Comment by eRuaro** [comment]
There are no methods though that let you pass in a specific `collection_name` though?
