### ISSUE TITLE
Support for chat model and response streaming with Amazon Bedrock 

### ISSUE THREAD

**Issue by Benyuel** [hwchase17/langchainjs#2321]
Expanding upon initial LLM support in https://github.com/hwchase17/langchainjs/pull/2210, langchainjs could also support streaming responses using bedrock's `/model/modelId/invoke-with-response-stream` endpoint.  This would allow implementation of a chat model and use of the callback manager.

**Comment by jacoblee93** [comment]
This would be awesome, yeah!
