### ISSUE TITLE
Cannot understand well integration guide

### ISSUE THREAD

**Issue by BitVoyagerMan** [hwchase17/langchainjs#2359]
- https://github.com/hwchase17/langchainjs/blob/main/.github/contributing/INTEGRATIONS.md 
There's this sentence:
 `Integrations tend to fall into a set number of categories, each of which will have their own section below. Please read the [general guidelines](https://github.com/hwchase17/langchainjs/blob/main/.github/contributing/INTEGRATIONS.md#general-concepts), then see the section at the end of this page specific to what you're building for additional information and examples.`
I think it's better to change it like this:
 `Integrations tend to fall into a set number of categories, each of which will have their own section below. Please read the [general guidelines](https://github.com/hwchase17/langchainjs/blob/main/.github/contributing/INTEGRATIONS.md#general-concepts), then see the section at the end of this page - Integration-specific guidelines and example PRs`

**Comment by BitVoyagerMan** [comment]
Sounds great!
Thanks.

**Comment by devstein** [comment]
@BitVoyagerMan Dosu is actually a bot and doesn't have the capability to create a PR (yet). Please make PR if you want to include this update in the documentation

**Comment by BitVoyagerMan** [comment]
Yes, will send PR. To main branch is OK?

**Comment by BitVoyagerMan** [comment]
Sent PR to main branch. waiting for the maintainer's review.

**Comment by jacoblee93** [comment]
Thank you!
