### ISSUE TITLE
Feature request: Save Documents to disk or other file store

### ISSUE THREAD

**Issue by simon-fernandes** [hwchase17/langchainjs#2366]
I have a `Document` that takes a long time to be processed by Unstructured. Once it's processed and I get a `Document` from it, I would like to be able to easily save/load this document to disk or other file store without a vector store (I don't want to split the `Document` in this use case, and the `Document` is too large to be converted to an embedding).

Is there a "Langchain" way of doing this or should I go down the route of just serializing to disk as JSON?

**Comment by jacoblee93** [comment]
I think serialization to disk is fine - we do also have the (poorly documented) concept of a Docstore, but it's only implemented for Google Cloud and in memory at the moment:

https://js.langchain.com/docs/api/stores_doc_gcs/classes/GoogleCloudStorageDocstore
