### ISSUE TITLE
[Question] Can LangChain help with aggregate queries?

### ISSUE THREAD

**Issue by ali-habibzadeh** [hwchase17/langchainjs#2384]
At things stand, it seems LangChain is powerful when you ask a question about a corpus that's converted to vectors. How can I go about creating a chain that allows me to ask questions that may not necessarily be in the body of the text upserted, but about overall / aggregate values? Such as "Rank top 10 verbs in the docs but number of frequency of usage"

**Comment by jacoblee93** [comment]
Those types of questions don't tend to fit well with vector store similarity search, but LangChain just orchestrates queries to retrievers in general, so given the right retriever yes!
