### ISSUE TITLE
Azure OpenAI Support?

### ISSUE THREAD

**Issue by HRcode** [hwchase17/langchainjs#244]
Unless I'm doing something wrong, it looks like connecting to an OpenAI model through Azure is not supported yet. I've tried to add my deployed Azure model name as a parameter called "deployment_id" (as that works in the Python version of LangChain) but I'm getting an "Incorrect API key provided" error in this version. I also tried "deploymentId", "deploymentID", and "engine" as parameter names.

Are there any plans to support Azure versions of OpenAI models?

**Comment by holwerda** [comment]
Was wondering about this too.  Started taking a look at how to extend it.

**Comment by aaronrogers** [comment]
Is it possible to create a custom LLM to pass into `LLMChain`?  If so, that'd help with this.

I opened a [question](https://github.com/hwchase17/langchainjs/discussions/286) about this and am hoping for an answer.

**Comment by nfcampos** [comment]
@aaronrogers I've now replied to you in the other thread. As for Azure OpenAI support, looks like this is an open issue on the openai-node client, see https://github.com/openai/openai-node/issues/53

**Comment by yehudacohen** [comment]
@aaronrogers did you ever build an AzureOpenAI chain? If so, are you able to share it either as a gist or npm package?

**Comment by aaronrogers** [comment]
@yehudacohen, yeah, it's a bit slapped together, but let me see what I can do.

**Comment by aaronrogers** [comment]
@yehudacohen, it's not pretty, but it works.  Your mileage may vary.
https://gist.github.com/aaronrogers/b6bb28e0e2299e5b96b168e8607a1cc2

**Comment by yehudacohen** [comment]
Thanks @aaronrogers , you're a hero!

**Comment by HRcode** [comment]
Thanks Aaron! Closing this for now. At some point it would be great for this to make it into the official langchainjs package, but I think this provides an onramp for Azure users to build a "custom" LLM for their langchain workflow.

**Comment by aaronrogers** [comment]
@HRcode, I agree, it would be nice to add.  There's also some additional work that could be done to make the process of creating custom LLMs easier.  There were a number of things I still felt like I needed to use from Langchain that weren't exposed, so I had to copy them over.

**Comment by thobhanifreddy** [comment]
Ideally, this should not be closed as it is not supported officially.
