### ISSUE TITLE
how to connect ConversationChain with BytesOutputParser

### ISSUE THREAD

**Issue by 0dd1er** [hwchase17/langchainjs#2443]
Hi,

is there a way to connect a chain with a BytesOutputParser?

If tried the following two variants

```
const outputParser = new BytesOutputParser();
const chain = new ConversationChain({llm: model, prompt:prompt, memory:memory, outputParser:outputParser}) 
const stream = await chain.stream({
    input: currentMessageContent,
});
```

```
const outputParser = new BytesOutputParser();
const c1 = new ConversationChain({llm: model, prompt:prompt, memory:memory})
const chain = c1.pipe({outputParser});
const stream = await chain.stream({
    input: currentMessageContent,
});
```

But both seem to be illegal.

BR,
0dd1er

**Comment by 0dd1er** [comment]
When connecting the conversation chain with the BytesOutputParser via pipe, it says:

Argument of type 'BytesOutputParser' is not assignable to parameter of type 'RunnableLike<ChainValues, Uint8Array>'.
  Type 'BytesOutputParser' is not assignable to type '{ [key: string]: RunnableLike<ChainValues, Uint8Array>; }'.
    Index signature for type 'string' is missing in type 'BytesOutputParser'.ts(2345)

**Comment by jacoblee93** [comment]
Hey @0dd1er, `ConversationChain` is a legacy-ish LLMChain - the proper way to do this with runnables would be something like this:

https://github.com/langchain-ai/langchain-nextjs-template/blob/main/app/api/chat/route.ts#L14

We have a fair bit of work to do updating the docs but let me know if that works for you!

**Comment by tbund** [comment]
Hi @jacoblee93,

Thanks for the quick reply!
I'm working within the starter.js framework and am curious if it's possible to stream outputs from more complex chains. 
This includes chains with memory, Retrieval QA, etc., while also using BytesOutputParser. 

Right now, it seems I'm limited to simple constructs like `const chain = prompt.pipe(model).pipe(outputParser);`.

Is there a way to convert a chain like ConversationChain into a 'runnable' object and then pipe it to a BytesOutputParser instance?

Best regards,
0dd1er

**Comment by jacoblee93** [comment]
The conversation chain is simple enough (see the above example)!

In a general sense no, but we'll be working to recreate many of those popular chains with runnables to enable this type of streaming. Here's another example with the complete convo retrieval QA chain:

https://github.com/langchain-ai/langchain-nextjs-template/blob/main/app/api/chat/retrieval/route.ts

Still figuring out the right abstractions for memory - if you're really keen on streaming with legacy chains, it's a bit more bespoke/ad-hoc (which is part of why we're switching everything to runnables):

https://js.langchain.com/docs/modules/chains/popular/chat_vector_db#streaming

**Comment by tbund** [comment]
thank you @jacoblee93 for your explainations and insights.
