### ISSUE TITLE
Error in documentation?

### ISSUE THREAD

**Issue by mrahmadt** [hwchase17/langchainjs#2446]
Hi

https://js.langchain.com/docs/get_started/quickstart
https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent

explain how to use openai-functions agent, but it seems it's not correct https://github.com/hwchase17/langchainjs/blob/main/langchain/src/agents/initialize.ts

```
type AgentType =
  | "zero-shot-react-description"
  | "chat-zero-shot-react-description"
  | "chat-conversational-react-description";

```

it's confusing for a new user to langchain, is this an error?

**Comment by jacoblee93** [comment]
Did you try it?
