### ISSUE TITLE
Is WikipediaQueryRun working properly?

### ISSUE THREAD

**Issue by gkhngyk** [hwchase17/langchainjs#2457]
Hello, I am trying to get results from wikipedia with `WikipediaQueryRun` but I am not getting any results.

Here is my code

```javascript
const { WikipediaQueryRun } = require('langchain/tools');

 const tools = [
      new Calculator(),
      new WikipediaQueryRun(),
    ];
    
      const executor = await initializeAgentExecutorWithOptions(tools, model, {
      agentType: 'chat-zero-shot-react-description',
      verbose: true,
    });
    
     const input = 'What is langchain?';
     const response = await executor.call({
        input: input,
      });

```

Here is output: 

`[chain/end] [1:chain:AgentExecutor] [10.41s] Exiting Chain run with output: {
  "output": "{\"lc\":2,\"type\":\"constructor\",\"id\":[\"langchain\",\"schema\",\"SystemMessage\"],\"kwargs\":{\"content\":\"Thought: The user is asking for information about \\\"langchain\\\" from Wikipedia. I should use the wikipedia-api tool to fetch this information.\\n\\nAction: \\n```\\n{\\n  \\\"action\\\": \\\"wikipedia-api\\\",\\n  \\\"action_input\\\": \\\"langchain\\\"\\n}\\n```\\n\",\"additional_kwargs\":{}}}"`
  
 
Is there a documentation with every use case for the Wikipedia Agent? 

Thank you

**Comment by gkhngyk** [comment]
Solved with: 

```javascript

 const executor = await initializeAgentExecutorWithOptions(tools, model, {
      agentType: 'zero-shot-react-description', // i changed to agent type and works fine 
      verbose: true,
 ```

**Comment by Boopalanoptisol** [comment]
@gkhngyk  is it possible to add memory with this agent

**Comment by gkhngyk** [comment]
> @gkhngyk is it possible to add memory with this agent

You can add memory to agent executor. 
For example: 

```
const executor = await initializeAgentExecutorWithOptions(
      tools,
      model,
     {
    agentType: 'zero-shot-react-description',
    memory: memory // <-- this is the memory you created above
     }
```

**Comment by Boopalanoptisol** [comment]
@gkhngyk  when we try to add buffermemory it shows error

**Comment by gkhngyk** [comment]
Can you try buffermemory with `agentType: 'chat-conversational-react-description'`
-> https://js.langchain.com/docs/modules/agents/agent_types/chat_conversation_agent

**Comment by Boopalanoptisol** [comment]
[llm/error] [1:chain:AgentExecutor > 4:chain:LLMChain > 5:llm:ChatOpenAI] [338ms] LLM run errored with error: "Request failed with status code 400"
[chain/error] [1:chain:AgentExecutor > 4:chain:LLMChain] [339ms] Chain run errored with error: "Request failed with status code 400"
[chain/error] [1:chain:AgentExecutor] [4.81s] Chain run errored with error: "Request failed with status code 400"
Trace: Error: Request failed with status code 400
  By using the agentType: 'chat-conversational-react-description'    getting the above error @gkhngyk
