### ISSUE TITLE
How can we add Memory to the dynamictool 

### ISSUE THREAD

**Issue by Boopalanoptisol** [hwchase17/langchainjs#2477]
import { OpenAI } from "langchain/llms/openai";
import { initializeAgentExecutorWithOptions } from "langchain/agents";
import { DynamicTool } from "langchain/tools";

export const run = async () => {
  const model = new OpenAI({ temperature: 0 });
  const tools = [
    new DynamicTool({
      name: "FOO",
      description:
        "call this to get the value of foo. input should be an empty string.",
      func: async () => "baz",
    }),
    new DynamicTool({
      name: "BAR",
      description:
        "call this to get the value of bar. input should be an empty string.",
      func: async () => "baz1",
    }),
  ];

  const executor = await initializeAgentExecutorWithOptions(tools, model, {
    agentType: "zero-shot-react-description",
  });

  console.log("Loaded agent.");

  const input = `What is the value of foo?`;

  console.log(`Executing with input "${input}"...`);

  const result = await executor.call({ input });

  console.log(`Got output ${result.output}`);
};

In the above code how can we add the memory. so that in the chatbot if human  will ask the question related to the previous question it will give the answer by analyzing the previous  humanmessages and give the response.

**Comment by Boopalanoptisol** [comment]
No overload matches this call.
  Overload 1 of 2, '(tools: StructuredTool<ZodObject<any, any, any, any, { [x: string]: any; }>>[], llm: BaseLanguageModel, options: InitializeAgentExecutorOptionsStructured): Promise<...>', gave the following error.
    Type '"zero-shot-react-description"' is not assignable to type '"structured-chat-zero-shot-react-description" | "openai-functions"'.
  Overload 2 of 2, '(tools: Tool[], llm: BaseLanguageModel, options?: InitializeAgentExecutorOptions | undefined): Promise<AgentExecutor>', gave the following error.
    Type 'BufferMemory' is not assignable to type 'undefined'.ts(2769)
initialize.d.ts(34, 5): The expected type comes from property 'agentType' which is declared here on type 'Init


When i add the above get error like i mentioned above @dosu-beta

**Comment by Boopalanoptisol** [comment]
@dosu-bot

[chain/error] [1:chain:AgentExecutor] [1ms] Chain run errored with error: "Missing value for input variable `chat_history`"
Trace: Error: Missing value for input variable `chat_history`

Getting error like this

**Comment by jacoblee93** [comment]
You'll need to use an agent specifically designed for conversation like the OpenAI functions agent:

https://js.langchain.com/docs/modules/agents/agent_types/openai_functions_agent
