### ISSUE TITLE
Even when using Azure OpenAI, if OPENAI_API_KEY does not exist, an error is output

### ISSUE THREAD

**Issue by m-hamaro** [hwchase17/langchainjs#2496]
I am using Azure OpenAI.
After upgrading to langchainjs v0.0.141, I get an error if OPENAI_API_KEY is not present, even when using Azure OpenAI

Now I work around it by writing a dummy OPENAI_API_KEY in .env.

Personally, I think the implementation of clientConfig is suspect, but due to my lack of ability, I don't know how exactly to fix it!
https://github.com/hwchase17/langchainjs/blob/d2d68958e111a0648a6581e289c3a46cd64dfb80/langchain/src/llms/openai.ts#L218

Can someone please help me?

**Comment by jacoblee93** [comment]
Ah, thank you for the report! Will look into it.

**Comment by jacoblee93** [comment]
The next version of LangChain will include a fix. Thank you again!

**Comment by jacoblee93** [comment]
This is live - please upgrade to 0.0.143. Thank you again!

**Comment by Souvikns** [comment]
I am having the same issue, and I am using `@langchain/openai`
