### ISSUE TITLE
I can only use OpenAI Embeddings 

### ISSUE THREAD

**Issue by coralexbadea** [hwchase17/langchainjs#2515]
I tried to extend the abstract Embeddings class to do my own embeddings:
```
import { Embeddings } from "../../../langchain/dist/embeddings/base";

export class CustomEmbeddings extends Embeddings {
    private generateEmbeddings;
    constructor(generateEmbeddings:any){
        super({})
        this.generateEmbeddings = generateEmbeddings
    }

    async embedDocuments(documents: string[]): Promise<number[][]> {
```
I failed due to error:
Package path ./dist/embeddings/base is not exported from package <package path>

**Comment by jacoblee93** [comment]
The base class should be exposed under `langchain/embeddings/base`.

**Comment by coralexbadea** [comment]
Yes, thank you for your answer, I installed it via npm install, I will attach an image 
![image](https://github.com/hwchase17/langchainjs/assets/36925146/b7f9a32e-b227-442b-8e5f-6fbfd1b578d8)
I tried to update the following tutorial: https://github.com/supabase-community/langchain-chatbot-demo
Can someone try to do the same, extending the Embeddings class, put it on a github repo, so I can try to reproduce it. I really really appreciate it.

**Comment by jacoblee93** [comment]
`import { Embeddings } from "langchain/embeddings/base";`
