### ISSUE TITLE
Cannot find module 'langchain/embeddings/hf_transformers' in node with version 0.0.143

### ISSUE THREAD

**Issue by helxsz** [hwchase17/langchainjs#2525]
I want to work to HuggingFace Embedding, the "langchain" is "^0.0.143" with preinstalled "@xenova/transformers": "^2.5.4".

I am trying to work with `import { HuggingFaceTransformersEmbeddings } from "langchain/embeddings/hf_transformers";`

but the node project comes with typescript compiling error :
**embedding_test.ts:1:51 - error TS2307: Cannot find module 'langchain/embeddings/hf_transformers' or its corresponding type declarations.**

so I look into the source code on the embedding and found that 

https://github.com/hwchase17/langchainjs/blob/78eccbaa446a53bb805f005b0a91eadd320caa10/langchain/src/embeddings/index.ts

```
export { OpenAIEmbeddings } from "./openai.js";
export { CohereEmbeddings } from "./cohere.js";
export { Embeddings } from "./base.js";
export { FakeEmbeddings } from "./fake.js";
```
that HuggingFaceInferenceEmbeddings is not included. is it the reason the project can't find module 'langchain/embeddings/hf_transformers'

**Comment by jacoblee93** [comment]
HFTransformers was added in 0.0.144, so you'll need to upgrade (but I think you figured that out!)

**Comment by Antonhansel** [comment]
Hello,

I've got the same issue, my langchain package version is 0.0.146

Here is a simple way to replicate this issue

```
import { HuggingFaceTransformersEmbeddings } from 'langchain/embeddings/hf_transformers';

const modelName = process.env.EMBEDDING_MODEL_NAME;

(async () => {
  console.log('Load embeddings...');
  const embeddings = new HuggingFaceTransformersEmbeddings({
    modelName: 'ggml-gpt4all-j-v1.3-groovy.bin'
  });
  console.log('Embeddings loaded!')
});
```

Here is my package.json

```
{
  "name": "node-private-gpt",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.ts",
  "scripts": {
    "start": "bun run src/index.ts",
    "dev": "bun --hot run src/index.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "chromadb": "^1.5.6",
    "langchain": "0.0.146",
    "typescript": "^5.0.0"
  },
  "devDependencies": {
    "@types/node": "^20.6.0",
    "bun-types": "latest"
  },
  "peerDependencies": {
    "typescript": "^5.0.0"
  }
}

```

And finally

```
➜  node-private git:(master) ✗ node -v 
v18.16.1
➜  node-private git:(master) ✗ npm -v 
9.5.1
```
