### ISSUE TITLE
npm install langchain@0.0.144 error

### ISSUE THREAD

**Issue by youht88** [hwchase17/langchainjs#2529]
when I install new version of langchain ,I got error like this:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: cohere-ai@6.2.2
npm ERR! node_modules/cohere-ai
npm ERR!   peerOptional cohere-ai@"^6.0.0" from chromadb@1.5.8
npm ERR!   node_modules/chromadb
npm ERR!     peerOptional chromadb@"^1.5.3" from langchain@0.0.122
npm ERR!     node_modules/langchain
npm ERR!       langchain@"0.0.122" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional cohere-ai@"^5.0.2" from langchain@0.0.122
npm ERR! node_modules/langchain
npm ERR!   langchain@"0.0.122" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/langchain/.npm/eresolve-report.txt for a full report.

**Comment by youht88** [comment]
resolved, thanks!

**Comment by nigel-daniels** [comment]
I'm still seeing this with langchain 0.0.144 and I do not have cohere-ai installed? How did you resolve this?

**Comment by nigel-daniels** [comment]
FYI I just created an empty directory and attempted to install 0.0.144 and got the above error, there is no package.lock file present. Please can you re-open this issue?

```
% mkdir foo

% cd foo 

% npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help init` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (foo) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
author: 
license: (ISC) 
About to write to /Users/nigel/git/foo/package.json:

{
  "name": "foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}


Is this OK? (yes) 

% npm install langchain
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: foo@1.0.0
npm ERR! Found: cohere-ai@6.2.2
npm ERR! node_modules/cohere-ai
npm ERR!   peerOptional cohere-ai@"^6.0.0" from chromadb@1.5.8
npm ERR!   node_modules/chromadb
npm ERR!     peerOptional chromadb@"^1.5.3" from langchain@0.0.144
npm ERR!     node_modules/langchain
npm ERR!       langchain@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peerOptional cohere-ai@"^5.0.2" from langchain@0.0.144
npm ERR! node_modules/langchain
npm ERR!   langchain@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/nigel/.npm/_logs/2023-09-06T19_45_36_643Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /Users/nigel/.npm/_logs/2023-09-06T19_45_36_643Z-debug-0.log
```

**Comment by anthonyattard** [comment]
> _🤖_
> 
> Hello,
> 
> The error you're encountering is due to a conflict between the versions of the `cohere-ai` dependency in your project. Your project seems to have `cohere-ai@6.2.2` installed, but LangChain version `0.0.122` (which seems to be installed in your project) requires `cohere-ai@^5.0.2`.
> 
> To resolve this issue, you can try the following steps:
> 
> 1. Uninstall the current version of `cohere-ai` in your project:
> 
> ```shell
> npm uninstall cohere-ai
> ```
> 
> 2. Install the version of `cohere-ai` required by LangChain `0.0.122`:
> 
> ```shell
> npm install cohere-ai@5.0.2
> ```
> 
> 3. Uninstall the current version of LangChain in your project:
> 
> ```shell
> npm uninstall langchain
> ```
> 
> 4. Install the new version of LangChain:
> 
> ```shell
> npm install langchain@0.0.144
> ```
> 
> If the issue persists, it might be due to other conflicting dependencies in your project. In this case, you might need to update your dependencies to the versions required by LangChain `0.0.144`.
> 
> Please note that the specific version requirements for the dependencies of LangChain `0.0.144` are as mentioned in the context above.
> 
> Let me know if this helps or if you need further assistance.
> 
> Best, Dosu
> 
> ## Sources
> * [package.json](https://github.com/hwchase17/langchainjs/blob/-/package.json)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

Thanks this solved the issue for me as well.
