### ISSUE TITLE
Issue importing './llms' submodule

### ISSUE THREAD

**Issue by zammitjames** [hwchase17/langchainjs#253]
I'm getting the following error when trying to run some of the examples locally.

`Error: Package subpath './llms' is not defined by "exports" in /Users/jameszammit/Github/stuff/llm/node_modules/langchain/package.json`

**Comment by zammitjames** [comment]
Ah I just realized it's due to a ESM vs CommonJS issue.

**Comment by swateek** [comment]
@zammitjames how did you resolve this issue?
