### ISSUE TITLE
Should extraction respect schema defaults?

### ISSUE THREAD

**Issue by paulguz-datapa** [hwchase17/langchainjs#2530]
I'm experimenting with using create_extraction_chain to produce an object, based on a JSON schema that is based on a C# class.  The object will then be deserialsed to an instance of that C# class.

In order for the extracted object to contain sensible defaults to allow deserialisation to succeed, I want to use the 'default' attribute in the schema.  But the outputted json does not respect these defaults.

Now, I am aware that defaults in json schemas are not intended as fallbacks to populate default values.  But the point of the extraction flow is for the LLM to read the metadata in the schema and use it to produce a precise output.  If I tell it to respect the defaults defined in the schema, it should.

I have tried with GPT-3.5-turbo and GPT-4

Here is a very simple example.  
**Schema:**

```
{
    "type": "object",
    "required": ["Guid","Forename","Age"],
    "properties": {
        "Guid": {
            "type": "string",
            "default": "00000000-0000-0000-0000-000000000000"
        },
        "Forename": {
            "type": "string"
        },
        "Age": {
            "type": "integer"
        }
    }
    
}
```

**Template:**
```You are a precise AI assistant that creates person records from text descriptions.
    Use the provided schema to produce an instance of a C# Person class from the provided description. 
    You are a tremendous stickler for sticking to every fine detail of the properties, such as defaults.
    Output just the code, no further explanations please.
    
    Hints: 
        * ALWAYS respect and include defaults values defined in the schema properties.  These are critical.  If a default is specified in the schema for a property or field, you MUST include it.
    
    Question: {question}
    Helpful Answer:
```

**Question**: Alex is 8
Output: [{'Guid': '', 'Forename': 'Alex', 'Age': 8}]

**Comment by paulguz-datapa** [comment]
@dosu-bot

I think you are confusing setting defaults in the parsed JSON schema, with using the defined defaults in the JSON schema and setting them in the JSON object that is finally output.  It is the latter I require.  

I expect the LLM to have understood the defaults from the schema and apply them to the JSON that it generates.

If schema defaults are indeed not supported in extraction, then please log this as a feature request.  Or a bug, I'm not sure.

**Comment by paulguz-datapa** [comment]
@dosu-bot

I'm not sure your answer is correct.  It appears to override _get_extraction_function to no longer do what it originally did.  And I'm not talking about inserting defaults in to the schema, but the LLM reading the defaults and inserting them in to the class output at the end of the chain.

I'm going to consider this as a feature that is not currently supported.  Can you please create a feature request for this and close this issue.

Thanks.

**Comment by jacoblee93** [comment]
This is dependent on what OpenAI returns unfortunately - seems like they don't respect that property.

As a stopgap you could have a step in code that populates empty fields with the default?

**Comment by paulguz-datapa** [comment]
@jacoblee93 Yeah, I was just trying to avoid that step.  I makes more sense to have everything defined in schema.  Thanks anyway.
