### ISSUE TITLE
Passing chat history as an array of strings is deprecated

### ISSUE THREAD

**Issue by scottklein7** [hwchase17/langchainjs#2553]
`import { OpenAI } from 'langchain/llms/openai';
import { PineconeStore } from 'langchain/vectorstores/pinecone';
import { ConversationalRetrievalQAChain } from 'langchain/chains';

const CONDENSE_PROMPT = `Given the following conversation and a follow up question, rephrase the follow up question to be a standalone question.

Chat History:
{chat_history}
Follow Up Input: {question}
Standalone question:`;

const QA_PROMPT = `QA PROMPT...

{context}

Question: {question}
Helpful answer in markdown:`;

export const makeChain = (vectorstore: PineconeStore) => {
  const model = new OpenAI({
    temperature: 1, // increase temepreature to get more creative answers
    modelName: 'gpt-3.5-turbo', //change this to gpt-4 if you have access
  });

  const chain = ConversationalRetrievalQAChain.fromLLM(
    model,
    vectorstore.asRetriever(),
    {
      qaTemplate: QA_PROMPT,
      questionGeneratorTemplate: CONDENSE_PROMPT,
      // returnSourceDocuments: true, //The number of source documents returned is 4 by default
    },
  );
  return chain;
};`

This is where I am using the makeChain 

import { NextRequest, NextResponse } from "next/server";
import { OpenAIEmbeddings } from "langchain/embeddings/openai";
import { PineconeStore } from "langchain/vectorstores/pinecone";
import { makeChain } from "@/utils/makechain";
import { pineconePromise } from "@/utils/pinecone-client";
import { PINECONE_INDEX_NAME } from "@/config/pinecone";

export async function POST(req: NextRequest, res: NextResponse) {
  const body = await req.json();
  const { question, history } = body as any;
  console.log("question", body);

  //only accept post requests
  if (req.method !== "POST") {
    return new NextResponse(JSON.stringify({ error: "Method not allowed" }), {
      status: 405,
    });
    return;
  }

  if (!question) {
    return new NextResponse(
      JSON.stringify({ error: "No question in the request" }),
      {
        status: 400,
      }
    );
  }
  // OpenAI recommends replacing newlines with spaces for best results
  const sanitizedQuestion = question.trim().replaceAll("\n", " ");

  try {
    const pinecone = await pineconePromise;
    const index = pinecone.Index(PINECONE_INDEX_NAME);

    /* create vectorstore*/
    const vectorStore = await PineconeStore.fromExistingIndex(
      new OpenAIEmbeddings({}),
      {
        pineconeIndex: index,
        textKey: "text",
        // namespace: PINECONE_NAME_SPACE, //namespace comes from your config folder
      }
    );

    //create chain
    const chain = makeChain(vectorStore);
    //Ask a question using chat history
    const response = await chain.call({
      question: sanitizedQuestion,
      chat_history: history || [],
    });

    console.log("response", response);
    return new NextResponse(JSON.stringify(response), { status: 200 });
  } catch (error: any) {
    console.log("error", error);
    return new NextResponse(
      JSON.stringify({ error: error.message || "Something went wrong" }),
      {
        status: 500,
      }
    );
  }
}

**Comment by scottklein7** [comment]
I am getting this error Passing chat history as an array of strings is deprecated, how do I fix that?

**Comment by scottklein7** [comment]
@dosu-bot?

**Comment by jacoblee93** [comment]
There should be a link in the deprecation notice as well.
