### ISSUE TITLE
withFallbacks fails with a ConversationChain

### ISSUE THREAD

**Issue by julianduque** [hwchase17/langchainjs#2559]
I'm using `withFallbacks` to use a different LLM if the main fails.

``` js
const openAi = new ChatOpenAI();
const vrtx = new ChatGoogleVertexAI();
const chat = new openAi.withFallbacks({ fallbacks: [vrtx] });
// ...

const chain = new ConversationChain({ llm: chat });
```

when running `chain.call` I'm getting the following error:

```
[17:18:56.643] ERROR (97420): this.llm.callKeys is not iterable
    err: {
      "type": "TypeError",
      "message": "this.llm.callKeys is not iterable",
      "stack":
          TypeError: this.llm.callKeys is not iterable
              at ConversationChain._selectMemoryInputs (file://...../node_modules/langchain/dist/chains/llm_chain.js:82:36)
```

Is there a way to conver that `RunnableWithFallbacks` into a `ChatLLM` model?

**Comment by jacoblee93** [comment]
`withFallbacks` is only for runnables - you can recreate the convo chain with runnables like this:

https://github.com/langchain-ai/langchain-nextjs-template/blob/main/app/api/chat/route.ts

We'll be working on making this clearer in the docs!
