### ISSUE TITLE
`handleEnd` doesn't seem to fire

### ISSUE THREAD

**Issue by rschwabco** [hwchase17/langchainjs#272]
I have a chat instance defined as follows:

```ts
const chat = new ChatOpenAI({
  streaming: true,
  callbackManager: {
    handleNewToken(token) {
      console.log(token)
    },
    handleError(error) {
      console.log("ERROR", error);                   
    },
    handleEnd(result) {
      console.log("END", result);
    }
  },
});
````

It doesn't seem like `handleEnd` is actually called when the stream ends.

**Comment by jacobrosenthal** [comment]
I noticed this myself. Doesnt look like its hooked up for the new chat model
https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chat_models/base.ts
vs old
https://github.com/hwchase17/langchainjs/blob/main/langchain/src/llms/base.ts#L94

**Comment by arnaudbzn** [comment]
`BaseChatModel` overloads `BaseLLM.generate` so no calls to `handleStart`, `handleEnd` and `handleError`.
A simple solution is to call `handleStart`, `handleEnd` and `handleError` in `ChatOpenAI.completionWithRetry`.
But a cleaner solution may require a bit of refactor of `BaseChatModel` to take care of that.
It seems that caching is not supported by `BaseChatModel` for the same reason.

**Comment by nfcampos** [comment]
Hi, we released Callbacks yesterday, which resolved this issue, and added a lot more events you can subscribe to. The api changed slightly to accommodate, see below. You can use this by updating to 0.0.32
```js
import { CallbackManager } from "langchain/callbacks";

const chat = new ChatOpenAI({
  streaming: true,
  callbackManager: CallbackManager.fromHandlers({
    async handleLLMStart(llm, prompts) {
      console.log(llm, prompts);
    },
    async handleLLMNewToken(token) {
      console.log({ token });
    },
    async handleLLMEnd(output) {
      console.log(output);
    },
  }),
});
```
