### ISSUE TITLE
Tests are not passing: jsdomexception issue

### ISSUE THREAD

**Issue by lalalune** [hwchase17/langchainjs#3]
Currently the agent test is failing because of an issue with the serpapi package and jest, specifically inside of a package inside of another package (jsdom -> jsdomexceptions).

It's possible that it's a tsconfig thing but I couldn't find any information to suggest it was anything but a bad line of code or something that isn't well supported in node.

Solution ideas:
1. Write a script that edits the package to fix the error. Not great, but fast and works.

2. Switch to `serp` npm package

3. work with the developer on serpapi to get it resolved?

**Comment by sebastianquek** [comment]
See https://github.com/serpapi/serpapi-javascript/issues/10,
> I've updated serpapi to 1.1.1 which removes the production dependency on domexception. Let me know if you're still facing issues after the update. Will close this for now.
