### ISSUE TITLE
[TypeError: this.pineconeClient.upsert is not a function]

### ISSUE THREAD

**Issue by munkhorgil** [hwchase17/langchainjs#303]
Getting **this.pineconeClient.upsert is not a function** error when trying to read texts.

```
  const pineconeClient = new PineconeClient();

  await pineconeClient.init({
    environment: "environment",
    apiKey: "apiKey"
  });

  const db = await PineconeStore.fromTexts(
    texts.map((text) => text.pageContent),
    [],
    embeddings,
    {
      pineconeClient,
    }
  );
```

Packages versions
```
    "@pinecone-database/pinecone": "^0.0.10",
    "langchain": "^0.0.29",
```

**Comment by nfcampos** [comment]
Hi @munkhorgil What should be passed to `pineconeClient` is the pinecone index, ie. the return value of calling in your snippet `pineconeClient.Index("my-index")`. Will open a PR to clarify the argument name
