### ISSUE TITLE
Map reduce method of summarize chain doesn't work as expected

### ISSUE THREAD

**Issue by anthonygore** [hwchase17/langchainjs#347]
Thanks for the amazing work on this library!

How the map reduce method works in the python library is different from how it works in this library, however. I believe the python library is correct as it matches the description in the docs.

In the python library, map reduce works by:

1. Running the provided docs through a prompt to reduce them.
2. Running the reduced docs through a different prompt to combine them.

In this library, it's slightly different:

1. If the provided docs length is too large for a single prompt, they are run through the reduce prompt until their length is small enough. Otherwise, this step is skipped.
2. Either the provided docs (if previous step is skipped) or the reduced docs are run through the combining prompt.

Said another way, if your provided docs can be stuffed into a single prompt they are not run through the reducing prompt. This is fine if your reducing prompt is the same as your combining prompt (as it is by default) but otherwise it doesn't work as expected.

I believe this could be fixed by a tweak to this function:

https://github.com/hwchase17/langchainjs/blob/a4015dbab105082442273b772d9d59d1d57b241f/langchain/src/chains/combine_docs_chain.ts#L149-L185

**Comment by nfcampos** [comment]
Thanks for opening the issue, you're right, we can add a flag that forces at least one pass through the map prompt
