### ISSUE TITLE
Docs: is the SerpApi required for Langchain? Their signup process is annoying

### ISSUE THREAD

**Issue by peterpme** [hwchase17/langchainjs#37]
Hi there,

I'm running through the docs and I'm essentially stuck here: https://hwchase17.github.io/langchainjs/docs/getting-started#agents-dynamically-call-chains-based-on-user-input

This makes use of SerpApi which is great, but their signup process requires an email and phone number. For quickstart docs, I personally feel that a tool that doesn't require an API key (or at the very least extensive signup process) would be more beneficial

Thanks!

**Comment by hwchase17** [comment]
great point, we have a pretty limited selection of tools at the moment but we'll work on adding more and transition off of it

**Comment by hartator** [comment]
I am the CEO of SerpApi.

We unfortunately had to add phone verification recently. 😞 Our service was receiving too much abuse. It's not easy to balance out fast free plan creations and free plan abuse mitigation. @peterpme Do you remember why you were stuck?

**Comment by nfcampos** [comment]
We have added an alternative in #258
