### ISSUE TITLE
Error with node:fs/promise

### ISSUE THREAD

**Issue by noobmaster19** [hwchase17/langchainjs#378]
Hey guys, Im facing this error setting up langchain.

```
ERROR in node:fs/promises
Module build failed: UnhandledSchemeError: Reading from "node:fs/promises" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

The issue seems to be coming from here:

```
import {
  ChatPromptTemplate,
  HumanMessagePromptTemplate,
  SystemMessagePromptTemplate,
} from "langchain/prompts";
```
Im using webpack to bundle the application for a vscode extension, and I'm on `"langchain": "^0.0.35",`
Any idea what might be happening?

**Comment by nfcampos** [comment]
Hi

If you mark `node:fs/promises` as `external` in web pack it should work. Let me know if not

**Comment by noobmaster19** [comment]
Hi, it does not work, I have since shifted the package to be used in a nestjs based backend. Shall I close this issue?

**Comment by isaiahtaylor** [comment]
FYI it appears that Edge Runtime is not supported yet #62

**Comment by isaiahtaylor** [comment]
FYI - if you are trying to use Edge runtime because it supports streaming, you can now stream from Serverless: https://twitter.com/isaiah_p_taylor/status/1638216571507331078

**Comment by Lionardo** [comment]
@isaiahtaylor did you find a way to go around this issue?

**Comment by isaiahtaylor** [comment]
@Lionardo here's my latest on it: https://twitter.com/isaiah_p_taylor/status/1638244623364788224 basically no way currently to have both lanchain _and_ vercel streaming. Once langchain deps are rewritten to support Edge runtime then it will be possible.

**Comment by yvesloy** [comment]
I had the same issue and resolved it by adapting the config. 

```
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  webpack: (webpackConfig, { webpack }) => {
    webpackConfig.experiments = { ...webpackConfig.experiments, topLevelAwait: true };
    webpackConfig.externals["node:fs"] = "commonjs node:fs";

    webpackConfig.plugins.push(
      // Remove node: from import specifiers, because Next.js does not yet support node: scheme
      // https://github.com/vercel/next.js/issues/28774
      new webpack.NormalModuleReplacementPlugin(
        /^node:/,
        (resource) => {
          resource.request = resource.request.replace(/^node:/, '');
        },
      ),
    );

    return webpackConfig;
  }
}

module.exports = nextConfig;
```
This removes the node in the beginning and thereby resolves the issue.

**Comment by homanp** [comment]
@yvesloy do you run the streaming in route handlers or the legacy pages/api?

**Comment by l4b4r4b4b4** [comment]
I had issues with streaming as well! Updating to canary-20 or something resolved the issue! Plus @leerob from vercel posted a solution, that should work without canary, but didnt try that one.
```
import { Configuration, OpenAIApi } from 'openai';

export const runtime = 'nodejs';
// This is required to enable streaming
export const dynamic = 'force-dynamic';

export async function GET(): Promise<Response> {
  const configuration = new Configuration({
    apiKey: process.env.OPENAI_API_KEY,
  });
  const openai = new OpenAIApi(configuration);

  let responseStream = new TransformStream();
  const writer = responseStream.writable.getWriter();
  const encoder = new TextEncoder();

  writer.write(encoder.encode('Vercel is a platform for....'));

  try {
    const openaiRes = await openai.createCompletion(
      {
        model: 'text-davinci-002',
        prompt: 'Vercel is a platform for',
        max_tokens: 100,
        temperature: 0,
        stream: true,
      },
      { responseType: 'stream' }
    );

    // @ts-ignore
    openaiRes.data.on('data', async (data: Buffer) => {
      const lines = data
        .toString()
        .split('\n')
        .filter((line: string) => line.trim() !== '');
      for (const line of lines) {
        const message = line.replace(/^data: /, '');
        if (message === '[DONE]') {
          console.log('Stream completed');
          writer.close();
          return;
        }
        try {
          const parsed = JSON.parse(message);
          await writer.write(encoder.encode(`${parsed.choices[0].text}`));
        } catch (error) {
          console.error('Could not JSON parse stream message', message, error);
        }
      }
    });
  } catch (error) {
    console.error('An error occurred during OpenAI request', error);
    writer.write(encoder.encode('An error occurred during OpenAI request'));
    writer.close();
  }

  return new Response(responseStream.readable, {
    headers: {
      'Content-Type': 'text/event-stream',
      Connection: 'keep-alive',
      'Cache-Control': 'no-cache, no-transform',
    },
  });
}
```

**Comment by homanp** [comment]
> I had issues with streaming as well! Updating to canary-20 or something resolved the issue! Plus @leerob from vercel posted a solution, that should work without canary, but didnt try that one.
> 
> ```
> 
> import { Configuration, OpenAIApi } from 'openai';
> 
> 
> 
> export const runtime = 'nodejs';
> 
> // This is required to enable streaming
> 
> export const dynamic = 'force-dynamic';
> 
> 
> 
> export async function GET(): Promise<Response> {
> 
>   const configuration = new Configuration({
> 
>     apiKey: process.env.OPENAI_API_KEY,
> 
>   });
> 
>   const openai = new OpenAIApi(configuration);
> 
> 
> 
>   let responseStream = new TransformStream();
> 
>   const writer = responseStream.writable.getWriter();
> 
>   const encoder = new TextEncoder();
> 
> 
> 
>   writer.write(encoder.encode('Vercel is a platform for....'));
> 
> 
> 
>   try {
> 
>     const openaiRes = await openai.createCompletion(
> 
>       {
> 
>         model: 'text-davinci-002',
> 
>         prompt: 'Vercel is a platform for',
> 
>         max_tokens: 100,
> 
>         temperature: 0,
> 
>         stream: true,
> 
>       },
> 
>       { responseType: 'stream' }
> 
>     );
> 
> 
> 
>     // @ts-ignore
> 
>     openaiRes.data.on('data', async (data: Buffer) => {
> 
>       const lines = data
> 
>         .toString()
> 
>         .split('\n')
> 
>         .filter((line: string) => line.trim() !== '');
> 
>       for (const line of lines) {
> 
>         const message = line.replace(/^data: /, '');
> 
>         if (message === '[DONE]') {
> 
>           console.log('Stream completed');
> 
>           writer.close();
> 
>           return;
> 
>         }
> 
>         try {
> 
>           const parsed = JSON.parse(message);
> 
>           await writer.write(encoder.encode(`${parsed.choices[0].text}`));
> 
>         } catch (error) {
> 
>           console.error('Could not JSON parse stream message', message, error);
> 
>         }
> 
>       }
> 
>     });
> 
>   } catch (error) {
> 
>     console.error('An error occurred during OpenAI request', error);
> 
>     writer.write(encoder.encode('An error occurred during OpenAI request'));
> 
>     writer.close();
> 
>   }
> 
> 
> 
>   return new Response(responseStream.readable, {
> 
>     headers: {
> 
>       'Content-Type': 'text/event-stream',
> 
>       Connection: 'keep-alive',
> 
>       'Cache-Control': 'no-cache, no-transform',
> 
>     },
> 
>   });
> 
> }
> 
> ```

Did you do this in route handlers or regular pages api?

**Comment by l4b4r4b4b4** [comment]
this is the suggestion I did not try, that @leerobert VP for DX at Vercel suggested. 

My problem was, that I needed to connect to MongoDB in the same route that does the GPT-Api call, to update a users available token. This again needed full node environment. So I turned off edge runtime, which than broke streaming. 
But with canary release the example from vercel works both for route handlers and normal api routes.

But I am struggling with connecting with ChromaDB which gives me funny errors :D 
First it does not resolve the needed dependencies, than after reinstalling them it successfully connects to Chroma and stores the embeddings but still returns an error:
```
Error in /api/document/upload: TypeError: Cannot read properties of undefined (reading 'data')
    at /usr/src/app/node_modules/.pnpm/chromadb@1.3.1/node_modules/chromadb/dist/main/index.js:136:29
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   at async Collection.add (/usr/src/app/node_modules/.pnpm/chromadb@1.3.1/node_modules/chromadb/dist/main/index.js:124:26)
   at async Chroma.addVectors (webpack-internal:///(api)/./node_modules/.pnpm/langchain@0.0.48_@dqbd+tiktoken@1.0.3_chromadb@1.3.1_cohere-ai@6.2.0_d3-dsv@3.0.1_epub2@3.0.1_tnsy5tx2rwt6ouwh4fpahcqrzy/node_modules/langchain/dist/vectorstores/chroma.js:85:9)
   at async Chroma.addDocuments (webpack-internal:///(api)/./node_modules/.pnpm/langchain@0.0.48_@dqbd+tiktoken@1.0.3_chromadb@1.3.1_cohere-ai@6.2.0_d3-dsv@3.0.1_epub2@3.0.1_tnsy5tx2rwt6ouwh4fpahcqrzy/node_modules/langchain/dist/vectorstores/chroma.js:46:9)
  at async Chroma.fromDocuments (webpack-internal:///(api)/./node_modules/.pnpm/langchain@0.0.48_@dqbd+tiktoken@1.0.3_chromadb@1.3.1_cohere-ai@6.2.0_d3-dsv@3.0.1_epub2@3.0.1_tnsy5tx2rwt6ouwh4fpahcqrzy/node_modules/langchain/dist/vectorstores/chroma.js:127:9)
  at async upload (webpack-internal:///(api)/./pages/api/document/upload.ts:42:29)
  ```

**Comment by nfcampos** [comment]
Support for Browsers, Cloudflare workers, Nextjs/vercel (browser/serverless/edge), Deno, Supabase edge functions has been released, see https://blog.langchain.dev/js-envs/ for details. See the docs for install/upgrade instructions https://js.langchain.com/docs/getting-started/install including some breaking changes

Any issues let me know

**Comment by homanp** [comment]
> Support for Browsers, Cloudflare workers, Nextjs/vercel (browser/serverless/edge), Deno, Supabase edge functions has been released, see https://blog.langchain.dev/js-envs/ for details. See the docs for install/upgrade instructions https://js.langchain.com/docs/getting-started/install including some breaking changes
> 
> 
> 
> Any issues let me know

This also fixes issues with streaming in NextJS/Vercel.
