### ISSUE TITLE
How to set proxy for openai

### ISSUE THREAD

**Issue by sunlujing** [hwchase17/langchainjs#388]
1. i need to config a proxy to call the openai.
2. so where should i to config the proxy ?

**Comment by Cyansce** [comment]
same question + 1

**Comment by duanwei913** [comment]
node's native fetch api is still in experiment, which doesn't offer a way to setup proxy AFAICT

**Comment by nfcampos** [comment]
Thanks for providing the solution @yych42

**Comment by allanbritos** [comment]
> ```ts
> { basePath: 'https://proxy.your-server.com/v1' }
> ```

@yych42 , https://proxy.your-server.com/v1 refers to an internet proxy or to a reverse_proxy?

**Comment by yych42** [comment]
> ```ts
> ```ts
> { basePath: 'https://proxy.your-server.com/v1' }
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> @yych42 , https://proxy.your-server.com/v1 refers to an internet proxy or to a reverse_proxy?
> ```

sorry about the delays. its a reverse proxy.

**Comment by qingtian1771** [comment]
it seems do not work for new version now

**Comment by fancn21th** [comment]
> it seems do not work for new version now

me 2
