### ISSUE TITLE
Unable to make API call to OpenAI !! Says: Headers is not defined

### ISSUE THREAD

**Issue by rajivraghu** [hwchase17/langchainjs#473]
Not sure what I am missing ..
Pulled the latest code from GitHub .It says header not defined.. Not sure if the examples are upto date..!  Anyone else facing the same issue??

![image](https://user-images.githubusercontent.com/5885193/227784374-f5787867-fe70-4557-b827-b22be5ad91a9.png)

**Comment by hkd987** [comment]
This section of the guide will help resolve the issue for you, https://hwchase17.github.io/langchainjs/docs/install#nodejs-16

**Comment by rajivraghu** [comment]
Thanks @hkd987 . I was on Node 16. My bad.
