### ISSUE TITLE
SimpleSequentialChain

### ISSUE THREAD

**Issue by danny-waite** [hwchase17/langchainjs#475]
How to combine chains, ie. take the output of prompt A and feed it as an input into prompt B?

The python version has the following:

https://python.langchain.com/en/latest/modules/chains/generic/sequential_chains.html

Am I missing something?

**Comment by danny-waite** [comment]
hey @nfcampos I can familiarise myself with the python code and give this a shot towards the end of the week if that helps?

**Comment by nfcampos** [comment]
Yes thanks @danny-waite Any questions let me know!

**Comment by Potrock** [comment]
Happy to take this on if you don't have time @danny-waite :)

**Comment by kwkr** [comment]
Is anyone working on this @danny-waite, @nfcampos ?

**Comment by danny-waite** [comment]
Hey @kwkr I was trying to get around to it, but didn't have chance as yet, so feel free to jump on it.  I'm happy to help if necessary

**Comment by kwkr** [comment]
> Hey @kwkr I was trying to get around to it, but didn't have chance as yet, so feel free to jump on it. I'm happy to help if necessary

Thanks! I will start working on it. Could you assign it to me @nfcampos ?

**Comment by nfcampos** [comment]
@kwkr assigned, thanks!
