### ISSUE TITLE
JS docs are currently down

### ISSUE THREAD

**Issue by cj** [hwchase17/langchainjs#476]
It looks like the latest commit #421 brought down the js docs https://hwchase17.github.io/langchainjs/docs/overview/.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1819/227836751-f03fb7c5-5c73-4b61-8af7-f1885dd4b416.png">

**Comment by m0o0scar** [comment]
same here, doc search also not working

![image](https://user-images.githubusercontent.com/165961/227841807-f364a796-de34-4756-a062-16967b03f38c.png)

**Comment by nfcampos** [comment]
Hi, the new link is https://js.langchain.com/docs/ we'll update the links in a repo later today

**Comment by nfcampos** [comment]
The search should be fixed now as well
