### ISSUE TITLE
Question: Will the Refine chain be implemented in langchainjs as well?

### ISSUE THREAD

**Issue by filipeteotonio** [hwchase17/langchainjs#483]

**Comment by nfcampos** [comment]
Hi, yes we plan to do this. Also labelled this issue as a good one for someone who wants to make a contribution

**Comment by RohitMidha23** [comment]
Would like to pick this up but new to the langchain stack. Can you hep with the requirements?

**Comment by nfcampos** [comment]
Thanks for the PR!
