### ISSUE TITLE
Add a DocumentLoader for word documents

### ISSUE THREAD

**Issue by nfcampos** [hwchase17/langchainjs#499]
### Discussed in https://github.com/hwchase17/langchainjs/discussions/497

<div type='discussions-op-text'>

<sup>Originally posted by **robert-hoffmann** March 28, 2023</sup>
Would be great to be able to add word documents to the parsing capabilities, especially for stuff coming from the corporate environment

Maybe this can be of help
https://dadoverflow.com/2022/01/30/parsing-word-documents-with-python/

Thanks 👍</div>

**Comment by aptlin** [comment]
Hey @nfcampos, can I take this on?

**Comment by nfcampos** [comment]
Sure, go for it, any questions let us know

**Comment by petersolimine** [comment]
Would something like the below as a util function be too much of a hack? 😆
`
const officeScript = require('office-script');
const fs = require('fs');

async function convertWordToPDF(inputFile, outputFile) {
  try {
    // Check if the input file exists
    if (!fs.existsSync(inputFile)) {
      console.error('Input file does not exist');
      return;
    }

    // Read the input file
    const inputData = fs.readFileSync(inputFile);

    // Convert the Word document to PDF
    const pdfBuffer = await officeScript.wordToPdf(inputData);

    // Save the PDF file
    fs.writeFileSync(outputFile, pdfBuffer);

    console.log('Successfully converted Word document to PDF');
  } catch (error) {
    console.error('Error converting Word document to PDF:', error);
  }
}

// Usage example
convertWordToPDF('input.docx', 'output.pdf');
`

**Comment by aptlin** [comment]
@nfcampos added support for docx in #556. Could you please take a look when you have a chance?

@petersolimine interesting take! Your solution might be even better from the POV that we get the same number of pages as in the original document, which is not the case with `mammoth` that I use in #556.
