### ISSUE TITLE
Default verbose to true when passing in callbackManager

### ISSUE THREAD

**Issue by nfcampos** [hwchase17/langchainjs#507]
This isn't an ideal api but that's a different problem

**Comment by ruqqq** [comment]
Is there a discussion somewhere on moving it towards an ideal API?

Some issues encountered top of my mind:
1. Should execute handlers regardless of verbose flag
2. Handlers should respect verbose flag and handle accordingly
3. Chat models are currently emitting the messages as concatenated string (why?)

**Comment by agola11** [comment]
Yeah, I think the ideal api wold be to execute all handlers and use the verbose flag within the handler itself. 

@ruqqq -- we're in the middle of changing the way callbacks work to better support concurrency and solve other issues. We can group this work in with that: https://github.com/hwchase17/langchainjs/pull/381

For your third point, it might be worth introducing a separate callback for chat models if you actually want to work with the message objects
