### ISSUE TITLE
Chat Message History with memory in NextJS

### ISSUE THREAD

**Issue by truedrju** [hwchase17/langchainjs#512]
I am trying to use the Chat API to stream chat with `BufferMemory` but when adding the `MessagesPlaceHolder` i get an error "Got Unsupported Message Type"

I am calling the API like

```
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next"
import { makeChain } from "./util"

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const body = req.body

  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    // Important to set no-transform to avoid compression, which will delay
    // writing response chunks to the client.
    // See https://github.com/vercel/next.js/issues/9965
    "Cache-Control": "no-cache, no-transform",
    Connection: "keep-alive",
  })

  const sendData = (data: string) => {
    res.write(`data: ${data}\n\n`)
  }

  sendData(JSON.stringify({ data: "" }))
  const chain = makeChain((token: string) => {
    sendData(JSON.stringify({ data: token }))
  })

  

  try {
    await chain.call({
      input: body.question,
      // history: body.history
    })
  } catch (err) {
    console.error(err)
    // Ignore error
  } finally {
    sendData("[DONE]")
    res.end()
  }
}

```

My chain invocation is :

```
export const makeChain = (onTokenStream: (token: string) => void) => {
      const model = new ChatOpenAI({
        temperature: 0,
        streaming: true,
        callbackManager: CallbackManager.fromHandlers({
            async handleLLMNewToken(token: string) {
                onTokenStream(token)
            },
        }),
    })

    const chatPrompt = ChatPromptTemplate.fromPromptMessages([
        SystemMessagePromptTemplate.fromTemplate(
          systemPrompt
        ),
        new MessagesPlaceholder("history"),
        HumanMessagePromptTemplate.fromTemplate("{input}"),
      ])
      
      return new ConversationChain({
        memory: new BufferMemory({ memoryKey: "history" }),
        prompt: chatPrompt,
        llm: model,
      })
}
````

I see the error is coming up here due to the MessagesPlaceholer initializer not returning an accepted message type:
https://github.com/hwchase17/langchainjs/blob/79e01d967f813e23acc22861619784aa83fc6794/langchain/src/memory/base.ts#L37 

I am not sure what is the best way to use Langchain to expose the previous conversation history to ChatGPT.

I have also followed this example but could not get the basic example of Chat GPT returning the users name in a subsequent message to work
https://github.com/hwchase17/langchainjs/blob/main/examples/src/agents/chat_convo_with_tracing.ts

I have set `LANGCHAIN_HANDLER=langchain` in my env file

and I have tried to send the history in my `chain.call()` invocation but nothing has worked yet.

**Comment by truedrju** [comment]
Obviously (in hindsight) i had to pass the full message history into the BufferMemory.  

Make sure returnMessages flag is not set or else the prompt does not get templated correctly.  Also do not set `LANGCHAIN_HANDLER=langchain` env variable

Final code
```
function getChatMessages(history: any): BaseChatMessage[] {
  return history.reduce((accum: BaseChatMessage[], curr: string[]) => {
    if (curr[0]) accum.push(new HumanChatMessage(curr[0]))
    if (curr[1]) accum.push(new SystemChatMessage(curr[1]))
    return accum
  }, [])
}

export const makeChain = async (
  history: any,
  onTokenStream: (token: string) => void
) => {
  const model = new ChatOpenAI({
    temperature: 0,
    streaming: true,
    callbackManager: CallbackManager.fromHandlers({
      async handleLLMNewToken(token: string) {
        onTokenStream(token)
      },
    }),
  })

  const memory = new BufferMemory({
    // returnMessages: true,
    memoryKey: "history",
    inputKey: "input",
    outputKey: "output",
  })

  memory.chatHistory = new ChatMessageHistory(getChatMessages(history))

  return new ConversationChain({
    memory: memory,
    llm: model,
  })  
}
```

```
// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next"
import { makeChain } from "./chain"

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const body = req.body

  res.writeHead(200, {
    "Content-Type": "text/event-stream",
    // Important to set no-transform to avoid compression, which will delay
    // writing response chunks to the client.
    // See https://github.com/vercel/next.js/issues/9965
    "Cache-Control": "no-cache, no-transform",
    Connection: "keep-alive",
  })

  const sendData = (data: string) => {
    res.write(`data: ${data}\n\n`)
  }

  console.log("incominghistory ", body.history)

  sendData(JSON.stringify({ data: "" }))
  const chain = await makeChain(body.history, (token: string) => {
    sendData(JSON.stringify({ data: token }))
  })

  try {
    await chain.call({
      input: body.question,
      // history: body.history
    })
  } catch (err) {
    console.error(err)
    // Ignore error
  } finally {
    sendData("[DONE]")
    res.end()
  }
}

```

**Comment by homanp** [comment]
How did you import `ChatMessageHistory`?

**Comment by truedrju** [comment]
@homanp 
i think one of the latest patches moved it to export but i just grabbed it straight from node_modules as a work aroud

import { ChatMessageHistory } from "../../../node_modules/langchain/dist/memory/chat_memory"

**Comment by homanp** [comment]
@truedrju did you get streaming to work on Vercel? Or are you hosting this somewhere else?

**Comment by truedrju** [comment]
@homanp im still experimenting locally but looks like an open issue rn

**Comment by Danm72** [comment]
> @truedrju did you get streaming to work on Vercel? Or are you hosting this somewhere else?
Streaming works from Vercel

**Comment by RGDEV2022** [comment]
@truedrju  what does your history look like coming in from makeChain? I thought you could just pass in something like this:
`{input: 'user input', answer: 'ai answer'}[] `this would be serialized and then deserialized in the server.

And in your `getChatMessages` function you would split that into a `HumanChatMessage` and `SystemChatMessage`.

Is that what you are doing? 

Also in the docs it says to use 
```
  new MessagesPlaceholder("history"),
  HumanMessagePromptTemplate.fromTemplate("{input}")
```
   
   why does history not use curly braces but input does?

**Comment by truedrju** [comment]
@RGDEV2022 the way i understand it, the calls to the LLMs are pretty much stateless. we are faking state by templating out a conversation history string and sending that into OpenAI API. The History / Memory components are just lightweight wrappers to help you accomplish that

```
class ChatMessage(BaseModel):
    message: str
    type: str

    def format(self):
        if self.type == "apiMessage":
            return f"Bot: {self.message}"
        else:
            return f"Human: {self.message}"


def form_conversation(chat_messages):
    return "\n".join([msg.format() for msg in chat_messages])


```

**Comment by RGDEV2022** [comment]
@truedrju makes sense. Got it working thanks. It's a bit unstable though. Doesn't recognize the context of the previous messages about 20% of the time. 
For example if I ask Question 1, Question 2, Question 3 and reference question 2 again, it sometimes thinks I'm referring to question 1. Hard to debug because it doesn't happen all the time either.
