### ISSUE TITLE
Issue when creating a VectorDB

### ISSUE THREAD

**Issue by samuelcardillo** [hwchase17/langchainjs#52]
Hi, already flagged that (and added my solution) on Discord - but felt like having it on GitHub might be a bit more productive.

Providing documents with not enough or too much content to HSNWLib returns an error:
```
Invalid the number of k-nearest neighbors (cannot be given a value greater than `maxElements`: 3).
``` 

My current solution has been to add this condition under line 76 in hsnwlib.js :

```
if(k > this.index.getMaxElements()) k = this.index.getMaxElements();
```

Obviously, I am not proposing this workaround as a pull request as, I believe, it is not a properly adapted long-term solution.

**Comment by nfcampos** [comment]
Thanks @samuelcardillo , to confirm you did have only 3 documents in this index at this time?

**Comment by hwchase17** [comment]
i ran into a similar issue when i only had one

thats why in the tests i think i had to increase the number of docs to 5 or so

**Comment by hwchase17** [comment]
i think this is an error from inside the hsnwlib? so what @samuelcardillo proposed may make sense

**Comment by nfcampos** [comment]
yea it is inside hnswlib (or actually inside the node wrapper https://github.com/yoshoku/hnswlib-node/blob/1fc96acf2f9357b75307dd64533a4492581c5281/src/addon.cc#L624), but do we want to at least warn the user? If they have 3 docs and ask for the 20 most similar they won't ever get 20 docs, so probably warning the user that maybe this isn't quite what they meant to do might be worth it?

**Comment by hwchase17** [comment]
yeah warning but not erroring probably best
