### ISSUE TITLE
ChatOpenAI + SerpAPI + History

### ISSUE THREAD

**Issue by progrmoiz** [hwchase17/langchainjs#531]
### Discussed in https://github.com/hwchase17/langchainjs/discussions/529

<div type='discussions-op-text'>

<sup>Originally posted by **progrmoiz** March 29, 2023</sup>
I'm trying to figure out how to merge ChatGPT with Bing Search and was looking at [this example](https://js.langchain.com/docs/modules/agents/agents/examples/conversational_agent). It talks about Buffer Memory as history, but what I want is to be able to provide my own history. How can I give multiple messages as context for ChatOpenAI instead of BufferMemory and use SerpAPI as a tool? 

I also found [this guide](https://js.langchain.com/docs/getting-started/guide-chat#multiple-messages)!</div>

**Comment by titocosta** [comment]
Struggling with this as well as of now. Should be something like this:
```
 const history = new ChatMessageHistory(previousMessages);
 const memory = new BufferWindowMemory({ chatHistory: history, returnMessages: true, k: 10 });
```
Notice that `ChatMessageHistory` is not exported yet on the NPM package, so need to use github clone.
