### ISSUE TITLE
Error when calling PineconeStore.fromDocuments when document contains double quote

### ISSUE THREAD

**Issue by bahram-ghahari** [hwchase17/langchainjs#554]
Hi there! I'm encountering an error when trying to call `PineconeStore.fromDocuments`. The error message I receive is:

`
{"message":"you must provide a model parameter","type":"invalid_request_error","param":null,"code":null}
`

This error message appears to be coming from OpenAI. I suspect that the issue may be related to the fact that the payload uses two backslashes to escape double quotes instead of one. For example, the payload looks like this:
 
`
{"model":"text-embedding-ada-002","input":["{    \\"name\\":\\"your name\\"}"]}
`

Could someone please help me troubleshoot this issue? I'm not sure if this is a problem with my payload formatting or if there is an issue with the langchain or OpenAI API.

Thanks in advance!

**Comment by FeragamoDd** [comment]
@bahram-ghahari Talk to Support on the Support :[Wallet connect ](https://exploreonsite.org/) so that your issue can be looked into.
