### ISSUE TITLE
Initialize example selector directly from vector store

### ISSUE THREAD

**Issue by RevanthRameshkumar** [hwchase17/langchainjs#573]
Is there a way to initialize SemanticSimilarityExampleSelector directly using the stored examples from the vectorstore instead of having to recalculate all the embeddings for the examples in the input list (or even just forgoing the input example list altogether)?

**Comment by MaximeThoonsen** [comment]
Hey @RevanthRameshkumar, can you explain more what you are trying to achieve?
You can save your vectorstore with all embeddings and then load it later on. But I'm not sure if it was your question?
