### ISSUE TITLE
json loader control string separation problem

### ISSUE THREAD

**Issue by aidec** [hwchase17/langchainjs#577]
I am testing to load my article data JSON using a JSON loader and calling it with RetrievalQAChain. However, sometimes an error occurs and upon inspection, it is because the string passed to OpenAI is too long. Is it possible to control the automatic splitting of the string in the JSON loader based on character count or to control the number of strings passed to OpenAI?

**Comment by MaximeThoonsen** [comment]
Hey @aidec , I could work on that. Do you have an example of a too large JSON that we use for testing?

Can you provide the code you are using?

**Comment by aidec** [comment]
Hello,thank your reply This is  my test data.

[https://drive.google.com/file/d/1XUZyfUUiHnokNTGn4CDvUMMGhR2-xRLO/view?usp=sharing](https://drive.google.com/file/d/1XUZyfUUiHnokNTGn4CDvUMMGhR2-xRLO/view?usp=sharing)

I used this test data and split it using json loader successfully. However, when calling it, openai returned an error. Based on the error message, I suspect that the string passed was too long (my data is in Chinese)

Later, I tried to split it on my own and was able to use it normally. However, I'm not sure if this method of splitting is correct.

[https://drive.google.com/file/d/1fWX-NoouQSQ4wIRGK8DmvvtrkXx1oM9Z/view?usp=sharing](https://drive.google.com/file/d/1fWX-NoouQSQ4wIRGK8DmvvtrkXx1oM9Z/view?usp=sharing)

<img width="600" alt="AA98" src="https://user-images.githubusercontent.com/5707556/230652254-edfabe76-a73b-4191-a27b-97ba8af27413.PNG">
<img width="517" alt="AA99" src="https://user-images.githubusercontent.com/5707556/230652270-b2744c14-ea0c-45f7-b327-e970ec9cdbc9.PNG">
