### ISSUE TITLE
Implement callbackManager for Embeddings

### ISSUE THREAD

**Issue by loui7** [hwchase17/langchainjs#586]
Description:
LangChain provides a callback system that allows you to hook into the various stages of your LLM application. This is useful for logging, [monitoring](https://js.langchain.com/docs/production/tracing), [streaming](https://js.langchain.com/docs/modules/models/llms/additional_functionality#streaming-responses), and other tasks. It's currently implemented in a number of LangchainJS components, but not embeddings.

To improve observability when using the embeddings SDK it would be good to implement the same functionality there.

**Comment by agola11** [comment]
Thanks, we've been thinking about this too! Will add to my queue
