### ISSUE TITLE
Feature request: Customizable document retrieval parameters (k and score threshold) for Index-related chains with VectorStore integration

### ISSUE THREAD

**Issue by alberduris** [hwchase17/langchainjs#591]
**Is your feature request related to a problem? Please describe.**

I am working with Index-related chains, such as `loadQAStuffChain`, and I want to have more control over the documents retrieved from a `VectorStore`. Specifically, I want to be able to set the "k" parameter (number of retrieved documents) or even a score threshold for the retrieved documents.

**Describe the solution you'd like**

I would like to see an option to pass a custom "k" parameter or a score threshold when using Index-related chains, such as `loadQAStuffChain`, `loadQAChain`, and `loadQAMapReduceChain`. This would allow users to have more control over the documents retrieved from the `VectorStore` and how they interact with the language model.

For example:

```typescript
const stuffQAChain = loadQAStuffChain(llm, { k: 10, scoreThreshold: 0.5 });
```

**Comment by mayt** [comment]
I implemented a similar feature here.
https://github.com/hwchase17/langchainjs/pull/827

**Comment by mayt** [comment]
Please feel free to close it!
