### ISSUE TITLE
PDFLoader not working

### ISSUE THREAD

**Issue by neebdev** [hwchase17/langchainjs#615]
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "UnknownErrorException: The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `Path2D` and/or `ReadableStream`); please use a `legacy`-build instead.".] {    
  code: 'ERR_UNHANDLED_REJECTION'
}
Usage:
import { PDFLoader } from "langchain/document_loaders";
export const run = async () => {
  const loader = new PDFLoader("src/sample.pdf");
  const docs = await loader.load();
  console.log(docs);
};
run();

**Comment by neebdev** [comment]
solved by changing `const { default: mod } = await import("pdfjs-dist");` to `const { default: mod } = await import("pdfjs-dist/legacy/build/pdf.js");` in document_loaders/pdf.js.

**Comment by nfcampos** [comment]
@neebdev hi, which environment are you running this on? Node? if so, which version

**Comment by neebdev** [comment]
Node v18.12.1

**Comment by felipetodev** [comment]
same error with `node@18.15.0` / `langchain@0.0.48` / `pdfjs-dist@3.5.141`

**Comment by nfcampos** [comment]
I've opened a PR that will let you customise which build of pdfjs is used, see https://github.com/hwchase17/langchainjs/pull/622

**Comment by Hormold** [comment]
Same problem on node 18.4, macos darwin

**Comment by magick93** [comment]
I'm still getting this error on node v18.14.2 on Ubuntu 22.10
