### ISSUE TITLE
Error: Package subpath './llms' is not defined by "exports"

### ISSUE THREAD

**Issue by benaichouchemm** [hwchase17/langchainjs#624]
We are trying to integrate langchain in a simple NestJs app, but we are getting this error:
`Error: Package subpath './llms' is not defined by "exports" in /Users/.../node_modules/langchain/package.json at new NodeError (node:internal/errors:387:5) at throwExportsNotFound (node:internal/modules/esm/resolve:365:9) at packageExportsResolve (node:internal/modules/esm/resolve:589:7) at resolveExports (node:internal/modules/cjs/loader:522:36) at Function.Module._findPath (node:internal/modules/cjs/loader:562:31) at Function.Module._resolveFilename (node:internal/modules/cjs/loader:971:27) at Function.Module._load (node:internal/modules/cjs/loader:833:27) at Module.require (node:internal/modules/cjs/loader:1057:19) at require (node:internal/modules/cjs/helpers:103:18)`

> We are using langchain 0.0.33

Any ideas what settings we are missing?

**Comment by birla** [comment]
My team is also facing the same issue. Using version 0.0.47 and 0.0.48, in Node 16 (common JS).

**Comment by beytarovski** [comment]
Just add `"type": "module"` to your **package.json**. Something like that:

````
{
  "type": "module",
  "name": "my-app",
  ...
}
````

**Comment by nfcampos** [comment]
Hi, we've released a new version 0.0.49 which adds a CJS build and fixes this issue.
