### ISSUE TITLE
Can make a call to the model because: ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by mbukeRepo** [hwchase17/langchainjs#625]
Hello I'm facing an issue trying to use the new version of langchain. 

Error message: ReferenceError: Headers is not defined
Node.js version: v16.17.0
Os version: Ubuntu 22.04.2 LTS

![Screenshot from 2023-04-05 10-54-04](https://user-images.githubusercontent.com/70356088/230032208-d6cc329c-f6b9-43d1-9e88-fc981e8d7d41.png)

**Comment by mbukeRepo** [comment]
The error is fixed after upgrading from v16 to v18

**Comment by nfcampos** [comment]
Hi, yes upgrading to Node 18 fixes that issue, see also this section in the docs https://js.langchain.com/docs/getting-started/install#unsupported-nodejs-16

**Comment by mbukeRepo** [comment]
Thank you @nfcampos for the feedback :+1: .
Actually for the package to work in node 16, I imported `Headers`, `Request` and `fetch` from `node-fetch` from 
`dist/util/axios-fetch-adapter.js`

`import fetch, {Headers, Request} from "node-fetch"; `

**Comment by mbukeRepo** [comment]
May be should be included in the docs
