### ISSUE TITLE
TensorHubEmbeddings import error

### ISSUE THREAD

**Issue by ElbekJK** [hwchase17/langchainjs#629]
Hi, I am having this error even though it exists according to the website: 
`import { TensorflowHubEmbeddings } from 'langchain/embeddings';
         ^

SyntaxError: The requested module 'langchain/embeddings' does not provide an export named 'TensorflowHubEmbeddings'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)  
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)      

Node.js v18.14.2`

**Comment by nfcampos** [comment]
Hi, in JS we don't yet have a Tensorflow Hub integration, see the ones available here https://js.langchain.com/docs/modules/models/embeddings/integrations

I think you might have seen that in the python docs?
