### ISSUE TITLE
Error initializing the application: TypeError: Cannot read properties of undefined (reading 'index')

### ISSUE THREAD

**Issue by hvardhan878** [hwchase17/langchainjs#631]
`import { Chroma } from 'langchain/vectorstores';
import { OpenAIEmbeddings } from "langchain/embeddings";

import { CharacterTextSplitter } from 'langchain/text_splitter';
import { DirectoryLoader, PDFLoader } from 'langchain/document_loaders';
import { RetrievalQAChain } from 'langchain/chains';
import { OpenAI } from "langchain/llms";
import pdfjsLib from "pdfjs-dist-legacy";

pdfjsLib.GlobalWorkerOptions.workerSrc = "pdf.worker.js";
const model = new OpenAI();

async function main() {
  

  const loader = new DirectoryLoader(
    "data",
    {
      ".pdf": (path) => new PDFLoader(path, {pdfjsLib}),

    }
  );

  const documents = await loader.load();

  const textSplitter = new CharacterTextSplitter({ chunkSize: 1000, chunkOverlap: 0 });
  const texts = await textSplitter.splitDocuments(documents);

  const embeddings = new OpenAIEmbeddings();
  const docsearch = await Chroma.fromDocuments(texts, embeddings);

  

  const qa = RetrievalQAChain.fromChainType({
    llm: model,
    chainType: 'stuff',
    retriever: docsearch.asRetriever({ searchKwargs: { k: 1 } }),
  });

  return qa;
}

export default main;
`

I am getting the error for Chroma running this in node.js

**Comment by nfcampos** [comment]
Hi, can you share the full error you're getting?
