### ISSUE TITLE
Installation of 0.0.49 on next.js 13 requires installing all type of dependencies and issue 602 does not help

### ISSUE THREAD

**Issue by rodrigorivera** [hwchase17/langchainjs#656]
Hi everyone,

I spent today over ten hours trying to make langchain.js work on my project both with versions 0.0.48 and the latest 0.0.49 from today.
So far, I have not had any success.

I am using Next.js v13.2.4 with Node v19.4. 

I install langchain with 
`npm i langchain`

My tsconfig.json looks like this
```json
{
    "extends": "tsconfig/nextjs.json",
    "include": ["next-env.d.ts", "src/**/*.ts", "src/**/*.tsx"],
    "exclude": ["node_modules"],
    "compilerOptions": {
        "baseUrl": ".",
        "paths": {
            "@app/*": ["./src/*"],
            "@public/*": ["./public/*"]
        },
        "skipLibCheck": true
    }
}
```

and my next.config.js has as webpack
```javascript
webpack(config) {
                config.module.rules.push({
                    test: /\.svg$/,
                    use: ['@svgr/webpack'],
                });
                return config;
            },
```

I am running the examples from the documentation. As a result, I am importing the following:
```typescript
import { OpenAI } from "langchain/llms";
import { PromptTemplate } from "langchain/prompts";
import { LLMChain } from "langchain/chains";
```

This triggers the following error:
`Module not found: Can't resolve '@dqbd/tiktoken'`

I started installing all the missing dependencies, but this had multiple negative results:

- My project had many libraries that I did not need
- I would also need React Native, as part of `react-native-sqlite-storage`
- I would need to modify my next.config.js extensively

After significant browsing and fiddling around, I ended up with these settings for webpack:
```javascript
webpack: (config, { webpack }) => {
        config.experiments = { ...config.experiments, topLevelAwait: true };
        config.externals['node:fs'] = 'commonjs node:fs';
        config.externals = {
            typeorm: 'typeorm',
            'react-native-sqlite-storage': 'react-native-sqlite-storage',
            replicate: 'replicate',
            // add others here
        };
        config.experiments = {
            asyncWebAssembly: true,
            layers: true,
        };
        config.resolve.fallback = {
            ...config.resolve.fallback, // if you miss it, all the other options in fallback, specified
            // by next.js will be dropped. Doesn't make much sense, but how it is
            fs: false,
        };
        config.plugins.push(
            // Remove node: from import specifiers, because Next.js does not yet support node: scheme
            // https://github.com/vercel/next.js/issues/28774
            new webpack.NormalModuleReplacementPlugin(/^node:/, (resource) => {
                resource.request = resource.request.replace(/^node:/, '');
            })
        );
```

All this would still be ok, if my project were to run, but I started to have errors such as:
` TypeError: Cannot read properties of null (reading 'useEffect')`

or
```
../../node_modules/react-native/index.js
Module parse failed: Unexpected token (14:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| // Components
> import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
| import typeof ActivityIndicator from './Libraries/Components/ActivityIndicator/ActivityIndicator';
| import typeof Button from './Libraries/Components/Button';
```

I removed all libraries related to langchain and decided to start fresh with the latest version 0.0.49 which just came out, but nothing has changed. It still throws as an error:
```
error - ../../node_modules/langchain/dist/base_language/count_tokens.js:47:41
Module not found: Can't resolve '@dqbd/tiktoken'
```

As you can see from my configuration file, I checked [Issue 602](https://github.com/nfcampos/langchain-issue-602) and added `"skipLibCheck": true`.

I checked most of the threads here from those having problems and could not find a solution.

Currently, I am not interested in using Cohere-AI, HuggingFace, Replicate or any ORM or SQLite. I am also unsure if I need Tiktoken. I only want to start with standard examples using the OpenAI implementation.

Am I overlooking something? Can you please point me in the right direction to get it running?

**Comment by LarchLiu** [comment]
- Install all the dependencies of langchain
- DO NOT use edge runtime at server side

Good luck.

**Comment by rodolphoasb** [comment]
As a workaround, you can't have `appDir: true` in your next.config. If you remove it, it should be fine!

**Comment by toonverbeek** [comment]
Running into the same issue. I need `appDir` because as far as I know the only way to support streaming in NextJS is using the new Route handlers in v13, which requires `appDir` to be enabled.

**Comment by nfcampos** [comment]
Support for Browsers, Cloudflare workers, Nextjs/vercel (browser/serverless/edge), Deno, Supabase edge functions has been released, see https://blog.langchain.dev/js-envs/ for details. See the docs for install/upgrade instructions https://js.langchain.com/docs/getting-started/install including some breaking changes

Any issues let me know
