### ISSUE TITLE
add easy way to run all examples

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchainjs#67]

**Comment by hwchase17** [comment]
all of them, a bit like a test

maybe the answer is they should just be tests?

**Comment by nfcampos** [comment]
yea then they should be tests instead, inside the langchain folder. I had thought the examples were to serve the same purpose as the python notebooks

**Comment by sullivan-sean** [comment]
Tests makes the most sense here, a lot of examples cannot be run without API keys - I imagine in most cases people are only concerned with running a few of the examples, e.g. that they have keys for
