### ISSUE TITLE
Feature request: Cheerio selector

### ISSUE THREAD

**Issue by magick93** [hwchase17/langchainjs#704]
Currently the Cheerio doc loader is hardcoded to get the entire page, using `$("body")`. However typically there is a main content area, which is important, and surrounding elements which are not.

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/document_loaders/cheerio_web_base.ts#L50-L55
```
  async load(): Promise<Document[]> {
    const $ = await this.scrape();
    const text = $("body").text();
    const metadata = { source: this.webPath };
    return [new Document({ pageContent: text, metadata })];
  }
```

It would be good if it were possible to pass in an option jquery style selector to target the exact content.

**Comment by nfcampos** [comment]
I agree, this would be great!

**Comment by magick93** [comment]
PR for this at https://github.com/hwchase17/langchainjs/pull/728

**Comment by 0swin** [comment]
On my current project, i am using [@mozilla/readability](https://github.com/mozilla/readability) to get the main content of the web page, trimming out the html tags, however this doesnt work for every website, and for some articles, Readability outputs only the first half of paragraphs

**Comment by sagar-jani** [comment]
I see this PR is merged, should issue should be closed ?

**Comment by magick93** [comment]
Yes, thanks.
