### ISSUE TITLE
Supabase Vector Store Problems

### ISSUE THREAD

**Issue by henriette-einstein** [hwchase17/langchainjs#706]
I have problems using Supabase as a Vectorstore. I have a textfile containing a speech of the German Chancellor Scholz as a testdocument. This speech is about the war in the Ukraine and of course contains the word "Ukraine" multiple times. I setup Supabase as described in the documentation (https://js.langchain.com/docs/modules/indexes/vector_stores/integrations/supabase)

I first generated the vectorstore using the fromDocuments()-method.

I then created a chain and queried "Was sagt Scholz zur Ukraine" (in english: what does Scholz tell about the Ukraine), I get the answer "I don't know". When I asked him "Was sagt Scholz zur Zeitenwende" (the speech is called Zeitenwende-speech and the word is used in the text too) the query returned a completelly wrong text.

I have then enhanced the testscripts to use chroma and hnswlib. When using these stores, I get a different, but correct results for both questions described above.

I know, that the results may differ between stores, but Supabase failed to answer many questions where the other stores worked just fine.

I attach the testdocument and my testscripts so that you can reproduce the problem

[Regierungserklärung von Bundeskanzler Olaf Scholz am 27. Februar 2022.md](https://github.com/hwchase17/langchainjs/files/11189736/Regierungserklarung.von.Bundeskanzler.Olaf.Scholz.am.27.Februar.2022.md)
[scripts.zip](https://github.com/hwchase17/langchainjs/files/11189739/scripts.zip)
[package.json.zip](https://github.com/hwchase17/langchainjs/files/11189742/package.json.zip)

**Comment by nfcampos** [comment]
@henriette-einstein I wonder if it's an issue with the index, try dropping and recreating
```sql
drop index documents_embedding_idx;

create index on documents
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);
```
and then try the query again afterwards

**Comment by henriette-einstein** [comment]
That worked! But as far as I can see, this statement is equal to the last statement you have in the documentation. Does that mean, that I always have to recreate the index after adding a new Document to the index?

**Comment by nfcampos** [comment]
@henriette-einstein some more info form supabase on this
> Re-indexing should only be needed if the distribution of data changes significantly. pgvector uses IVFFlat (Inverted File) indexes which come with a few nuances:
> - The index enables an approximate nearest neighbour search (since exact search on high dimensional data can't be indexed efficiently). This means that query results on the same data will actually change after you add an index (trading recall for speed).
> - pgvector recommends adding indexes only after the table has sufficient data, so that the internal IVFFlat cell clusters are based on your data's distribution. Anytime the distribution changes significantly, indexes should probably be recreated.
> - When you create the index, you choose the number of inverted lists (cell clusters). Increase this number to speed up queries, but at the expense of recall.
> - Every query you can set the number of probes (1 by default), which is referring to the number of nearby cells to probe for a match. Increase this for better recall at the expense of speed.
> Some good references I've found are:
> - pgvector has some documentation on their indexing: https://github.com/pgvector/pgvector#indexing
> - Facebook Research's Faiss library discusses IVF: https://github.com/facebookresearch/faiss/wiki/Faiss-indexes#cell-probe-methods-indexivf-indexes
> - James Briggs has a good video on indexes and has a section on IVF: https://www.youtube.com/watch?v=B7wmo_NImgM&t=1360s
