### ISSUE TITLE
`pdfjs` requires `canvas` which doesn't run on ARM

### ISSUE THREAD

**Issue by Heilemann** [hwchase17/langchainjs#709]
Trying to load a PDF using PDFLoader fails on eg. a MacBook Pro M1 Pro because `pdfjs` requires the `canvas` package to run on `nodejs`, but [the `canvas` package doesn't support ARM processors](https://github.com/Automattic/node-canvas/issues/1511).

See also [this issue](https://github.com/Automattic/node-canvas/issues/2220).

**Comment by nfcampos** [comment]
Added info to the docs on how to fix it in #632

**Comment by Heilemann** [comment]
Thanks for the help!
