### ISSUE TITLE
Suggestion: adding document size & ignorelist options for GithubRepoLoader

### ISSUE THREAD

**Issue by Kureev** [hwchase17/langchainjs#722]
The problem: sometimes, files in the repo might exceed recommended token size, meaning that vector databases like Pinecone won't be able to process such documents. 

In ideal world, I'd imagine a new configuration option to be:

```ts
const loader = new GithubRepoLoader(repositoryUrl, {
        accessToken: process.env.GITHUB_ACCESS_TOKEN,
        branch: 'main',
        recursive: true,
        unknown: 'warn',
});

const docs = loader.load({
        chunkSize: 7,
        chunkOverlap: 3,
});
```

Going further, it might be beneficial to exclude not only the binary files, but allow provide developer control over the ignorelist. Something like this:

```ts
const loader = new GithubRepoLoader(repositoryUrl, {
        accessToken: process.env.GITHUB_ACCESS_TOKEN,
        branch: 'main',
        recursive: true,
        unknown: 'warn',
        ignorelist: ['.*', 'dist/*'], // string[] patterns to ignore
});
```

I'd love to implement something like this if you consider such contribution. Just let me know and I'll compose a PR in no time.

**Comment by mengjian-github** [comment]
There is a common demand where reaching the rate limit of the GitHub API is easy without a token. Additionally, I tried passing in "https://github.com/hwchase17/langchainjs" and found that there was no response for a long time, and eventually, no document was generated.

**Comment by Kureev** [comment]
Yeah, I immediately faced the first issue with the token, but for my purpose I see no issue to provide it with one. As for the second one, it might be related to the quota issue with many requests without proper authentication 🤔

**Comment by tonisives** [comment]
I created a [PR](https://github.com/hwchase17/langchainjs/pull/1177) that accepts .gitignore file lines

**Comment by Kureev** [comment]
Seems #1177 has landed, so I'm closing this issue
