### ISSUE TITLE
Cache not working as expected when using ChatOpenAI and ConversationChain

### ISSUE THREAD

**Issue by milanjain2208** [hwchase17/langchainjs#724]
I am using the ChatOpenAI model along with the ConversationChain from the LangChain library, and I am trying to enable caching to reduce API calls and token usage. I've set the `cache` option to `true` while instantiating the ChatOpenAI model. However, when I call the same question multiple times, the token usage keeps increasing, indicating that the cache is not working as intended.

Here's a shortened version of my code, demonstrating the issue:

```
import { ChatOpenAI } from "langchain/chat_models";
import { ConversationChain } from "langchain/chains";
import { ChatPromptTemplate, MessagesPlaceholder, SystemMessagePromptTemplate, HumanMessagePromptTemplate } from "langchain/prompts";
import { BufferMemory } from "langchain/memory";
import { CallbackManager } from "langchain/callbacks";

const chat = new ChatOpenAI({
  temperature: 0,
  cache: true,
  openAIApiKey: process.env.OPENAI_API_KEY,
  streaming: false,
  callbackManager: CallbackManager.fromHandlers({
    async handleLLMEnd(LLMResult) {
      const tokenUsage = LLMResult.llmOutput.tokenUsage;
      console.log(`Total Tokens Used: ${tokenUsage.totalTokens}, Completion Tokens: ${tokenUsage.completionTokens}, Prompt Tokens: ${tokenUsage.promptTokens}`);
    }
  }),
});

const systemMessage = "You are a helpful assistant";
const prompt = ChatPromptTemplate.fromPromptMessages([
  SystemMessagePromptTemplate.fromTemplate(`${systemMessage}`),
  new MessagesPlaceholder("history"),
  HumanMessagePromptTemplate.fromTemplate("{text}"),
]);

const chain = new ConversationChain({
  prompt: prompt,
  llm: chat,
  memory: new BufferMemory({ returnMessages: true, memoryKey: "history" })
});

async function testCache() {
    console.log("Started")
  const userQuery = "What is a GPT";
  await chain.call({ text: userQuery });
  await chain.call({ text: userQuery });
  await chain.call({ text: userQuery });
}

testCache();

```

When running the testCache function, I observed the following output:
```
Total Tokens Used: 112, Completion Tokens: 89, Prompt Tokens: 23
Total Tokens Used: 216, Completion Tokens: 89, Prompt Tokens: 127
Total Tokens Used: 320, Completion Tokens: 89, Prompt Tokens: 231
```

This indicates that the cache is not working as expected, since the token usage keeps increasing for the same query.

I would greatly appreciate any assistance or guidance you can provide regarding this issue.

**Comment by jevadebe** [comment]
This is expected behaviour. When calling chain.call again, there`s a new message being added to the history which will be send through as history for the next call (and so the call is different and not being cached). The total tokens used in the output is also a pointer to this. It`s increasing by the same amount for every step and showing the tokens used for that call, not the total usage. Try creating a new chain (with the same Chat instance) and then it should cache properly.
