### ISSUE TITLE
Summarization chain

### ISSUE THREAD

**Issue by juzarantri** [hwchase17/langchainjs#737]
Using this chain takes lots of time for generating out put i.e., summary

Here is the reference which I used
https://js.langchain.com/docs/modules/chains/other_chains/summarization

**Comment by arronKler** [comment]
try this `const chain = loadSummarizationChain(model, { type: 'stuff' });` if your content is not too long

**Comment by juzarantri** [comment]
Thanks @arronKler  for this but what to do if the content is long like 6000 words

**Comment by juzarantri** [comment]
Thanks for your contribution

**Comment by arronKler** [comment]
> @arronKler Do you know how can i see the intermediate steps using Langchain JS as I'm not sure my prompt is being applied? I think the [default prompt](https://github.com/hwchase17/langchainjs/blob/ca9cdee709cf421e17fb3db797db8c69c13ed67f/langchain/src/chains/summarization/stuff_prompts.ts) is always applied for some reason.

you may need this

https://js.langchain.com/docs/production/tracing
