### ISSUE TITLE
Missing tools in version 0.0.52

### ISSUE THREAD

**Issue by elier** [hwchase17/langchainjs#740]
Error using SearAPI tool:
```
import { Calculator } from "langchain/tools/calculator";
import { SerpAPI } from "langchain/tools/serpapi";
```

Error:   
Cannot find module 'langchain/tools/serpapi' or its corresponding type declarations.ts

Details:  
After npm install, inside node_modules/langchain/tools/, I only see the calculator module.

**Comment by arronKler** [comment]
try `import { SerpAPI } from 'langchain/tools'`
