### ISSUE TITLE
Support for Amazon Bedrock

### ISSUE THREAD

**Issue by mats16** [hwchase17/langchainjs#775]
Hello,

I would like to request the addition of support for Amazon Bedrock to the Langchain library. As Amazon Bedrock is a new service, it would be beneficial for Langchain to include it as a supported platform.

2023-04-13 Amazon announced the new service [Amazon Bedrock](https://aws.amazon.com/bedrock/).
Blog: https://aws.amazon.com/blogs/machine-learning/announcing-new-tools-for-building-with-generative-ai-on-aws/

Issue of the python library: https://github.com/hwchase17/langchain/issues/2828

**Comment by ztanruan** [comment]
Any updates on this request ?

**Comment by thehoneymad** [comment]
Hello, would be super awesome to have this one done!
