### ISSUE TITLE
JavaScript code text splitter

### ISSUE THREAD

**Issue by noghartt** [hwchase17/langchainjs#785]
What are the best ways to create a JavaScript code text splitter as the Python Text Splitter example?

Could splitter accepts RegEx? Or how we could split the scope of arrow functions and other stuffs like that?

**Comment by TimPietrusky** [comment]
Will be solved via https://github.com/hwchase17/langchainjs/pull/707

**Comment by jacoblee93** [comment]
Merged with #1469
