### ISSUE TITLE
LLMChain hard dependency on Redis, TypeORM

### ISSUE THREAD

**Issue by dkarlovi** [hwchase17/langchainjs#796]
```typescript
import { LLMChain } from "langchain/chains";
```

Causes

```
$ npx tsc

node_modules/langchain/dist/cache.d.ts:1:38 - error TS2307: Cannot find module 'redis' or its corresponding type declarations.

1 import type { RedisClientType } from "redis";
                                       ~~~~~~~

node_modules/langchain/dist/sql_db.d.ts:1:67 - error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

1 import type { DataSource as DataSourceT, DataSourceOptions } from "typeorm";
                                                                    ~~~~~~~~~

node_modules/langchain/dist/util/sql_utils.d.ts:1:52 - error TS2307: Cannot find module 'typeorm' or its corresponding type declarations.

1 import type { DataSource, DataSourceOptions } from "typeorm";
                    
```

Reproducer repo:  https://github.com/dkarlovi/langchainjs-796

**Comment by nfcampos** [comment]
Hi, that's not a dependency, as it's clearly marked, on purpose, as `import type` it doesn't actually import the code. If you disable type checking your dependencies `skipLibCheck` you wouldn't see that alert

**Comment by dkarlovi** [comment]
@nfcampos I know about skipping the lib check, but that flag feels like it's a big hammer here, no? I also lose the checks which I might want to see. 🤔

**Comment by nfcampos** [comment]
If there is a better solution I'm all for it

**Comment by dkarlovi** [comment]
@nfcampos looking at the code, it seems there's some mixing of concerns here, maybe?

If we check the offending cache.ts, it directly loads from Redis:

https://github.com/hwchase17/langchainjs/blob/6b77cbe861addc47da69cb6e25cde7f4d35fd5bb/langchain/src/cache.ts#L2

It seems this should be split to allow loading the generic cache-related types to be loaded without immediately pulling in Redis-specific types, example here:

https://github.com/hwchase17/langchainjs/blob/6b77cbe861addc47da69cb6e25cde7f4d35fd5bb/langchain/src/llms/base.ts#L1

**Comment by nfcampos** [comment]
Yes changing that would be a breaking change. I'll have to consider whether it's worth making a breaking change to appease one out of many possible typescript configurations

**Comment by dkarlovi** [comment]
@nfcampos I agree it's a BC break, but this type of bundling (specific in abstract) seems to have been undone for other modules already (OpenAI, Pinecone). IMO it's probably a good idea to solve these types of issues while the project is still very young because they'll 100% introduce issues down the line and solving them then will be quite a bit more complex, while they're constantly causing friction or issues (for example, for non-Node users).

It's up to you of course.

**Comment by nfcampos** [comment]
@dkarlovi opened a PR to do this
