### ISSUE TITLE
text.replaceAll is not a function - deploying on render

### ISSUE THREAD

**Issue by arian0zen** [hwchase17/langchainjs#810]
i am getting this error:

![image](https://user-images.githubusercontent.com/68517592/232204881-662729db-cdc2-430c-98ec-6fbaee2606fc.png)
`Apr 15 02:34:44 PM  error TypeError: text.replaceAll is not a function
Apr 15 02:34:44 PM      at OpenAIEmbeddings.embedQuery (/opt/render/project/src/backend/node_modules/langchain/dist/embeddings/openai.cjs:91:46)
Apr 15 02:34:44 PM      at PineconeStore.similaritySearch (/opt/render/project/src/backend/node_modules/langchain/dist/vectorstores/base.cjs:41:90)
Apr 15 02:34:44 PM      at qna (/opt/render/project/src/backend/controller/qnaController.js:30:41)
Apr 15 02:34:44 PM      at processTicksAndRejections (internal/process/task_queues.js:95:5)`

when deploying on render, though in localhosr or even on vercel i don't see this issues

help

**Comment by hyuraku** [comment]
The default version of Node.js on `Render` is `14.17.0`. The error occurred because the `replaceAll` method in Node.js is only available from version 15.

References:
https://node.green/
https://render.com/docs/node-version

**Comment by arian0zen** [comment]
heyyy thankk youuuu!! this information solved my issues :)
