### ISSUE TITLE
Unable to deploy supabase functions that utilize the LLMChain from langchainJS 

### ISSUE THREAD

**Issue by DitlevHB** [hwchase17/langchainjs#811]
Using the following example project:
https://github.com/langchain-ai/langchain-template-supabase/issues/7

As stated in the issue, deploying a function using supabase with the LLMChain import does not work.

I am relaying the issue here because I am not sure on what end we have a hiccup: langchainJS, or supabase.

Steps to reproduce the behavior

1. Clone https://github.com/langchain-ai/langchain-template-supabase/
2. Install dependencies
3. npx supabase start
4. npx supabase functions deploy chat

I am able to run the script directly with Deno, so it is clear that it is some incompatibility with LangChainJS and a build.ts script that Supabase uses in processing edge functions during deployment.

**Comment by nfcampos** [comment]
As answered in one of the other issues you opened for the same problem, it sounds like you need to run `yarn run supabase:deploy` instead

**Comment by DitlevHB** [comment]
Thank you it does work now, but does not explain why.
I have mentioned why it works on the other issue that I posted.
