### ISSUE TITLE
ConversationalRetrievalQAChain does not work with multilingual input.

### ISSUE THREAD

**Issue by trevorpfiz** [hwchase17/langchainjs#842]
Simply put, in ChatGPT, I type a question in Spanish and I get Spanish back. If I type another question in the same chat in French, I get French back. It will respect the language of the question.

With `ConversationalRetrievalQAChain`, I type my first question in Spanish and I get Spanish back. However, if I type a second question in Spanish, it seems that behind the scenes the question gets converted to English with a few words of added context. This will make the response come back in English, breaking multilingual/non-English conversations.

**Comment by phoenixz0024** [comment]
I seem to have the same issue
