### ISSUE TITLE
sql chain

### ISSUE THREAD

**Issue by hwchase17** [hwchase17/langchainjs#86]
equivalent of https://langchain.readthedocs.io/en/latest/modules/chains/examples/sqlite.html

a chain that generates sql code, then executes it, then summarizes responses

prereq for this is probably a sql tool + example of how to use it (separate pr)

**Comment by MaximeThoonsen** [comment]
Working on it here : https://github.com/hwchase17/langchainjs/pull/144

**Comment by nfcampos** [comment]
This is now released
