### ISSUE TITLE
Remove Axios, replace with Fetch

### ISSUE THREAD

**Issue by lalalune** [hwchase17/langchainjs#863]
Right now langchainjs is using a very old version of Axios. This requires us to npm install --legacy-peer-deps

Fetch is now supported in Node natively, which means the same interface will work on backend or frontend without the axios dependency. Since there are just a couple of uses of axios, and it will keep the project more terse, I would like to make a PR that removes the dependency on Axios and replaces it with native fetch. Can polyfill node-fetch for older clients as well.

If this is agreed to, I can make a PR and verify the tests.

**Comment by nfcampos** [comment]
We use this version because it's the same version used by openai sdk, see https://github.com/hwchase17/langchainjs/issues/816#issuecomment-1510393706 

We do try to use `fetch` where we can, you'll see we make use of it in quite a few places.

**Comment by jpamorgan** [comment]
hmmm. this is making it very hard to use with nestjs which needs `^1.35`

**Comment by nfcampos** [comment]
Well but it'd be exactly as hard to use the `openai` sdk with it, no? That sounds like an issue to pick up with `nestjs` or `openai`. If `openai` update their version of `axios` we'll happily update it here as well.

**Comment by nfcampos** [comment]
(That would be because `npm` treats peer dependency (axios is an optional peer dependency of langchain) ranges more strictly than direct dependency ranges (axios is a direct dependency of openai))

In any case I've opened PR #973 relaxing the peer dependency range for axios to make you folks happy (but I still recommend you use the axios version your dependencies (like openai) require, even if `npm` doesn't complain)

**Comment by nfcampos** [comment]
That `^1.0.0` is our dev dependency range (which doesn't affect anyone installing `langchain` from npm/yarn/etc). Our peer dependency range is now `*`. As far as I can tell both versions are compatible enough that in ours/openai's usage they can be used interchangeably

**Comment by mikkotikkanen** [comment]
Ah, right, just noticed it was under `devDependencies` 🤦‍♂️

**Comment by tecoad** [comment]
> hmmm. this is making it very hard to use with nestjs which needs `^1.35`

Same issue here. 
Did you manage to make it work with nestjs?

**Comment by nfcampos** [comment]
@tecoad the PR mentioned above was released in 0.0.64 id suggest updating
