### ISSUE TITLE
WebBrowserTool 403 error

### ISSUE THREAD

**Issue by crallan** [hwchase17/langchainjs#881]
I'm trying to use the WebBrowserTool and I got the foirbidden code (403) on some sites. I tried to add the user agent and also use proxies but I still get 403. I tried to send the headers directly on the tool contructor or the axios config.

**Example prompt**: `Try to get the pricing model from https://www.canva.com/`

```
const headers = {
  'user-agent':
    'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36',
  'upgrade-insecure-requests': '1',
  'accept':
    'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'en-US,en;q=0.9,en;q=0.8',
};

new WebBrowser({
    model,
    headers,
    embeddings,
    axiosConfig: {
      headers
    },
  })
```

**Result:**
![image](https://user-images.githubusercontent.com/19255010/232924547-e823ef1a-e892-454e-89f9-1172bbd6f088.png)

**Comment by sarfudheen** [comment]
Hello Crallan,
I saw that you closed the 403 error issue with the WebBrowserTool. Could you share what changes or configurations helped overcome this error, especially if specific headers, user-agent settings, or other techniques were key to the fix?
Thank you!
