### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hiroshinishio** [hwchase17/langchainjs#892]
This occurs when I do a GithubRepoLoader for this repository and use RecursiveCharacterTextSplitter. Is there a countermeasure?

**Comment by nfcampos** [comment]
Are you able to share a code snippet that produced this error?

**Comment by haouarihk** [comment]
it happend to me when i use RecursiveCharacterTextSplitter in the nextjs api

**Comment by jacoblee93** [comment]
Hey @hiroshinishio and @haouarihk, we just pushed a refactor of the recursive splitter - going to close for now but can you please reopen if you see this again?
