### ISSUE TITLE
All requests through langchain to OpenAI timeout

### ISSUE THREAD

**Issue by henrikix** [hwchase17/langchainjs#895]
Trying to add langchainjs to my Node.js project but whenever calling any function related to OpenAI the requests timeout.
I also downloaded the repo, configured it and ran the examples but the results were exactly the same, it just times out.

For example:
```
const model = new OpenAI({ temperature: 0.9, modelName: "gpt-3.5-turbo" , timeout: 20})
const response = await model.generate(["Tell me a joke."]);
console.log(response)
```

When directly using the OpenAI node package then it works perfectly
```
const configuration = new Configuration({
organization: orgId,
apiKey: process.env.OPENAI_API_KEY,
});
const openai = new OpenAIApi(configuration);
const response = await openai.createChatCompletion({model: 'gpt-3.5-turbo', temperature: 0, messages: [{role: 'user', content: 'hi there'}]})
console.log(response)
```

Hoping for some feedback.
Thanks!

**Comment by freddymercury** [comment]
I am observing the same, even when running the openai example in the examples directory, I am getting a 404 response:

 `yarn run start src/llms/openai.ts`

**Request**
`   data: '{"model":"gpt-4","temperature":0.7,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"max_tokens":1000,"stream":false,"messages":[{"role":"user","content":"Question: What would be a good company name a company that makes colorful socks?\\nAnswer:"}]}',
    url: 'https://api.openai.com/v1/chat/completions'
  },
` 

**Response**

` response: {
    ok: false,
    status: 404,
    statusText: 'Not Found',
    headers: {
      'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400',
      'cf-cache-status': 'DYNAMIC',
      'cf-ray': '~removed~',
      connection: 'keep-alive',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=utf-8',
      date: 'Tue, 18 Apr 2023 removed',
      server: 'cloudflare',
      'set-cookie': '00000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
      'strict-transport-security': 'max-age=15724800; includeSubDomains',
      'transfer-encoding': 'chunked',
      vary: 'Origin',
      'x-request-id': '~removed~'
    },`

**Comment by freddymercury** [comment]
also getting a 429 with this source

`const { OpenAI } = require("langchain/llms/openai");
require("dotenv").config();

const openAIApiKey = process.env.OPENAI_API_KEY;
const model = new OpenAI({ openAIApiKey, temperature: 0.9 });

const openAICall = async () => {
  const response = await model.call("who is agent smith?");
  return response;
};

(async () => {
  try {
    const response = await openAICall();
    console.log(response);
  } catch (error) {
    console.error("Error:", error);
  }
})();
`

**Comment by henrikix** [comment]
> I am observing the same, even when running the openai example in the examples directory, I am getting a 404 response:
> 
> `yarn run start src/llms/openai.ts`
> 
> **Request** ` data: '{"model":"gpt-4","temperature":0.7,"top_p":1,"frequency_penalty":0,"presence_penalty":0,"n":1,"max_tokens":1000,"stream":false,"messages":[{"role":"user","content":"Question: What would be a good company name a company that makes colorful socks?\\nAnswer:"}]}', url: 'https://api.openai.com/v1/chat/completions' },`
> 
> **Response**
> 
> ` response: { ok: false, status: 404, statusText: 'Not Found', headers: { 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400', 'cf-cache-status': 'DYNAMIC', 'cf-ray': '~removed~', connection: 'keep-alive', 'content-encoding': 'gzip', 'content-type': 'application/json; charset=utf-8', date: 'Tue, 18 Apr 2023 removed', server: 'cloudflare', 'set-cookie': '00000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None', 'strict-transport-security': 'max-age=15724800; includeSubDomains', 'transfer-encoding': 'chunked', vary: 'Origin', 'x-request-id': '~removed~' },`

In your case perhaps the issue might be that you should change examples to use `modelName: "gpt-3.5-turbo"` since currently I see that by default it uses `gpt-4` for which you might not have access. For me though it is not the issue.

**Comment by Thevetat** [comment]
Going through netlify for me, and having issues with langchain / openai.  If I just call the openAI package without langchain, it is no issue.   If i run my env locally, I can use langchain.  When I deploy to netlify though, langchain times out on the openAI api calls.  Not sure what this adds but that is my experience.

**Comment by freddymercury** [comment]
hmm...I am getting a 429 -- too many requests. here is my client src:

`const { OpenAI } = require("langchain/llms/openai");
require("dotenv").config();

const openAIApiKey = process.env.OPENAI_API_KEY;
const model = new OpenAI({
  openAIApiKey,
  temperature: 0.9,
  modelName: "gpt-3.5-turbo",
});

const openAICall = async () => {
  const response = await model.call("who is john snow?");
  return response;
};

(async () => {
  try {
    const response = await openAICall();
    console.log(response);
  } catch (error) {
    console.error("Error:", error);
  }
})();
`

**Comment by henrikix** [comment]
@nfcampos Node `v18.16.0` and npm `9.5.1` (if it matters)

**Comment by henrikix** [comment]
Node version doesn't seem to matter. Tried out `20.0.0` - same deal.
Currently traced error to `axios-fetch-adapter.js` where I can see that it immediately fails without making any actual calls anywhere.

**Comment by sajadghawami** [comment]
@henrikix 

i was also getting the same error... turns out, i had a running subscription for `ChatGPT Pro`, but i did not set one up a general paid account. You can do that [here](https://platform.openai.com/account/billing/overview).

**Comment by henrikix** [comment]
@sajadghawami I already have it setup and as mentioned in my initial post when running the OpenAI node package directly everything works

**Comment by sajadghawami** [comment]
@henrikix 

Whats the exact error you are getting?
What node version are you using? (Recommended is 18+)
What langchain version are you using?
Can you provide some code?

**Comment by henrikix** [comment]
@sajadghawami If you scroll up a bit you can find all the information. (langchain both straight from repo and also latest version on my project)

**Comment by nfcampos** [comment]
@henrikix is it possible your local network has a proxy? By default fetch doesn't inherit proxy settings from your computer, so if that's the case you'd have to do as described in this issue https://github.com/hwchase17/langchainjs/issues/388#issuecomment-1490421309

**Comment by henrikix** [comment]
@nfcampos No proxies. Just in case I previously even tried switching to a 4G hotspot on my iPhone but the result was identical.

**Comment by henrikix** [comment]
@nfcampos Get the f**k out of here 😡 😂 😂 . 
Obviously I assumed it to be seconds and for some reason I initially added the timeout there because it seemed like it was not working so in my mind I increased the timeout instead of setting it to `20ms`.

Managed to dwelve into the deepest depths of `langchain` for 1+ day just to find out my fatal mistake was the dumbest one ..

**Comment by nfcampos** [comment]
Haha no worries

**Comment by liowalex** [comment]
> @nfcampos Get the f**k out of here 😡 😂 😂 . Obviously I assumed it to be seconds and for some reason I initially added the timeout there because it seemed like it was not working so in my mind I increased the timeout instead of setting it to `20ms`.
> 
> Managed to dwelve into the deepest depths of `langchain` for 1+ day just to find out my fatal mistake was the dumbest one ..

Hi @henrikix do you mind posting your solution to the issue? I'm running into something similar and wondering how you solved it
