### ISSUE TITLE
VectorStoreRetrieverMemory in langchainjs

### ISSUE THREAD

**Issue by MehdiChelh** [hwchase17/langchainjs#921]
Hello,

The following link describes the VectorStoreRetrieverMemory class (in the lanchain's python implementation), which seems to be extremely useful for referencing an external vector DB & it's text/vectors:

https://python.langchain.com/en/latest/modules/memory/types/vectorstore_retriever_memory.html

However, this feature doesn't seem present in langchainjs. Is there a plan to add it? Or should we use a different class in langchainjs ?

Thanks !

**Comment by YazeedAlKhalaf** [comment]
I just tried with version 0.0.70 and I was able to import it.
FYI, I am using Deno to use langchainJS in my backend.

**Comment by MehdiChelh** [comment]
Ah yes indeed I see that the feature was recently added to the repo, thanks @YazeedAlKhalaf !
I will close the issue now.
