### ISSUE TITLE
Additions for chromadb integration

### ISSUE THREAD

**Issue by jeffchuber** [hwchase17/langchainjs#96]
There are few things that can be improved in the integration:
- [ ] Add tests - this will require mocking the chroma backend responses to have any value and to be a part of regular CI. 
- [x] Add ability for documents to be stored in Chroma. Chroma can operate purely as a metadata-index store, but some users store documents in Chroma as well and and provide some hybrid search affordances. For example search where document `$contains` a string. https://github.com/chroma-core/chroma/blob/main/examples/where_filtering.ipynb

**Comment by jeffchuber** [comment]
the second is now completed thanks to @nfcampos ! https://github.com/hwchase17/langchainjs/pull/73/commits/de165f6b0c5432d9f9acddddfd48560925c4b474

🙌  thanks!

**Comment by cdiddy77** [comment]
Happy to take a crack at the first task. The CONTRIBUTING doc seems to say that I should self-assign if I want to do it, and so I shall.

**Comment by jeffchuber** [comment]
@cdiddy77 it would be great if you don't mind taking a look at the current test coverage and see where we have gaps! 🚀
