### ISSUE TITLE
Organization ID configuration

### ISSUE THREAD

**Issue by BaoHung** [hwchase17/langchainjs#995]
How can I configure the Organization ID?

**Comment by galtonova** [comment]
If you are talking about OpenAI organizations, you can provide it to the second `configuration` parameter of the constructors of `OpenAI` or `ChatOpenAI` classes.

```ts
new ChatOpenAI({ modelName: "gpt-3.5-turbo" }, { organization: "org-..." });
```

**Comment by BaoHung** [comment]
@galtonova Thanks, it worked well.
It'd be nice if this information is added to the document page 👍
